### ISSUE TITLE
rhabdoweisia fugax var. americana

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1006]
[Originally posted on GoogleCode (id 306) on 2012-08-31 by lufortin]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

Scientific name:rhabdoweisia fugax var. americana

ID of the specimen(s):MT00180411

Your name:Lucie Fortin

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-05 20:36Z]

Ce nom (var. americana) n'est pas dans les bases de données.

Seulement R. fugax entré ds le spécimen: il faut que l'entrée du nom coïncide avec celle du taxon pour que la base fonctionne.
