### ISSUE TITLE
Juncaceae – à ajouter dans TAXON

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1037]
[Originally posted on GoogleCode (id 419) on 2013-02-21 by cl.bouchard6]

La mise à jour de l'inventaire des Juncaceae est terminée.

Les documents pour les nouveaux taxons Juncus, Luzula et Oxychloe sont en pièces jointes. L'issue 418 déjà soumise concerne les taxons Distichia.

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-21 19:19Z]

Oxychloe fait

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-22 13:11Z]

Luzula fait. Voir document attaché. Dans celui-ci, les noms en jaune sont faits, ceux en bleu étaient déjà en bd (parfois les autorités diffèrent légèrement) et les taxons en vert posent des problèmes:
Luzula angustifolia	autorité inscrite (Wild.) Garckee : il n'y a pas de L. a. avec cette autorité, mais il y a une subsp. rubella avec cette autorité - s'agit-il d'une sous-espèce?

Luzula racemosa = vulcanica	Luzula racemosa Desv. = vulcanica Dew. - Je ne comprends pas cette entrée - racemosa et vulcanica sont distincts dans mes sources. Y a-t-il deux entrées à faire?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-22 18:43Z]

Juncus

Juncus albescens (triglumis)	(Lange) Fernald = Juncus albescens = triglumis var. a.

Juncus canaliculatus = macrophyllus	Liebmann - pourquoi = macrophyllus?

Juncus debilis (=acuminatus var. debilis)	A. Gray = debilis

Juncus marginatus - voir aristulatus	Rostkovius = marginatus

Juncus secundas 	Beauv. = secundus (mal épelé)

Juncus × buchenaui (= alpinus × articulatus) subsp. fuscoater	autorité inscrite  Dörfler : il n'y a pas de subsp. fuscoater dans ce taxon - inscrit sous buch.
la subsp. fuscoater va avec J. alpinus (plus bas ds liste!)

Juncus fasciculatus	autorité inscrite Brot. ou Bros - plante d'Algérie : je présume l'autorité être Bertol.

Tout est fait

Luc
