### ISSUE TITLE
Rumex - reclassement

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1043]
[Originally posted on GoogleCode (id 425) on 2013-02-25 by cl.bouchard6]

Ajouts car trouvés au reclassement pour Asie

Rumex syriacus Meisn.

Rumex thyanschanicus Losinsk. (début peu lisible)

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-25 21:25Z]

Rumex syriacus Meisn. = R. chalepensis Miller

Rumex thyanschanicus Losinsk. = thianschanicus acc
