### ISSUE TITLE
New Herbarium

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#113]
[Originally posted on GoogleCode (id 457) on 2013-03-04 by francois.lambert.3]

Institution: Morong Herbarium

ID of the specimen(s): 184087

Your name: François Lambert

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-05 17:50Z]

Nom ajouté et enregistrement mis à jour
