### ISSUE TITLE
Polygonaceae WAT - Taxons à ajouter

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1181]
[Originally posted on GoogleCode (id 901) on 2014-02-13 by cl.bouchard6]

Trouvés pour US

Corculum leptopus (H. &amp; A.) Stuntz

Eriogonum brevicaule Nutt. var. brevicaule
Eriogonum cernuum Nutt. var. cernuum
Eriogonum dichotomum Douglas
Eriogonum microthecum Nutt. var. simpsonii (Bentham) Reveal (est inscrit dans nom scientifique accepté)
Eriogonum ovalifolium Nutt. var. ochroleucum (Small ex Rydberg) M. Peck (est inscrit dans nom scientifique accepté)
Eriogonum umbellatum Torr. var. majus Hooker (est inscrit dans nom scientifique accepté)

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-13 18:29Z]

Corculum leptopus (H. & A.) Stuntz = Antigonon leptopus

Eriogonum brevicaule Nutt. var. brevicaule acc
Eriogonum cernuum Nutt. var. cernuum = Eriogonum cernuum Nutt.
Eriogonum dichotomum Douglas = Eriogonum niveum
Eriogonum microthecum Nutt. var. simpsonii acc
Eriogonum ovalifolium Nutt. var. ochroleucum acc
Eriogonum umbellatum Torr. var. majus acc
