### ISSUE TITLE
Taxon à revoir

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1188]
[Originally posted on GoogleCode (id 920) on 2014-02-20 by cl.bouchard6]

??? même taxon

Taxon ID 14279
Taxon ID 10748

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-21 16:23Z]

J'ai effacé la seconde entrée 14279 pour ne conserver que la première
Merci
L
