### ISSUE TITLE
Nouveaux noms Aspleniaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1190]
[Originally posted on GoogleCode (id 922) on 2014-02-20 by Simon.Chausse]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>

(Can., US, Eur., Asie)
Phyllitis scolopendrium (L.) Newman

(Can., US, Eur.)
Scolopendrium vulgare Sm.

(US)
Scolopendrium officinarum Sw.
Asplenium pinnatifidum Nutt.
Asplenium bradleyi D.C. Eaton
Asplenium montanum Willd.
Scolopendrium rhizophyllum Endl.

(A. Centrale)
Scolopendrium

(A. du Sud)
Phyllitis brasiliensis (Sw.) Kuntze

(Eur.)
Scolopendrium hemionitis (L.) Lag., D. García &amp; Clemente
Scolopendrium officinale DC.
Scolopendrium scolopendrium (L.) H. Karst.

(Asie)
Camptosorus sibiricus Rupr.
Asplenium cryptolepis X Trichomanes
Phyllis sibiricus Linn.

(Afrique)
Phyllitis hemionitis Kuntze

(Océanie)
Diellia falcata Brack.
Diellia

<b>ID of the specimen(s):</b>

<b>Your name:</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-21 15:29Z]

Phyllitis scolopendrium = Asplenium scolopendrium
Scolopendrium vulgare = Asplenium scolopendrium
Scolopendrium officinale = Asplenium scolopendrium
Scolopendrium scolopendrium = Asplenium scolopendrium
NB: il y a deux subsp.: subsp. americanum indig. en AN, et subsp. scolopendrium indig. en Eurasie et int. en AN [il faudra identifier les spécimens éventuellement]

Scolopendrium hemionitis (L.) Lag., D. García & Clemente = Asplenium hemionitis

Phyllitis hemionitis Kuntze = Asplenium sagittatum

Camptosorus sibiricus = Asplenium ruprechtii
Phyllis sibiricus Linn. = P. sibirica (Ruprecht) Kuntze [pas L.] = Asplenium ruprechtii

Asplenium cryptolepis X Trichomanes = A. x clermontae

Diellia falcata = Asplenium dielfalcatum Viane
Diellia = Asplenium
