### ISSUE TITLE
Woodsiaceae - reclassement

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1198]
[Originally posted on GoogleCode (id 945) on 2014-03-04 by margotton.herbier]

Woodsia mexicana                  us
Woodsia mollis                    a centrale  mexique
Woodsia montevidensis              a du sud
Woodsia rufidula                   europe
Woodsia cycloloba Hand.-Mazz.        asie
Woodsia elongata Hook.             asie
Woodsia manchuriensis Hooker         asie
Physematium manchuriense Nakai      asie
Woodsia polystichoides D.C. Eaton  asie
Woodsia obtusa Hook. (autorité différente) afrique

Diane Fournier

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-05 14:14Z]

Woodsia mexicana us : est-ce bien US? car cette sp n'y est pas présente (mauvaise det?) = W. mollis (pas au US non plus)
Woodsia mollis acc

Woodsia montevidensis acc
Woodsia rufidula = W. ilvensis

Woodsia cycloloba acc
Woodsia elongata acc
Woodsia manchuriensis acc
Woodsia polystichoides acc

Woodsia obtusa Hook. (autorité différente) afrique : il n'existe pas W. o. Hook. dans les bd - de plus, cette plante n'est pas rapportée pour l'Afrique ds la bd des plantes africaines de CJB - cela reste un problème à élucider
