### ISSUE TITLE
Polygonaceae WAT - Taxons à ajouter

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1203]
[Originally posted on GoogleCode (id 957) on 2014-03-06 by cl.bouchard6]

Trouvé pour US
Polygonum phytolaccaefolium Meisn.

Trouvé pour IPE
Polygonum amphibium var. stipulaceum (Coleman) Fern. f. terrestrial

Trouvés pour Ontario
Polygonum hydropiper var. projectum Stanford
Polygonum hydropiperoides f. leucochranthum A.H. Moore
Polygonum lapathifolium Linnaeus subsp. lapathifolium
Polygonum lapathifolium subsp. mesomorphum Danser

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-07 15:02Z]

Polygonum phytolaccaefolium Meisn. = phytolaccifolium = Aconogonon phytolaccifolium - déjà ds bd
Note: l'orthographe "ae" est généralement corrigé par "i" dans les noms

Polygonum amphibium var. stipulaceum (Coleman) Fern. f. terrestrial
Je présume que le déterminateur a soit voulu indiquer la forme terrestre de façon informelle en utilisant l'anglais, soit voulu indiquer f. terretre (Leers) S.F. Blake - dans les deux cas, cela indique la forme terrestre = Persicaria amphibia (les données sont ambigües concernant la var. pour ce nom)

Polygonum hydropiper var. projectum Stanford déjà ds bd = persicaria hydropiper

Polygonum hydropiperoides f. leucochranthum A.H. Moore = Persicaria hydropiperoides

Polygonum lapathifolium Linnaeus subsp. lapathifolium = Persicaria lapathifolia

Polygonum lapathifolium subsp. mesomorphum Danser = (Danser) Danser = Persicaria lapathifolia
