### ISSUE TITLE
Polygonaceae WAT

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1207]
[Originally posted on GoogleCode (id 965) on 2014-03-13 by cl.bouchard6]

Polygonaceae WAT - Taxons à ajouter

1. Trouvé pour US

Polygonum douglasii var. microspermum (Engelm.) Dorn

Polygonella croomii Chapm.

Polygonella brachystachya Meisn.

Rumex salicifolius var. triangulivalvis (Danser) J.C. Hickman

2. Polygonaceae WAT – Taxons entrés dans la rubrique «Nom scientifique accepté» mais pas dans la rubrique «Nom scientifique»

Polygonum aviculare Linnaeus subsp. buxiforme (Small) Costea &amp; Tardif

Polygonum sawatchense Small subsp. sawatchense

Polygonum americanum (Fischer &amp; C.A. Meyer) T.M. Schuster &amp; Reveal

Polygonum articulatum Linnaeus

Polygonum pinicola T.M. Schuster &amp; Reveal

Polygonum ramosissimum Michaux subsp. ramosissimum

Rumex lapponicus (I. Hiitonen) Czernov

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-14 19:16Z]

Polygonum douglasii var. microspermum (Engelm.) Dorn = Polygonum engelmannii

Polygonella croomii Chapm. = Polygonum polygamum var. croomii
Polygonella brachystachya Meisn. = Polygonum polygamum var. brachystachyum

Rumex salicifolius var. triangulivalvis (Danser) J.C. Hickman = Rumex triangulivalvis

noms scientifiques acc ajouté
Polygonum aviculare subsp. buxiforme
Polygonum sawatchense Small subsp. sawatchense
Polygonum americanum
Polygonum articulatum
Polygonum pinicola

Polygonum ramosissimum Michaux subsp. ramosissimum

Rumex lapponicus
