### ISSUE TITLE
Autorité différente

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1211]
[Originally posted on GoogleCode (id 975) on 2014-03-20 by cl.bouchard6]

BD taxon

ID11516 Rumex alpestris est inscrit comme nom accepté avec autorité Á. Löve

ID 18048 Rumex alpestris est inscrit avec autorité Jacquin

Est-ce 2 taxons différents?

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-20 17:11Z]

Claire

La fiche 11516 comportait une erreur d'autorité, maintenant corrigée. C'est Jacquin qui est correct. Je ne sais pourquoi une telle erreur s'est produite.

Luc
