### ISSUE TITLE
Juncaceae WAT - Taxons à ajouter

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1217]
[Originally posted on GoogleCode (id 991) on 2014-03-27 by cl.bouchard6]

Ontario
Juncus balticus Willd. var. littoralis Engelm. f. dissitiflorus Engelm.

US
Juncus balticus var. montanus Engelmann

A du Sud
Distichia (indet.) re issue 418

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-28 18:14Z]

Distichia: ajouté à bd 
NOTE: il faudra transférer ce genre en syn de Juncus et toutes les espèces, mais le travail taxonomique n'a pas encore été fait

Juncus balticus var. montanus = Juncus balticus subsp. ater

Juncus balticus Willd. var. littoralis Engelm. f. dissitiflorus Engelm = 
Juncus balticus subsp. littoralis
