### ISSUE TITLE
Juncaceae WAT - Taxons à ajouter

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1221]
[Originally posted on GoogleCode (id 1002) on 2014-04-02 by cl.bouchard6]

Nunavut (à confirmer)
Luzula arcuata var. confusa (Lindeberg) Kjellm. (autorité différente de Vascan)

Alaska
Juncus castaneus Smith subsp. castaneus

Yukon
Luzula arcuata subsp. unalaschkensis (Buchenau) Hultén
Luzula arcuata (Wahlenberg) Swartz subsp. arcuata
Luzula parviflora (Ehrhart) Desvaux subsp. parviflora
Luzula wahlenbergii subsp. piperi (Coville) Hultén

US
Juncus bufonius var. occidentalis F.J. Hermann
Juncus nevadensis S. Watson var. nevadensis

EUR
Juncus effusus Linnaeus subsp. effusus
___________________

TAXON ID 7404 : le nom accepté pour Juncus albescens (Lange) Fernald est :
Juncus triglumis Linnaeus var. albescens Lange
ou
Juncus triglumis Linnaeus subsp. albescens (Lange) Hultén (re : Vascan 16875 et 16876)

TAXON ID 16860 et 16861 :  Le nom scientifique indiqué est Luzula arcuata mais 16861 a un espace placé à la fin de Luzula arcuata avec un rang de sous-espèce

TAXON ID 8151 : Luzula multiflora subsp. frigida : autorité différente pour subsp. (Rouy vs (Buchenau) V.I. Krecztowicz)
___________________

À entrer sous «Nom scientifique» (déjà entré comme «Nom accepté»)
Luzula alpinopilosa (Chaix) Breistroffer subsp. alpinopilosa
Luzula comosa E. Meyer var. comosa 

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-10 20:54Z]

TAXON ID 16860 et 16861 :  Le nom scientifique indiqué est Luzula arcuata mais 16861 a un espace placé à la fin de Luzula arcuata avec un rang de sous-espèce
16861 supprimé

Juncus castaneus subsp. castaneus acc
Luzula arcuata subsp. unalaschkensis (Buchenau) Hultén acc
Luzula arcuata (Wahlenberg) Swartz subsp. arcuata acc
Luzula wahlenbergii subsp. piperi (Coville) Hultén = Luzula piperi

Juncus bufonius var. occidentalis = Juncus bufonius var. bufonius
Juncus nevadensis S. Watson var. nevadensis = Juncus nevadensis

Juncus effusus Linnaeus subsp. effusus = Juncus effusus

TAXON ID 7404 : le nom accepté pour Juncus albescens (Lange) Fernald est :
Juncus triglumis Linnaeus var. albescens Lange
ou
Juncus triglumis Linnaeus subsp. albescens (Lange) Hultén
correction a été faite au 7004 pour harmoniser avec VASCAN et les autorités ont été corrigées là où nécessaire

TAXON ID 8151 : Luzula multiflora subsp. frigida : autorité différente pour subsp. (Rouy vs (Buchenau) V.I. Krecztowicz)
corrigé Rouy

Luzula alpinopilosa (Chaix) Breistroffer subsp. alpinopilosa acc
Luzula comosa E. Meyer var. comosa acc

Merci pour la correction des erreurs
L

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2014-04-17 15:17Z by cl.bouchard6]

Yukon
Luzula parviflora (Ehrhart) Desvaux subsp. parviflora - je ne trouve pas dans la BD

Claire B.

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2014-04-17 15:34Z by cl.bouchard6]

Nunavut (à confirmer)
Luzula arcuata var. confusa (Lindeberg) Kjellm. (autorité différente de Vascan) - je ne trouve pas dans la BD

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-17 19:19Z]

Luzula parviflora (Ehrhart) Desvaux subsp. parviflora acc

Luzula arcuata var. confusa (Lindeberg) Kjellm.: avec cette autorité, il s'agit de f. confusa selon TROPICOS et IPNI: Luzula arcuata fo. confusa (Lindeb.) Kjellm.
la var. confusa est associée à Lange seulement
donc j'ai entré la forme. Si on veut la var., il faudra mettre le nom de var. correct (avec ajout d'une note de détermination)
