### ISSUE TITLE
Aspleniaceae (dernière destination)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1222]
[Originally posted on GoogleCode (id 1003) on 2014-04-03 by Simon.Chausse]

*Europe et Asie*
Ceterach officinarum DC.
Ceterach aureum L.
Ceterach aureum Cav.

*Europe*
Ceterach officinarum Willd.
Grammitis ceterach Sw.
Asplenium ceterach L.
Asplenium ceterach f. crematum Sloover (L.)

Simon Chaussé

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-15 13:13Z]

Ceterach officinarum DC nom. illeg. hom. = Asplenium ceterach
Ceterach officinarum Willd. = Asplenium ceterach
Asplenium ceterach acc
Asplenium ceterach f. crematum Sloover : non retrouvé ds bd ms = Asplenium ceterach [pour l'instant - ajouté ds bd comme nom à valider]
Ceterach aureum L" [non trouvé] =? Cav. = (Cav.) Buch ds IPNI [Buch ds TROPICOS, erroné] = Asplenium aureum Cav.
