### ISSUE TITLE
Modification Aspleniacées

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1224]
[Originally posted on GoogleCode (id 1005) on 2014-04-03 by Simon.Chausse]

Asplenium platyneuron (L.) Britton, Sterns &amp; Poggenb.
    
   il y avait aussi l'autorité (L.) Oakes et (L.) D.C. Eaton

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-08 14:21Z]

Simon

Asplenium platyneuron (L.) Britton, Sterns & Poggenb.
    
   il y avait aussi l'autorité (L.) Oakes et (L.) D.C. Eaton

(L.) Oakes = (L.) D.C. Eaton = D.C. Eaton nom. inval. [même réf] = Asplenium platyneuron (L.) BSP

Le nom n'a même pas été formellement créé par Eaton, qui mentionne le nom par Oakes en note seulement (provenant d'un manuscrit)

Je les ai ajoutés à la bd comme non publiés
