### ISSUE TITLE
Ajouts Aspleniaceae 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1231]
[Originally posted on GoogleCode (id 1016) on 2014-04-10 by Simon.Chausse]

*A. central*
Asplenium auritum var. foeniculaceum Baker (Sw.)

Asplenium auritum var. bipinnatisectum Mett. (Sw.)

*A. Sud*
Asplenium lunulatum Sw.

*Qc*
Camptosorus rhizophyllus fo. Auriculatus Clute (L.)

Simon Chaussé

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-14 13:46Z]

Camptosorus rhizophyllus fo. Auriculatus Clute (L.)
Problème d'autorité: la f. auriculatus a été décrite par Ralph Hoffm.
le seul nom de f. sous cette espèce attribuée à Clute est f. intermedius (Arthur) Clute
Je ne crois pas que c'est ce dont il s'agit - le déterminateur a donc fait une erreur, ce qui n'est pas nouveau
Camptosorus rhizophyllus f. auriculatus est déjà dans la bd = Asplenium rhizophyllum

Asplenium lunulatum acc
Asplenium auritum var. bipinnatisectum Mett. = A. cuspidatum Lam.
Asplenium auritum var. foeniculaceum Baker = (Kunth) Baker fide IPNI = A. fragrans Sw. [ou A. cuspidatum selon d'autres, ms controversé et ambigü - valider taxo éventuellement]
