### ISSUE TITLE
Martineau 2014 – Taxon

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1272]
[Originally posted on GoogleCode (id 1131) on 2014-05-18 by cl.bouchard6]

Sticherus flagellaris (Bory) H. St. John ID 192670 det 1
Sticherus flagellaris (Bory ex Willd.) Ching ID 192670 det 2

Sticherus lobatus Wakef. ID 192671

Sticherus tenera (R. Br.) Ching ID 192672 et ID 192673 det 1(inscrit Sticherus tener (R.Br.) Ching)
Sticherus tenera (R. Br.) Ching forme B ID 192672 det 2 (inscrit Sticherus tener (R.Br.) Ching forme B)
Sticherus tenera (R. Br.) Ching forme A ID 192673 det 2 (inscrit Sticherus tener (R.Br.) Ching forme A)

Dicranopteris linearis (Burm. f.) Underw. ID 192674 det 1
Gleichenia linearis (Burm. f.) C.B. Clarke ID 192674 det 2

Gleichenia dicarpa R. Br. ID192676 et ID 192677

Gleichenia alpina R. Br. ID 192678

Gleichenia remota (Kaulf.) Spreng. ID 192679 det 1
Sticherus remotus (Kaulf.) Chrysler ID 192679 det 2

Gleichenia abscida Rodway ID 192680

Gleichenia brevipubis Christ ID 192681 det 1
Sticherus brevipubis (Christ) A.R. Sm. ID 192681 det 2

Adiantum rhizophorum Sw. ID 192682

Adiantum reniforme var. reniforme ID 192684 (Adiantum reniforme L. var. reniforme)

Adiantum reniforme L. ID 192685

Adiantum reniforme var. pusillum ID 192687 det - autorité Bolle
Adiantum reniforme subsp. pusillum ID 192687 det 2 - autorité (Bolle ) Rivas Mart.

Adiantum pyramidale (L.) Willd. ID 192688

Adiantum argutum Splitg. ID 192690

Adiantum lucidum (Cav.) Sw. ID 192691

Adiantum serratodentatum autorité Willd. ID 192692 det 1
Adiantum serratodentatum autorité Humb. &amp; Bonpl. ex Willd. ID 192692 det 2
Adiantum petiolatum x Adiantum serratodentatum ID 192693

Adiantum capillus-veneris L. ID 192695

Cryptogramma crispa (L.) R. Brown ID 192698

Cryptogramma acrostichoides R. Br. in Richards. ID 192699 det 1
Cryptogramma crispa var. acrostichoides ID 192699 det 2 (Cryptogramma crispa (L.) R. Br. var. acrostichoides (R.Br.) C.B.Clarke)
Cryptogramma acrostichoides R. Br. ID 192699 det 3

Cosentinia vellea (Aiton) Tod. ID 192700 et ID 192701

Humata repens (L. f.) J. Small ex Diels ID 192703

Cheilanthes acrostica (Balb.) Tod. ID 192704

Cheilanthes tinaei Todero ID 192705

Cheilanthes maderensis Lowe ID 192706

Cheilanthes gracillima D.C. Eaton ID 192707

Cheilanthes pulchella Bory ex Willd. ID 192708

Cheilanthes hispanica Mett. ID 192709

Cheilanthes guanchica C. Bolle ID 192710

Cheilanthes tomentosa Link ID 192711

Cheilanthes austrotenuifolia Quirk &amp; Chambers ID 192712

Notholaena marantae autorité (L.) Desv. ID 192713 det 1
Notholaena marantae autorité (L.) R. Br. ID 192713 det 2

Ceratopteris pteridoides (Hook.) Hieron. ID 192714

Pellaea calomelanos (Swartz) Link ID 192715

Pellaea viridis (Forssk.) Prantl ID 192716

Antrophyum guayanense Hieron. ID 192717

Vittaria elongata Sw. ID 192718

Vittaria isoetifolia Bory ex Fée ID 192719

Hymenophyllum wrightii Bosch ID 192720 det 2

Hymenophyllum tunbrigense (L.) Smith ID 192721

Hymenophyllum wilsonii Hooker ID 192722 det 1
Hymenophyllum peltatum (Poir.) Desv. ID 192722 det 2

Hymenophyllum capillare Desv. ID 192723

Hymenophyllum hygrometricum (Poir.) Desv. ID 192724

Hymenophyllum fucoides Swartz ID 192726

Hymenophyllum crassipetiolatum Stolze ID 192727

Hymenophyllum flabellatum Labill. ID 192728

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-20 19:25Z]

Sticherus flagellaris(Bory) H. St. John = Sticherus flagellaris (Bory ex Willd.) Ching acc
Sticherus lobatus Wakef. acc
Sticherus tener (R. Br.) Ching est OK (TROPICOS est erroné)
Sticherus tener (R.Br.) Ching forme B - entré unknown
Sticherus tener (R.Br.) Ching forme A = Sticherus urceolatus

Dicranopteris linearis (Burm. f.) Underw acc
Gleichenia linearis (Burm. f.) C.B. Clarke = Dicranopteris linearis

Gleichenia dicarpa R. Br. acc
Gleichenia alpina R. Br. acc
Gleichenia abscida Rodway acc

Gleichenia remota (Kaulf.) Spreng. = Sticherus remotus (Kaulf.) Chrysler acc
Gleichenia brevipubis Christ = Sticherus brevipubis (Christ) A.R. Sm. acc

Adiantum rhizophorum Sw. acc
Adiantum reniforme var. reniforme acc [à valider]
Adiantum reniforme L. acc

Adiantum reniforme var. pusillum Bolle =  Adiantum reniforme subsp. pusillum (Bolle ) Rivas Mart. = Adiantum reniforme

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-20 21:00Z]

Adiantum pyramidale acc
Adiantum argutum Splitg. acc
Adiantum lucidum (Cav.) Sw. acc
Adiantum serratodentatum autorité Willd. = [mauvaise interprétation des autorités] =
Adiantum serratodentatum autorité Humb. & Bonpl. ex Willd. acc
Adiantum petiolatum x Adiantum serratodentatum acc [à valider éventuellement]
Adiantum capillus-veneris acc

Cryptogramma crispa (L.) R. Brown acc
Cryptogramma acrostichoides R. Br. in Richards. = in non nécessaire = acc
Cryptogramma crispa var. acrostichoides : déjà ds bd [4187] = C. a.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-21 15:55Z]

Cosentinia vellea (Aiton) Tod. acc

Humata repens = Davallia repens [acc?]

Cheilanthes acrostica (Balb.) Tod. = Allosorus acrosticus acc
Cheilanthes tinaei Todero = Allosorus tinaei acc
Cheilanthes maderensis Lowe = Allosorus pteridioides acc
Cheilanthes gracillima D.C. Eaton acc
Cheilanthes pulchella Bory [ex Willd.] = [in Willd.]= Allosorus fragilis acc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-21 17:56Z]

Cheilanthes hispanica Mett. = Allosorus hispanicus acc
Cheilanthes guanchica C. Bolle = Allosorus guanchicus acc
Cheilanthes tomentosa Link = Myriopteris tomentosa
Cheilanthes austrotenuifolia Quirk & Chambers acc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-22 20:54Z]

Notholaena marantae autorité (L.) Desv. ID 192713 det 1 = Paragymnopteris marantae
Notholaena marantae autorité (L.) R. Br. ID 192713 det 2 = Paragymnopteris marantae acc

Ceratopteris pteridoides (Hook.) Hieron. acc

Pellaea calomelanos (Swartz) Link acc
Pellaea viridis (Forssk.) Prantl = Cheilanthes viridis acc

Antrophyum guayanense Hieron. = Polytaenium guayanense acc

Vittaria elongata Sw. = Haplopteris elongata acc

Vittaria isoetifolia Bory ex Fée acc

Hymenophyllum wrightii Bosch acc
Hymenophyllum tunbrigense (L.) Smith

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-23 20:37Z]

Hymenophyllum wilsonii Hooker = Hymenophyllum peltatum acc
Hymenophyllum capillare Desv. acc
Hymenophyllum hygrometricum (Poir.) Desv. acc
Hymenophyllum fucoides acc
Hymenophyllum crassipetiolatum Stolze acc
Hymenophyllum flabellatum Labill. acc
