### ISSUE TITLE
Martineau 2014 – Taxon

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1275]
[Originally posted on GoogleCode (id 1137) on 2014-05-25 by cl.bouchard6]

Pteris vittata L. ID 192774

Pteris bahamensis (J. Agardh) Fée ID 192775 det 2

Lindsaea lancea (L. Bedd.) var. falcata (Dryand.) Ros. ID 192776

Lindsaea lancea (L.) Bedd. var. lancea ID 192777

Lindsaea parkeri (Hook.) Kuhn subsp. parkeri ID 192778

Lindsaea linearis Swartz ID 192779

Saccoloma inaequale (Kunze) Mett. ID 192780

Pneumatopteris pennigera (Forst.f.) Holtt. ID 192781

Oreopteris limbosperma (Bell. ex. All.) Holub ID 192782 det 1
Oreopteris limbosperma Holub ID 192782 det 2

Davallia canariensis (L.) Sm. ID 192786

Lophosoria quadripinnata (J.F. Gmel.) C. Chr. ID 192787

Stenogramma pozoi (Lag.) Iwatsuki ID 192788

Blechnum spicant – autorité (L.) Roth ID 192789 det 1 et ID 192790 det 1
Blechnum spicant (L.) Sm. ID 192789 det 2 et ID 192790 det 2

Blechnum serrulatum Rich. ID 192791

Blechnum vulcanicum (Blume) Kuhn ID 192792 et ID 192793

Blechnum wattsii Tind. ID 192794 et ID 192795

Blechnum fluviatile (R.Br.) E.J. Lowe ex Salomon ID 192796

Blechnum penna-marina (Poiret) Kuhn subsp. alpina (R.BR.) T.C. Chambers &amp; P.A. Farrant ID 192797

Woodwardia radicans (L.) Sm. ID 192799 et ID 192802

Woodwardia areolata (L.) T. Moore ID 192800

Woodwardia fimbriata Sm. ID 192801

Elaphoglossum splendens Brack. ID 192803

Elaphoglossum luridum (Fée) Christ ID192804

Asplenium anisophyllum-boltonii ID 192806 det 1
Asplenium boltonii Hook. ex Schelpe ID 192806 det 2

Asplenium sagittatum (DC.) Bunge, A. J. ID 192808 det 1 et det 2

Asplenium viviparum var. lineatum (Sw.) Tardieu ID 192809 det 1 et ID 192810 det 1
Asplenium viviparum (L. f.) C.Presl 192809 det 2 et ID 192810 det 2

Asplenium hemionitis L. var. hemionitis ID 192811

Asplenium trichomanes L. subsp. pachyrachis (Christ) Lovis &amp; Reichstein ID 192812

Asplenium sulcatum Lam. ID 192814 det 2 et ID 192815 det 2

Asplenium aureum L. var. aureum ID 192819 det 1

Asplenium hispanicum Cosson ID 192823

Asplenium appendiculatum (Labill.) C.Presl subsp. appendiculatum ID 192824

Asplenium × alternifolium Wulfen subsp. alternifolium ID 192827

Asplenium monodon Liebm. ID 192830

Asplenium foresiense Le Grand ID 192831

Asplenium yunnanense Franch. ID 192832

Asplenium fissum Kit. ex Willd. ID 192833

Asplenium trichomanes-dentatum L. ID 192835

Asplenium × pagesii Litard. ID 192837

Asplenium obovatum  Viv. subsp. lanceolatum (Fiori) Pinto da Silva ID 192838

Asplenium lepidum C. Presl subsp. lepidum ID 192840

Asplenium haussknechtii Godet &amp; Reut. ID 192840

Asplenium obovatum Viv. subsp. obovatum ID 192841

Asplenium jahandiezii avec autorité (Litard.) Rouy ID 192842 det 1
Asplenium jahandiezii Rouy ID 192842 det 2

Asplenium balearicum Shivas ID 192843

Athyrium filix-femina (L.) Mertens var. cyclosorum Rupr. ID 192848 det 2 et ID 192849 det 2

Cystopteris alpina avec autorité (Jacq.) Desv. ID 192853 det 2

Cystopteris dickieana R. Sim ID 192857

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-26 14:21Z]

Pteris vittata acc
Pteris bahamensis (J. Agardh) Fée ACC

Lindsaea lancea (L. Bedd.) var. falcata (Dryand.) Ros. acc ms à valider (falcata?)
Lindsaea lancea (L.) Bedd. var. lancea acc
Lindsaea parkeri (Hook.) Kuhn subsp. parkeri acc
Lindsaea linearis Swartz acc

Saccoloma inaequale (Kunze) Mett. acc

Pneumatopteris pennigera (Forst.f.) Holtt. syn =  Cyclosorus pennigerus [à valider]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-26 19:25Z]

Blechnum serrulatum Rich.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-27 19:20Z]

Blechnum spicant – autorité (L.) Roth acc
Blechnum spicant (L.) Sm. = nom. inval. = (L.) Roth

Elaphoglossum splendens Brack. = (Bory ex Willdenow) Brackenridge acc
Elaphoglossum luridum acc

Asplenium boltonii acc
Asplenium sagittatum (DC.) Bange acc
Asplenium viviparum var. lineatum (Sw.) Tardieu = Asplenium daucifolium var. lineatum
Asplenium viviparum = Asplenium daucifolium var. viviparum
Asplenium hemionitis var. hemionitis acc
Asplenium trichomanes L. subsp. pachyrachis (Christ) Lovis & Reichstein acc
Asplenium sulcatum Lam. acc
Asplenium aureum var. aureum = A. aureum acc
Asplenium hispanicum Cosson acc
Asplenium appendiculatum (Labill.) C.Presl subsp. appendiculatum acc


ATT'N:
Asplenium anisophyllum-boltonii à éclaircir - var. boltonii in TRO, ms pas autres bd

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-27 20:58Z]

Asplenium × alternifolium Wulfen subsp. alternifolium acc
Asplenium monodon Liebm. acc
Asplenium foresiense = Asplenium foreziense
Asplenium yunnanense Franch. = Asplenium exiguum subsp. yunnanense [mal appliqué ici]
Asplenium fissum Kit. ex Willd. = Willd. = acc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-28 14:01Z]

Asplenium trichomanes-dentatum L = A. dentatum
Asplenium × pagesii Litard. acc
Asplenium obovatum  Viv. subsp. lanceolatum (Fiori) Pinto da Silva = Asplenium obovatum subsp. billotii
Asplenium obovatum Viv. subsp. obovatum acc
Asplenium lepidum C. Presl subsp. lepidum acc
Asplenium haussknechtii Godet & Reut. = Asplenium lepidum subsp. haussknechtii
Asplenium balearicum Shivas acc
Asplenium jahandiezii avec autorité (Litard.) Rouy acc
Asplenium jahandiezii Rouy [erroné, ignore basionyme] = (Litard.) Rouy

Athyrium filix-femina (L.) Mertens var. cyclosorum Rupr. acc

Cystopteris alpina (Jacq.) Desv. = (Lam.) Desv.
Cystopteris dickieana R. Sim = C. fragilis
