### ISSUE TITLE
Baccharis - Taxon

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1295]
[Originally posted on GoogleCode (id 1212) on 2014-07-21 by cl.bouchard6]

Pour Brésil et Argentine

Baccharis tenuifolia DC ID 193375 det 1
Baccharis linearifolia (Lam.) Pers. ID 193375 det 2

Baccharis subumbelliformis Heering ID 192762 det 1 ; ID 193654 det 1
Baccharis sphenophylla Dusén ID 192762 det 2 ; ID 193654 det 2

Baccharidastrum triplinervium (Less.) Cabrera ID 192766 det 1 ; ID 193166 det 1 ; ID 138007 det 1
Baccharis vulneraria Baker ID 192766 det 2 ; ID 193166 det 2 ; ID 138007 det 2

Baccharis usterii Heering ID 191095 det 1
Baccharis junciformis DC. ID 191095 det 2

Baccharis linearifolia (Lam.) Pers. ID 191100 det 2

Baccharis pingraea DC. ID 193130 det 2

Baccharis crispa Spreng. ID 193204 det 2

Baccharis glutinosa Pers. ID 193300 det 2

Baccharis flabellata Hook. &amp; Arn. ID 193301 det 2

Baccharis punctulata DC. ID 193302 det 2

Baccharis penningtonii Heering ID 193320 det 2

Baccharis articulata (Lam.) Pers. ID 193458

Baccharis salicifolia (Lam.) Pers. ID 193377 det 2

Baccharis trinervis (Lam.) Pers. ID 193378

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-23 14:28Z]

Baccharis linearifolia acc
Baccharis tenuifolia DC = Baccharis pseudotenuifolia
Baccharis subumbelliformis Heering unknown
Baccharis sphenophylla unknown
Baccharidastrum triplinervium (Less.) Cabrera = Baccharis vulneraria acc
Baccharis usterii acc
Baccharis junciformis acc
Baccharis pingraea acc
Baccharis crispa Spreng. acc
Baccharis glutinosa Pers. syn B. salicifolia fide TRO ms semble acc par Heiden

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-24 12:59Z]

Baccharis flabellata Hook. & Arn. acc
Baccharis punctulata DC. acc
Baccharis penningtonii Heering acc
Baccharis articulata (Lam.) Pers acc
Baccharis salicifolia (Lam.) Pers. = Baccharis salicifolia (Ruiz & Pavón) Persoon acc
Baccharis trinervis (Lam.) Pers. unknown
