### ISSUE TITLE
Ulota coarctata

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1487]
[Originally posted on GoogleCode (id 313) on 2012-09-21]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

Scientific name: Ulota coarctata

ID of the specimen(s):MT00180436

Your name:Lucie Fortin

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-16 20:56Z]

svp: ne pas faire des messages différents. On peut ajouter au message envoyé quand c'est la même espèce.
Luc
