### ISSUE TITLE
Noms acceptés - Polygonaceae

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1523]
[Originally posted on GoogleCode (id 676) on 2013-07-11]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Trouvés pour Amérique centrale :

Polygonum punctatum Ell. Small var. typicum Fassett, Brittonia 6 (4):371.

Polygonum punctatum Ell. var. eciliatum Small

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-15 15:51Z]

Polygonum punctatum Ell. Small var. typicum = Persicaria punctata

Polygonum punctatum Ell. var. eciliatum : les données sont incohérentes concernant ce taxon, bien décrit sous punctatum Ell. et non Buch.-Ham. (comme ds Plant List, erronée)
Un isotype à HUH est annoté Polygonum densiflorum C.F.W. Meissner (= Persicaria glabra (Willd.) M.Gómez fide PL)
C'est certainement un Persicaria selon la photo du type - L,espèce reste à déterminer - P. punctatum se rend au Mexique - non complètement résolu
En attendant, placer sous Persicaria - ce ne peut être erroné

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-26 13:17Z]

Polygonum punctatum Ell. var. eciliatum = Persicaria punctata
