### ISSUE TITLE
Accepted names for new Polygonaceae found in MT inventory

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1524]
[Originally posted on GoogleCode (id 686) on 2013-07-26]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>
Noms acceptés pour les suivants?

Asie:
Tovara virginiana var. filiformis (Thunb.) Steward
http://www.tropicos.org/Name/50135318

USA:
Tracaulon sagittatum (L.) Small
http://www.tropicos.org/Name/26001846

Polygonum punctatum var. littorale Fassett
http://www.tropicos.org/Name/26001125

Polygonum pensylvanicum var. nesophilum Fernald
http://www.tropicos.org/Name/26001749

Polygonum pensylvanicum var. rosiflorum Norton
http://www.tropicos.org/Name/26001747

USA, PEI, QC, ON, MB:
Polygonum punctatum var. confertiflorum (Meisn.) Fassett
http://www.tropicos.org/Name/26000887

ON, QC:
Polygonum acre var. leptostachyum Meisn.
http://www.tropicos.org/Name/26001088

QC:
Polygonum acre Ell. var. parvum Victorin &amp; Rouss.
revoir BD TAXON entrée 10123
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=242100107
(Polygonum punctatum Elliott var. parvum Marie-Victorin &amp; Rousseau)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-26 13:14Z]

QC:
Polygonum acre Ell. var. parvum Victorin & Rouss.
revoir BD TAXON entrée 10123
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242100107
(Polygonum punctatum Elliott var. parvum Marie-Victorin & Rousseau)
= Persicaria punctata

Je n'ai pas à "revoir" l'entrée: elle est conforme. Ce sont les récolteurs (ou le déterminateur) qui a incorrectement attribué parvum à P. acre, une combinaison qui ne semble jamais avoir été faite. Polygonum acre (Kunth nom. illeg. ou Lam.)= punctatum et à l'époque, ils ont dû penser que c'était le bon nom. Cela n'en fait pas un nom valide mais une simple transposition de concept sans validité, comme il y en a tant à l'herbier.

Polygonum acre var. leptostachyum Meisn. = Persicaria punctata

Polygonum punctatum var. confertiflorum (Meisn.) Fassett = Persicaria punctata

Tovara virginiana var. filiformis (Thunb.) Steward = Persicaria filiformis

Tracaulon sagittatum (L.) Small= Persicaria sagittata

Polygonum punctatum var. littorale Fassett = Persicaria punctata

Polygonum pensylvanicum var. nesophilum Fernald = Persicaria pensylvanica

Polygonum pensylvanicum var. rosiflorum Norton = Persicaria pensylvanica
