### ISSUE TITLE
Nouveauxs taxons à ajouter

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1526]
[Originally posted on GoogleCode (id 705) on 2013-08-28]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

NB: ces noms sont tous déjà &quot;saisis&quot; dans le champ du nom scientifique par importation du Workbench d'Alexandre, il faut seulement les ajouter à la table TAXON

<b>Scientific name:</b>
<b>ID of the specimen(s):</b>

Carex echinodes
186378, 186379

Cuscuta gronovii var. gronovii
186427, 186428

Euonymus alata
186438, 186439

Festuca rubra subsp. rubra
186442, 186443

Fragaria vesca subsp. vesca
186444, 186445

Geranium pusillum
186446, 186447

Hypericum perforatum subsp. perforatum
186458, 186459

Lonicera dioica var. dioica
186474, 186475

Malus baccata
186484, 186485

Ribes alpinum
186518, 186519

Teucrium canadense subsp. viscidum
186576, 186577

Thinopyrum ponticum
186580, 186581

Verbena hastata var. hastata
186594, 186595

Viburnum opulus subsp. opulus
186602, 186603

Viola pubescens var. scabriuscula
186608, 186609

NB: ces noms sont tous déjà &quot;saisis&quot; dans le champ du nom scientifique par importation du Workbench d'Alexandre, il faut seulement les ajouter à la table TAXON

<b>Your name:</b>
Geoffrey Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-29 13:56Z]

Carex echinodes
186378, 186379
Déjà ds bd
Il y avait un espace de trop à la fin du nom dans l'entrée de A. Bergeron, ce qui empêche la bd de reconnaître le nom: il faut à tout prix enlever tout espace à la fin des noms

Cuscuta gronovii var. gronovii
186427, 186428 (ce no est Danthonia! 186426)

Euonymus alata
186438, 186439
The epithet has an orthographic error: the correct name is alatus - the taxon is already in the db

Festuca rubra subsp. rubra
186442, 186443
fait

Fragaria vesca subsp. vesca
186444, 186445
fait


Geranium pusillum
186446, 186447
fait

Hypericum perforatum subsp. perforatum
186458, 186459
fait

Lonicera dioica var. dioica
186474, 186475
fait

Malus baccata
186484, 186485
fait

Ribes alpinum
186518, 186519
fait

Teucrium canadense subsp. viscidum
186576, 186577
fait

Thinopyrum ponticum
186580, 186581
fait

Verbena hastata var. hastata
186594, 186595
la var. hastata n'est pas retenue par l'auteur de FNA - syn ds VASCAN


Viburnum opulus subsp. opulus
186602, 186603
fait

Viola pubescens var. scabriuscula
186608, 186609

NOTE IMP: je note que le continent n'a pas été entré dans la géographie - il ne faudrait pas oublier de le faire à l'importation, même si le récolteur ne fournit pas l'info - j'ai fait un changement global sur les récoltes de Alexandre
