### ISSUE TITLE
3 new taxons

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1528]
[Originally posted on GoogleCode (id 711) on 2013-09-16]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>

Tilia ×vulgaris
186648

Epilobium ciliatum subsp. ciliatum var. ciliatum
186650

Acer ×freemanii
186652

<b>ID of the specimen(s):</b>

voir ci-dessus

Your name: Geoffrey Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-16 17:12Z]
