### ISSUE TITLE
2 new taxa for specimens being deposited at MT by Alexandre Bergeron

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1531]
[Originally posted on GoogleCode (id 728) on 2013-10-09]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>
186841:
Clematis serratifolia

186864:
Epilobium parviflorum

<b>ID of the specimen(s):</b>
Clematis serratifolia:
186841

Epilobium parviflorum:
186864

<b>Your name:</b>
Geoffrey Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-09 20:59Z]

Clematis serratifolia serait nouveau pour le Qc., le Canada et FNA!

Epilobium parviflorum est nouveau pour le Qc.
