### ISSUE TITLE
7 new New Zealand taxa for 8 records

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1532]
[Originally posted on GoogleCode (id 730) on 2013-10-10]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>

186441
Helichrysum dimorphum x Raoulia glabra
Helichrysum dimorphum Cockayne x Raoulia glabra Hooker f.

186443
Raoulia glabra
Raoulia glabra Hooker f.

186445
Helichrysum dimorphum
Helichrysum dimorphum Cockayne

186447
Griselinia lucida
Griselinia lucida (J.R. Forster &amp; G. Forster) G. Forster

186449
Laurelia novae-zelandiae
Laurelia novae-zelandiae A. Cunningham

186451
Olea lanceolata
Olea lanceolata Hooker f.

186453
186455
Nothofagus solanderi
Nothofagus solanderi (Hooker f.) Oersted

<b>ID of the specimen(s):</b>

<b>Your name:</b>
Geoffrey Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-10 19:30Z]

186451
Olea lanceolata : j'ai ajouté une annotation électronique: Nestegis lanceolata - si elle est imprimée et ajoutée au spécimen, enlever det. el. de bd

Luc
