### ISSUE TITLE
Nom accepté pour spécimen de M-V qui sera photographié

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1536]
[Originally posted on GoogleCode (id 896) on 2014-02-11]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>
Salix pellita Anderss. var. denudata Anderss.

<b>ID of the specimen(s):</b>
non encore saisi

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-13 14:24Z]

Geoff
Le nom Salix pellita var. denudata Anderss. n'existe pas dans les bd
Mais il existe un Salix candida var. denudata Anderss.

Est-ce bien pellita?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-17 14:42Z]

entré comme Salix pellita var. denudata, mais sans autorité car le nom n'existe pas

le spécimen est-il pellita ou candida?

Luc
