### ISSUE TITLE
Nom avec autorités acceptées à ajouter, autorité de synonyme à vérifier

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1538]
[Originally posted on GoogleCode (id 969) on 2014-03-17]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>

ID de taxon dans la table TAXON de la base de données MT = 362
nom scientifique = Alnus viridis (Chaix) de Candolle subsp. crispa E.E. Nelson
nom scientifique accepté = Alnus viridis (Chaix) de Candolle subsp. crispa (Aiton) Turrill

dans la table TAXON, il manque l'enregistrement suivant :
nom scientifique = Alnus viridis (Chaix) de Candolle subsp. crispa (Aiton) Turrill
nom scientifique accepté = Alnus viridis (Chaix) de Candolle subsp. crispa (Aiton) Turrill

Vascan [&lt;http://data.canadensys.net/vascan/taxon/3681?lang=fr&gt;]
Alnus viridis (Chaix) de Candolle subsp. crispa (Aiton) Turrill

<b>ID of the specimen(s):</b>
NA

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-18 14:41Z]

Alnus viridis (Chaix) de Candolle subsp. crispa E.E. Nelson corrigé car erroné

en faisant cela, le second problème est réglé
