### ISSUE TITLE
Supprimer taxon "Carex sequalis"

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1539]
[Originally posted on GoogleCode (id 976) on 2014-03-24]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>
&quot;Carex sequalis&quot;
Saisi par Fannie Matthieu, 2004-05-10

Sur l'étiquette, il est indiqué &quot;Alopecurus aequalis&quot;
la fiche a été corrigée

<b>ID of the specimen(s):</b>
63484

<b>Your name:</b>
Geoff Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-25 12:54Z]

Merci. C'était l'un de ces cas étranges

Luc
