### ISSUE TITLE
Misspelled taxon

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1564]
[Originally posted on GoogleCode (id 1405) on 2014-10-30]

Misspelled scientific name:
Campanula giesekiana
Taxon ID 18849

Correctly spelled scientific name:
Campanula gieseckeana
http://data.canadensys.net/vascan/taxon/9754
http://www.tropicos.org/Name/5500393

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-30 19:35Z]

corrigé

j'aurais sans doute dû utiliser copier-coller
