### ISSUE TITLE
Poa pratensis subsp. alpigena -- autorités en conflit entre MT et Vascan

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1567]
[Originally posted on GoogleCode (id 1415) on 2014-11-03]

ID de taxon 9996
base de données MT (nom scientifique):
Poa pratensis Linnaeus subsp. alpigena (Hudson) Clapham

base de données MT (nom scientifique accepté):
Poa pratensis Linnaeus subsp. alpigena (Fries ex Blytt) Hiitonen

cf.:
http://herbarium.usu.edu/webmanual/
http://www.tropicos.org/Name/25534798
http://data.canadensys.net/vascan/taxon/7894
Poa pratensis Linnaeus subsp. alpigena (Lindman) Hiitonen

cf.:
http://www.theplantlist.org/tpl1.1/record/kew-436921
Poa pratensis Linnaeus subsp. alpigena (Blytt) Hiitonen

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-11-03 19:15Z]

Je ne sais ce qui s'est produit ici. Totalement aberrant. Spaced out. Drunk or drugged.

Luc
