### ISSUE TITLE
Synonymie de Carex tribuloides var. reducta

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1569]
[Originally posted on GoogleCode (id 1438) on 2014-11-06]

Pourquoi le Carex tribuloides var. reducta est-il devenu synonyme de Carex tribuloides var. tribuloides (Vascan, Tropicos, Kew, The sedges of Carex subgenus Vignea (&lt;http://vignea.lifedesks.org/pages/8139&gt;)?

Le Carex tribuloides var. reducta était un synonyme publié de Carex projecta depuis K.K. Mackenzie et les flores du 20e siècle (Fernald, Gleason, Cronquist) jusqu'à peu avant le traitement de FNA (où les synonymes sont absents dans les cas de projecta et de tribuloides).

Parmi 46 spécimens à MT appelés Carex tribuloides var. reducta, 37 ont été révisés à C. projeta, 2 à C. tribuloides var. tribuloides, 2 à C. cristatella, 2 à C. crawfordii, 1 à Carex argyrantha, 1 à C. scoparia et 1 à Carex echinata subsp. echinata.

Hypothèse : le type de Carex tribuloides var. reducta (L.H. Bailey) a été révisé à Carex tribuloides var. tribuloides?

Est-ce que ça vaut la peine de vérifier que la synonymie est exacte?

protologue de Carex projecta (K.K. Mackenzie, 1908) où le Carex tribuloides var. reducta est listé en synonymie
http://www.biodiversitylibrary.org/page/12621488#page/310/mode/1up&gt;

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
Peu importe ce que Mackenzie a fait, il semble que tous soient d'accord pour placer le type de Carex tribuloides var. reducta en synonymie de var. tribuloides et non de C. projecta (FNA n'a pas de synonymie). Même WCSP le place ainsi. Il ait possible que Mack. ait erré, ce qui ne serait pas la première fois.
En ce qui concerne les spécimens, l'interprétation de ceux-ci pourrait aussi avoir été erronée et des spécimens de projecta identifiés à ce taxon. Cela signifie seulement que des outils erronés ont été utilisés.
Je ne remettrai pas ceci en question, à moins qu'on m'amène des arguments quant au type.
Luc
