### ISSUE TITLE
New taxons Carex d'Asie

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1570]
[Originally posted on GoogleCode (id 1442) on 2014-11-07]

Noms de Carex d'Asie recensés avant la saisie

Carex coacta Boott  [Carex &quot;coarcta&quot; Boott selon l'étiquette]
Carex curaica Kunth
Carex desertorum Litvinov
Carex iljinii V.I. Kreczetowicz
Carex pseudocuraica F. Schmidt
Carex pycnostachya Karelin &amp; Kirilov
Carex sajanensis ñ. [?] V.I. Kreczetowicz
Carex similigena V.I. Kreczetowicz
Carex stenophylla Wahlberg var. duriuscula (C.A. Meyer) Trautvetter
Carex stenophylla Wahlberg sen str. ssp. uralensis (C.B. Clarke) ñ.    [? V.I. Kreczetowicz]
Carex stenophylloides V.I. Kreczetowicz

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-11-10 21:28Z]

Carex coacta = C. divisa
Carex curaica acc
Carex desertorum = Carex pachystylis
Carex iljinii acc
Carex pseudocuraica acc
Carex pycnostachya acc
Carex sajanensis acc
Carex similigena = C. enervis
Carex stenophylla var. duriuscula = Carex duriuscula
Carex stenophylloides V.I. Kreczetowicz = Carex stenophylla subsp. stenophylloides

Carex stenophylla ssp. uralensis (C.B. Clarke) [? V.I. Kreczetowicz]: la subsp. uralensis ne peut être trouvée ds les bd
cependant, C. uralensis C.B. Clarke existe et est un syn. de C. stenophylla subsp. stenophylla - je vais donc placer ce nom en syn. du dernier taxon
