### ISSUE TITLE
Mentha canadensis ou Mentha arvensis subsp. borealis?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1576]
[Originally posted on GoogleCode (id 1525) on 2014-12-16]

Selon le suivant, Mentha canadensis est le nom accepté :

Taxon ID = 17692
Mentha arvensis var. borealis = syn.
Mentha canadensis = nom acc.

selon les 2 suivants, Mentha arvensis subsp. borealis est le nom accepté :

Taxon ID = 8533
Mentha canadensis  = syn.
Mentha arvensis subsp. borealis = nom acc.

Taxon ID = 8528
Mentha arvensis var. canadensis = syn.
Mentha arvensis subsp. borealis = nom acc.

Par ailleurs, Frédéric Coursol nous a mentionné qu'il existe un publication pour appuyer Mentha canadensis

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-12-22 15:21Z]

Je sais à propos de ce taxon et je dois modifier VASCAN en conséquence

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-08 19:24Z]

VASCAN était déjà modifié et j'ai ajouté des synonymes additionnels

Mentha arvensis var. borealis = Mentha arvensis subsp. borealis = Mentha arvensis var. canadensis = M. canadensis acc
