### ISSUE TITLE
New taxon Carex Asia

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1581]
[Originally posted on GoogleCode (id 1590) on 2015-01-29]

Carex biwensis
Carex biwensis Franchet

Carex chitralensis
Carex chitralensis Nelmes

Carex condensata
Carex condensata Nees

Carex conglobata
Carex conglobata Kitaibel ex Willdenow

Carex conglobata var. acuta
Carex conglobata Kitaibel ex Willdenow var. acuta (Litvinov) O. Fedtschenko &amp; B. Fedtschenko

Carex corsica
Carex corsica Degland ex Loiseleur-Deslongchamps

Carex diffusa
Carex diffusa Boott ex C.B.Clarke

Carex doisutepensis
Carex doisutepensis T. Koyama

Carex doniana
Carex doniana Sprengel

Carex filiculmis
Carex filiculmis Franchet &amp; Savatier

Carex flavocuspis
Carex flavocuspis Franchet &amp; Savatier

Carex graciliformis
Carex graciliformis V.I. Kreczetowicz

Carex hapalopoda
Carex hapalopoda Nelmes

Carex japonica
Carex japonica Thunberg

Carex nachiana
Carex nachiana Ohwi

Carex nakiri
Carex nakiri Ohwi

Carex nakiri var. nakiri
Carex nakiri Ohwi var. nakiri

Carex nakiri var. sendaica
Carex nakiri Ohwi var. sendaica T. Koyama

Carex nipposinica
Carex nipposinica Ohwi

Carex parciflora
Carex parciflora Boott

Carex parciflora var. macroglossa
Carex parciflora Boott var. macroglossa (Franchet &amp; Savatier) Ohwi

Carex parciflora var. parciflora
Carex parciflora Boott var. parciflora

Carex simulans
Carex simulans C.B. Clarke

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-30 19:06Z]

Carex biwensis = Carex rara subsp. rara
Carex chitralensis = Carex koshewnikowii subsp. chitralensis
Carex condensata acc
Carex conglobata var. acuta = Carex turkestanica
Carex corsica = Carex microcarpa
Carex diffusa = Carex vesiculosa
Carex doisutepensis acc
Carex doniana acc
Carex filiculmis = Carex breviculmis var. breviculmis
Carex flavocuspis acc
Carex graciliformis = Carex acuta
Carex japonica acc
Carex nachiana acc
Carex nakiri = Carex brunnea subsp. brunnea [à valider car probl. de priorité]
Carex nakiri var. nakiri = Carex brunnea subsp. brunnea
Carex nipposinica = Carex brownii subsp. brownii
Carex parciflora = Carex jackiana subsp. parciflora
Carex parciflora var. parciflora = Carex jackiana subsp. parciflora
Carex simulans acc

PROBLÈME:
Carex hapalopoda svp vérifier orthogr - pas ds les bd
Carex nakiri var. sendaica  : ne serait-ce pas plutôt C. sendaica var. nakiri? 
Carex parciflora var. macroglossa  : plutôt Carex parciflora var. macroglossa ?

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2015-01-30 19:42Z]

Objet: PROBLÈME
Sur les spécimens, nous avons vérifié ensemble que l'orthographe et l'ordre des mots sont tels que signalés:

Carex hapalopoda Nelmes
Carex nakiri Ohwi var. sendaica T. Koyama
Carex parciflora Boott var. macroglossa (Franchet & Savatier) Ohwi

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-23 16:52Z]

Carex parciflora Boott var. macroglossa (Franchet & Savatier) Ohwi = Carex jackiana var. macroglossa

Carex nakiri Ohwi var. sendaica T. Koyama: ce nom ne semble pas exister; par contre, il y a : Carex sendaica var. nakiri (Ohwi) T. Koyama qui semble plus vraisemblable
[C. nakiri est un nom. inval.] - je vais donc entrer le nom comme tel, le corriger à sendaica var nakiri, puis donner le nom acc. du dernier 
= Carex brunnea subsp. brunnea

Carex hapalopoda Nelmes : pas ds les bd ms dans herbier MNHN et ds bd flore Vietnam
