### ISSUE TITLE
New taxon Carex Asia_illegible name with attached image of label

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1582]
[Originally posted on GoogleCode (id 1593) on 2015-01-29]

<b>Scientific name:</b>
Carex __avacum Lorado? [Goradu?]
 
<b>ID of the specimen(s):</b>
NA (Russia, 31 July 1932, No. 125)

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-30 14:17Z]

Carex ?oe?arae??

Je ne suis même pas capable de déterminer le nom d'auteur

Il faudrait trouver un spécimen original russe qui aurait été interprété...

Je suggère de publier sans compléter le nom d'espèce - mettre le nom de genre. Quelqu'un saura peut-être
