### ISSUE TITLE
New taxon_Carex d'Asie

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1583]
[Originally posted on GoogleCode (id 1600) on 2015-02-04]

Carex chloroleuca
Carex chloroleuca Meinshausen

Carex amgunensis var. chloroleuca
Carex amgunensis F. Schmidt var. chloroleuca (Meinshausen) Kükenthal

Carex subumbellata var. verecunda
Carex subumbellata Meinshausen var. verecunda Ohwi

Carex nitida var. aspera
Carex nitida Host var. aspera (Boeckeler) Kükenthal

Carex nitida var. aspera f. alpina
Carex nitida Host var. aspera (Boeckeler) Kükenthal f. alpina Kükenthal

Carex schlagintweitiana
Carex schlagintweitiana Boeckeler

Carex jaluensis
Carex jaluensis Komarov

Carex maculata
Carex maculata Boott

Carex maculata f. viridens
Carex maculata Boott f. viridens Kükenthal

Carex praelonga var. angustior
Carex praelonga C.B. Clarke var. angustior C.B. Clarke

Carex phacota var. gracilispica
Carex phacota Sprengel var. gracilispica Kükenthal

Carex cincta
Carex cincta Franchet

Carex pruinosa subsp. maximowiczii
Carex pruinosa Boott subsp. maximowiczii Kükenthal

Carex atrata subsp. pullata
Carex atrata Linnaeus subsp. pullata (Boott) Kükenthal

Carex atrata subsp. pullata var. subglacilenta
Carex atrata Linnaeus subsp. pullata (Boott) Kükenthal var. subglacilenta Kükenthal

Carex atrata subsp. pullata var. glacialis
Carex atrata Linnaeus subsp. pullata (Boott) Kükenthal var. glacialis Boott

Carex spectabilis var. denticulata
Carex spectabilis Dewey var. denticulata (Kükenthal) Ohwi

Carex scita var. korginensis
Carex scita Maximowicz var. korginensis (Meinshausen) Kükenthal

Carex oxyandra var. lanceata
Carex oxyandra (Franchet &amp; Savatier) Kudô var. lanceata (Kükenthal) Ohwi

<b>Your name:</b>
Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 15:04Z]

Carex amgunensis = Carex amgunensis
Carex amgunensis var. chloroleuca = Carex amgunensis
Carex subumbellata var. verecunda  acc
Carex nitida var. aspera = Carex turkestanica
Carex schlagintweitiana = Carex setigera var. schlagintweitiana
Carex jaluensis acc
Carex praelonga var. angustior = Carex teres
Carex phacota var. gracilispica = Carex phacota
Carex cincta = Carex phacota
Carex pruinosa subsp. maximowiczii = Carex maximowiczii
Carex atrata subsp. pullata acc
Carex atrata subsp. pullata var. subglacilenta = Carex atrata subsp. pullata
Carex atrata subsp. pullata var. glacialis = Carex atrata subsp. pullata
Carex scita var. korginensis = koraginensis [vérifier - mal épelé ds TROPICOS] = Carex scita var. riishirensis
 

PROBLÈMES: 
Carex maculata f. viridens : non retrouvé ds les bd ms trouvé avec JSTOR types P00285301 écrit viridans [sic] Lev. [non Kuk.] mais sur spéc.: Kuk. ex Lév.- svp vérifier orthographe et aut., etc.
syn de maculata ds P
je ne vais inscrire le nom qu'après vérification orthographique

Carex spectabilis var. denticulata : pas ds les bd - svp vérifier avant de terminer entrée [entrée débutée] - ttes les vars. sont syn, mais pas du même taxon

Carex oxyandra var. lanceata: pas ds les bd - j'ai débuté entrée, mais imp. de déterminer la syn. - vérif authorités - il existe un C. salina var. lanceata (Dewey) Kük. = C. salina - c'est le seul nom proche que j'ai pu trouver

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2015-02-16 15:39Z]

Noms vérifiés sur l'étiquette, prêts à être ajoutés à la base de données:

(1) faute d'orthographe de ma part, sur l'étiquette dactylographiée :
Carex maculata Boott f. viridans Kükenthal

(1a) à ne pas oublier aussi :
Carex maculata Boott

(2) mon erreur, Carex spectabilis var. denticulata devrait être
Carex tolmiei Boott var. denticulata (Kükenthal) Ohwi

(3) sur l'étiquette dactylographiée :
Carex oxyandra Kudô var. lanceata Ohwi

mais = Carex oxyandra (Franchet & Savatier) Kudô var. lanceata (Kükenthal) Ohwi
selon CONSPECTUS CARICUM JAPONICARUM, p. 127
(p.j. Kiyama1932_ConspectusCaricumJaponicarum_JlFacSciHokkaidoImperialUniv5_2(1)127)
<http://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAA&url=http%3A%2F%2Feprints.lib.hokudai.ac.jp%2Fdspace%2Fbitstream%2F2115%2F26216%2F1%2F2%25281%2529_P1-266.pdf&ei=5wniVOz8JKjasATj9oKgDQ&usg=AFQjCNHial8suZOqE6NbZQxanCORxYJfuA&sig2=1tFTmsrmI2Az_y0zk9nmfw&bvm=bv.85970519,d.cWc>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-23 18:36Z]

Carex tolmiei Boott var. denticulata = Carex flavocuspis

Carex oxyandra (Franchet & Savatier) Kudô var. lanceata (Kükenthal) Ohwi = via basionyme C. wrightii var. lanceata Kük. = Carex oxyandra var. oxyandra

Carex maculata Boott f. viridans Kükenthal : à valider - selon MNHN: f. viridans Lév. [ms aucune citation] = Carex maculata var. maculata [attribution à var. typique à valider]
