### ISSUE TITLE
Province erronée

### ISSUE THREAD

**Issue by FredCoursol** [irbv-collections/MT-controlled-vocabulary#1623]
[Originally posted on GoogleCode (id 907) on 2014-02-14]

Ontario, pas Québec comme province

Scientific name:Carex umbellata

ID of the specimen(s):MT00178780

Your name:Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-14 15:25Z]

Svp, ne pas utiliser Taxon comme étiquette pour données géographiques erronées

Ont. corrigé ds BD
