### ISSUE TITLE
New Taxon Carex d'Asie

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1702]
Carex acicularis Boott
Carex cephalotes F. Muell.
Carex chlorantha R. Br.
Carex tereticaulis F. Muell.
Carex appressa R. Br.
Carex secta Boott (sur étiquette: Carex secta Sol. ex Boott in Hook.f.)
Carex virgata Sol. ex Boott (sur étiquette: Carex virgata Sol. ex Boott in Hook.f.)
Carex resectans Cheeseman
Carex inversa R. Br.
Carex macloviana var. subfusca (W. Boott) Kük.
Carex longibrachiata Boeckeler
Carex pycnothyrsos Kük.
Carex nyasensis C.B. Clarke
Carex filicina Nees var. angustifolia Nelmes
Carex palawanensis Kük.
Carex gaudichaudiana Kunth
Carex ternaria G. Forst.
Carex loheri C.B. Clarke
Carex brunnea var. meyenii (Nees) Kük.
Carex jackiana Boott
Carex montis-eeka Hillebr.
Carex lucida Boott (sur étiquette: Carex lucida Boott in Hook.f.)
Carex dipsacea Berggr.
Carex testacea Sol. ex Boott (sur étiquette: Carex testacea Sol. ex Boott in Hook.f.)
Carex comans Berggr.
Carex exploratorum Nelmes
Carex nealae Krauss [sic; p-ê Carex nealiae R.W. Krauss?]
Carex spicata-paniculata C.B.Cl. [sic]
Carex gembolensis C. B. Clarke var. crebra Nelmes
Carex rubicunda Petrie
Carex tasmanica Kük.
Carex lambertiana Boott (sur étiquette: Carex lambertiana Boott in Hook.f.)
Carex solandri Boott in Hook.f. [sic; p-ê Carex solanderi Boott?]
Carex forsteri Wahl
Carex fascicularis Sol. ex Hook. f. (sur étiquette: Carex fascicularis Sol. ex Boott)
Carex novae-selandiae Boeckeler
Carex trifida Cav.
Carex bichenoviana Boott
Carex alligata Boott
Carex clemensii Kük.
Carex bifida Cav.
Carex confusa (Cheeseman) Hamlin
Carex coriacea Hamlin
Carex dissita Sol. ex Boott (sur étiquette: in Hook.f.)
Carex geminata Schkuhr
Carex gunniana Boott
Carex hebes Nelmes
Carex iynx Nelmes
Carex blakei Nelmes
Carex meyenii Nees
Carex pluvia var. koolauensis R.W. Krauss
Carex raoulii Boott (sur étiquette: in Hook.f.)
Carex sinclairii Boott ex Cheeseman (sur étiquette: Carex sinclairii C.B.Clarke in Cheesem.)
Carex tahoata Hamlin
Carex wahuensis var. meyeri Franch. & Sav.
Carex wahuensis var. rubiginosa R.W. Krauss
Carex wahuensis C.A. Mey.
Carex wahuensis var. lavarum Kükenthal

Sarah Dupont, 8 juin 2015

**Comment by brouille** [comment]
Carex acicularis acc
Carex cephalotes = Carex pyrenaica var. cephalotes [ms valider car contradiction entre sources]
Carex chlorantha acc
Carex tereticaulis acc
Carex appressa acc
Carex secta Boott acc
Carex virgata acc [ms valider car contradiction entre sources]
Carex resectans acc
Carex inversa acc
Carex macloviana var. subfusca =  Carex macloviana subsp. subfusca
Carex longibrachiata = [orth. var.] = Carex longebrachiata acc
Carex pycnothyrsos = Carex rafflesiana
Carex nyasensis = Carex echinochloe subsp. nyasensis

**Comment by brouille** [comment]
Carex filicina var. angustifolia = Carex filicina [non retrouvé ds bd - assigné à sp]
Carex palawanensis acc
Carex gaudichaudiana acc
Carex ternaria acc
Carex loheri acc
Carex brunnea var. meyenii = Carex meyenii
Carex jackiana acc
Carex montis-eeka acc
Carex lucida = Carex flagellifera
Carex dipsacea acc
Carex testacea acc
Carex comans acc
Carex exploratorum = Carex graeffeana acc
Carex nealae ou nealiae = nealiae = Carex appendiculata var. appendiculata acc
Carex spicata-paniculata = Carex spicatopaniculata acc
Carex gembolensis var. crebra = Carex vesiculosa

**Comment by brouille** [comment]
Carex rubicunda acc
Carex tasmanica acc
Carex lambertiana acc
Carex solandri [ms TRO a solanderi vs WCSP, IPNI, NZ] acc
Carex forsteri acc
Carex fascicularis acc [Sol. ex Hook. f.  vs ex Boott : voir bd pr commentaire - à valider]
Carex novae-selandiae = Carex fascicularis
Carex trifida acc
Carex bichenoviana acc
Carex alligata acc
Carex clemensii = Carex perakensis var. borneensis
Carex confusa = Carex ternaria
Carex coriacea acc
Carex dissita acc
Carex geminata acc
Carex gunniana acc
Carex hebes acc
Carex iynx acc
Carex blakei acc
Carex meyenii acc
Carex pluvia var. koolauensis = Carex alligata
Carex raoulii acc
Carex sinclairii acc
Carex tahoata = Carex dipsacea
Carex wahuensis acc
Carex wahuensis var. meyeri = Carex wahuensis subsp. wahuensis
Carex wahuensis var. rubiginosa = Carex wahuensis subsp. rubiginosa
Carex wahuensis var. lavarum unknown

Problème : Carex bifida Cav. : est-ce bien Cav. comme auteur ? N'existe pas ds bd [note trifida Cav. ] svp vérifier

**Comment by brouille** [comment]
le spécimen est Carex trifida Cav., déjà ds bd
