### ISSUE TITLE
New Taxon Carex d'Asie

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1703]
195892, 195893: 2e détermination: Carex angustinowiczii Meinsh.
195894, 199589: 1 ière détermination: Carex angustinowiczii Meinsh.
195895, 195891: 1 ière détermination: Carex angustinowiczii Meinshausen
199590: 3e détermination: C. angustinowiczii var. sharensis ( Franch.) Ohwi
196384: 2e détermination: Carex angustinowiczii Meinshausen ex Korshinsky var. sharensis (Franchet) Ohwi

Claude Lucier, 4 juin 2015

**Comment by brouille** [comment]
Carex angustinowiczii = Carex augustinowiczii acc
Carex angustinowiczii var. sharensis déja ds bd (avec orthogr. correct) acc
