### ISSUE TITLE
New Taxon Carex praecox Jacq. var. vivaldii

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1724]
196058: 1 ière détermination: Carex praecox Jacq. var. vivaldii (sans autorité pour la variété)

Claude Lucier  15 juin 2015

**Comment by brouille** [comment]
Carex praecox Jacq. var. vivaldii = var. vidalii [orthogr. erroné] = Carex caryophyllea var. caryophyllea
