### ISSUE TITLE
Parc; county

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#1738]
New Mexico : comtés incomplets
175235
Sandoval County
https://en.wikipedia.org/wiki/Sandoval_County,_New_Mexico

Santa Fe National Forest
https://en.wikipedia.org/wiki/Santa_Fe_National_Forest

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
