### ISSUE TITLE
New Taxon Phyllanthus de Cuba

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1803]
113804: 2e détermination: Phyllanthus scopulorum (Britt.) Alain (photo liée à la fiche 201634)
113767: 2e détermination: Phyllanthus pruinosus Poepp. (photo liée à la fiche 201703)
113772: 1 ière détermination: Roigia comosa Britton (photo liée à la fiche 201700)
113776: 2e détermination: Phyllanthus discolor Poepp. ex Spr. var. discolor (photo liée à la fiche 201698)
113775: 2e détermination: Phyllanthus discolor Poepp. ex Spr. var. discolor (photo liée à la fiche 201696)
113774: 2e détermination: Phyllanthus discolor Poepp. ex Spr. var. discolor (photo liée à la fiche 201695)

Claude Lucier, 15 juillet 2015

**Comment by brouille** [comment]
Phyllanthus scopulorum (Britt.) Alain  = Phyllanthus scopulorum (Britton) Urban
Phyllanthus pruinosus = Phyllanthus discolor
Roigia comosa = Phyllanthus comosus
Phyllanthus discolor Poepp. ex Spr. var. discolor = Phyllanthus discolor [les var. ne semblent pas retenues]
