### ISSUE TITLE
New Taxon Phyllantus Cuba

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1804]
113788: 1 ière détermination: Phyllanthus minimus Wr. (photo liée à la fiche 201691)
113791, 201689, 201688, 201687: 1 ière détermination: Ramsdenia moaensis (sans autorité) (photo liée respectivement  à la fiche 201690, 201689, 201688, 201687)
113790, 201685, 201682, 201683, 201684, 201681: 1 ière détermination: Ramsdenia moaensis n. sp. (sans autorité  (photo liée respectivement à la fiche 201686, 201685, 201682, 201683, 201684, 201681)
201680: 1 ière détermination: Phyllanthus juglandifolius Willd.
113780: 2e détermination: Phyllanthus juglandifolius Willd.
113808: 2e détermination: Phyllanthus foveolatus (Britt.) Alain
113803: 1 ière détermination: Phyllanthus aff. nummulariaefolius Poir.

Claude Lucier, 17 juillet 20145

**Comment by brouille** [comment]
Phyllanthus minimus = Phyllanthus echinospermus
Ramsdenia moaensis pas ds bd = Phyllanthus sp.
Phyllanthus juglandifolius acc
Phyllanthus foveolatus = Phyllanthus myrtilloides subsp. erythrinus
Phyllanthus nummulariaefolius acc [ms Madagascar]
