### ISSUE TITLE
New Taxon carex transférés

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1806]
Schoenoxiphium caricoides C.B.Cl.  (S. Kunthianum KüK.).... Afrique

Schoenoxiphium rufum Nees.....Afrique

Schoenoxiphium Sparteum (Wahl.)  Kük.....Afrique

Schoenoxiphium kunthianum Kük...Afrique

Elyna bellardi (All.) .....Groenland..NUN.....U.S.A.

Kobresia scirpina Willd....Groenland

Kobresia bellardii var. macrocarpa ....U.S.A

Kobresia hyperborea A.E. Porsild...NUN....T.N.O.

 Kobresia arctica A.E. Porsild.....T.N.O.

 Kobresia sp....NUN.

 Elyna myosuroides (Vill.) Fritsch ...Europe

 Kobresia caricina Willd....Europe

 Kobresia bipartita (All.) Dalla Torre ...Europe

 Elyna spicata Schrad.... Europe

 Trilepis lhotzkiana Nees Amérique du sud

 Kobresia capillifolia ....Europe

Diane Fournier

**Comment by brouille** [comment]
Schoenoxiphium caricoides = Carex spartea
Schoenoxiphium rufum = Carex ludwigii
Schoenoxiphium Sparteum = Carex spartea
Schoenoxiphium kunthianum = Carex spartea
Elyna bellardi = Carex myosuroides
Kobresia scirpina = Carex myosuroides
Kobresia bellardii var. macrocarpa = Carex borealipolaris
Kobresia hyperborea = Carex borealipolaris
Kobresia arctica = Carex borealipolaris
Kobresia = Carex
Elyna myosuroides = Carex myosuroides
Kobresia caricina = Carex simpliciuscula
Kobresia bipartita = Carex simpliciuscula
Elyna spicata Schrad. = Carex myosuroides
Kobresia capillifolia = Carex capillifolia
Trilepis lhotzkiana = Carex lhotzkiana
