### ISSUE TITLE
New Taxon carex transférés et famille des  athyriaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1811]
Pour Kobresia capillifolia on a comme nom revisé  "Carex capillifolia" cependant ce nom n'est pas présent dans la banque de données

Il y a une série de 7 textes portant sur les plantes sivantes: 
" Cobresia bonatiana Kükenthal, spec. nova. texte dans Asie

Kobresia brunnescens Böcklr. texte dans Asie

Kobresia clarkeana Kükenthal var.megalantha Kükenthal, var. nova. texte dans Asie

Kobresia elata Böcklr. texte dans Asie

Kobresia hyalinolepis Böcklr. texte dans Asie

Kobresia macrantha Böcklr. texte dans Asie

Cobresia siamensis Ohwi, sp.nv. texte dans Asie "

Cobresia capillifolia (Decne.) C.B.Clarke var. filifolia  (Turczan.) Kükenthal...Asie

 Kobresia capilliformis....Asie

 Cobresia pamiro-alaica Iv....Asie

Kobresia royleana (Nees) Boeck....Asie

Elyna schoenoides C.A.Mey.....Asie

Kobresia schoenoides, Boeck. B. Clarke..Asie

Kobresia tibetica Maxim. M.R....Asie

Kobresia uncinioides (Boott) C.B.Clarke ...Asie

Uncinia brevicaulis Thou. var. macloviana Kuek.....Amérique du sud

Uncinia erinacea (Cav.) Pers...... Amérique du sud

Uncinia macrophylla Steud......Amérique du sud

Uncinia uncinata (L.f.) Kukenth....Amérique du sud

Uncinia hamata (Sw.) Urban.... Amérique du Sud

Uncinia riparia R. Br....Océanie

Uncinia riparia R. Br. var. affinis C.B. Clarke....Océanie

 Uncinia pedicellata Kükenthal...Oceanie

 Uncinia longifructus ( Kükenthal) Petrie...Oceanie

 Uncinia lindleyana Kunth ...Océanie

 Uncinia leptostachya Raoul .....Océanie

 Uncinia fuscovaginata Kükenthal...Océanie

 Uncinia flaccida S.T.Blake....Océanie

 Uncinia filiformis Boott in Hook. f...Océanie

 Uncinia ferruginea Boott in Hook. f....Océanie

 Uncinia divaricata.....Océanie

Uncinia compacta R.Br.....Océanie

Uncinia caespitosa Boott in Hook f.....Océanie

Uncinia caespitosa Boott in Hook f. var. minor Kükenthal...Océanie

Uncinia australis Pers. (Uncinia uncinata (L.f.) Kükenthal) .....Océanie  (les deux annotations se retrouvent sur l'étiquette)

Uncinia....Océanie

Uncinia rubra Boott in Hook.f....Océannie

Uncinia tenella R. Br.  ...Océanie

Fin des annotations pour les carex tranférés
.....................................................................................................................................................................

Physematium manchuriense Nakai ...Asie

Woodsia cathcartiana...U.S.
....................................................................................................................................................................

"famille des athyriaceae"

Athyrium distentifolium....  Colombie-Britannique

Athyrium americanum (Butters) Maxon....USA

 Phegopteris alpestris Mett....USA

Athyrium asplenioides (Michx.) Eaton.....USA

Athyrium (Asplenium) cyclosorum orientale ...USA

Athyrium asplenioides (Michx.) Desv. f. typicum...USA

**Comment by herbier** [comment]
envoyé par Diane Fournier

**Comment by brouille** [comment]
Cyperaceae faites ms commentaire perdu

Physematium manchuriense = manchuriensis = Woodsia manchuriensis
Woodsia cathcartiana = Woodsia oregana subsp. cathcartiana
Athyrium distentifolium acc
Athyrium americanum = Athyrium distentifolium var. americanum
Phegopteris alpestris = Athyrium distentifolium [pr Amérique]
Athyrium asplenioides = Athyrium filix-femina var. asplenioides
Athyrium asplenioides f. typicum = Athyrium filix-femina var. asplenioides
Athyrium (Asplenium) cyclosorum orientale : il n'y a pas de var. ou f. orientale sous cyclosorum ; A. cyclosorum = Athyrium filix-femina var. cyclosorum
