### ISSUE TITLE
New Taxon Festuca

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1829]
202425: 1ière et 2e détermination: Festuca saximontana var. purpursiana (Saint-Yves) Frederiksen & Paulick
202436: 3e détermination: Festuca ovina L. var. saximontana

Claude Lucier, 21 août 2015

**Comment by brouille** [comment]
Festuca saximontana var. purpusiana acc
Festuca ovina L. var. saximontana = Festuca saximontana
