### ISSUE TITLE
New Taxa from Oregon

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1835]
202961
Vicia gigantea Hook.

202962
Thysanocarpus curvipes Hook.

202963
Lomatium Nudicaule (Pursh) Coult. & Rose

202965
Aster hallii A. Gray

202966
Danthonia californica Bol.

202968
Ericameria nauseosa (Pall. ex Pursh) G.L. Nesom & G.I. Baird

202969
Lupinus latifolius Lindl. ex J. Agardh var. subalpinus (Piper & B.L. Rob.) C.P. Sm.

202970
Amelanchier alnifolia (Nutt.) Nutt. ex Roem. var. semiintegrifolia (Hook.) C.L. Hitchc.

202973
Trifolium eriocephalum Nutt. var. eriocephalum

202977
Salix sessilifolia Nutt. 

202978
Sidalcea oregana (Nutt.) A. Gray var. procera C.L. Hitchc.

202979
Penstemon davidsonii Greene var. davidsonii

202980
Micropus californicus Fisch. & C.A. Mey. var. californicus

202981
Phacelia capitata Kruckeb.

202982
Trifolium vesiculosum Savi

202984
Acacia dealbata Link

202985
Crataegus monogyna Jacq. x Crataegus suksdorfii (Sarg.) Kruschke (Natural hybrid common where the 2 parents are sympatric.)

202989
Luzula hitchcockii Hämet-Ahti

202990
Eremogone pumicola (Coville & Leiberg) Ikonn.

202991
Hackelia californica (A. Gray) I.M. Johnst.

202993
Nothochelone nemorosa (Douglas ex Lindl.) Straw

202994
Carex amplifolia Boott

202995
Phyllodoce empetriformis (Sm.) D. Don

202996
Eucephalus ledophyllus (A. Gray) Greene var. covillei (Greene) G.L. Nesom

202997
Phacelia heterophylla Pursh ssp. Virgata (Greene) Heckard

203000
Raphanus raphanistrum L. x Raphanus sativus L.

Geoff (for Christiane Nepveu)

**Comment by brouille** [comment]
202974 nom acc différent : Sanguisorba minor = Poterium sanguisorba var. polygamum 

Vicia gigantea = Vicia nigricans var. gigantea
Thysanocarpus curvipes acc
Lomatium nudicaule acc
Aster hallii = Symphyotrichum hallii
Danthonia californica acc
Ericameria nauseosa acc
Lupinus latifolius var. subalpinus acc
Amelanchier alnifolia var. semiintegrifolia acc
Trifolium eriocephalum var. eriocephalum acc
Salix sessilifolia acc
Sidalcea oregana var. procera = Sidalcea oregana subsp. oregana
Penstemon davidsonii var. davidsonii acc
Micropus californicus var. californicus acc
Phacelia capitata acc
Trifolium vesiculosum acc
Acacia dealbata acc
Crataegus monogyna x Crataegus suksdorfii = Crataegus monogyna var. monogyna × Crataegus gaylussacia
Luzula hitchcockii acc
Eremogone pumicola acc
Hackelia californica acc
Nothochelone nemorosa acc
Carex amplifolia acc
Phyllodoce empetriformis acc
Eucephalus ledophyllus var. covillei acc
Phacelia heterophylla subsp. virgata = Phacelia heterophylla var. virgata
Raphanus raphanistrum × Raphanus sativus
