### ISSUE TITLE
New Taxon Orobanche

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1844]
202900: 1 ière détermination: Orobanche fasciculata Nutt., var. typica
202919: 1 ière détermination: Orobanche uniflora L. var. terrae-novae (Fern.) Munz
202940: 1 ière détermination: Orobanche uniflora var. purpurea (Heller) Achey 

Claude Lucier,  9 septembre 2015

**Comment by brouille** [comment]
Orobanche fasciculata Nutt., var. typica - nom. inval. = Orobanche fasciculata
Orobanche uniflora L. var. terrae-novae (Fern.) Munz : autorité (Fern.) Achey [je ne sais d'où Munz proviendrait] = Orobanche uniflora
Orobanche uniflora var. purpurea = Orobanche uniflora
