### ISSUE TITLE
New Taxon (Madagascar)

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1845]
203381
Aeranthes

203332
Aeranthes adenopoda

203354
Aeranthes parvula

203390, 203393
Aeranthes setiformis

203330, 203342, 203352, 203377, 203378, 203383, 203414, 203415, 203417, 203404, 203407, 203408, 203409, 203410, 203411
Angraecum

203371, 203374, 203395, 203405
Angraecum arachnites

203336, 203337
Anagraecum baronii

203341, 203347
Angraecum bicallosum

203338, 203366
Anagraecum caricifolium

203388, 203399, 203403
Angraecum clareae

203367
Angraecum compactum

203324, 203339, 203345, 203359, 203360, 203373, 203382, 203387, 203416
Angraecum cordemoyi

203323, 203370
Angraecum didieri

203353, 203355, 203361, 203402
Angraecum filicornu

203375
Angraecum germinyanum

203356
Aeranthes leandriana

203334
Angraecum letouzeyi

203327
Angraecum nanum

203418
Angraecum oblongifolium

203412
Angraecum pauciramosum

203326
Angraecum perparvulum

203384
Angraecum pseudodidieri

203333, 203340, 203364
Angraecum pseudofilicornu

203331, 203344, 203372, 203406
Angraecum pterophyllum

203413
Angraecum rostratum

203343, 203396
Angraecum sedifolium

203346, 203358, 203363, 203379
Angraecum setipes

203319, 203321, 203400
Angraecum sororium

203398
Angraecum sterophyllum

203328
Angraecum tenellum

203325
Angraecum waterlotii

203322, 203349, 203350, 203351, 203369
Beclardia macrostachya

203365
Jumellea

203380
Jumellea brachycentra

203357, 203389, 203394
Jumellea gracilipes

203335, 203362
Jumellea gracillipes

203329
Jumellea maxilarioides

203376
Jumellea peyrotii

203320
Jumellea rigida

203391
Jumellea spathulata

203368, 203392
Jumellea teretifolia

203386
Microcoelia gilpinae

203401
Neobathia

203397
Neobathiea grandidieriana

203348
Neobathiea keraudrenae

203385
Oeonia rosea

Geoff pour Tahiana

**Comment by brouille** [comment]
Aeranthes acc [nous allons tenter de l'identifier à partir de la photo plus tard]
Aeranthes adenopoda acc
Aeranthes parvula acc
Aeranthes setiformis acc
Aeranthes leandriana acc

Angraecum acc
Angraecum arachnites acc
Angraecum baronii acc
Angraecum bicallosum acc
Anagraecum caricifolium acc
Angraecum clareae acc
Angraecum compactum acc
Angraecum cordemoyi acc
Angraecum didieri acc
Angraecum filicornu acc
Angraecum germinyanum acc
Angraecum letouzeyi acc
Angraecum nanum acc
Angraecum oblongifolium acc
Angraecum pauciramosum acc
Angraecum perparvulum acc
Angraecum pseudodidieri acc

**Comment by brouille** [comment]
Angraecum pseudofilicornu acc
Angraecum pterophyllum acc
Angraecum rostratum acc
Angraecum sedifolium acc
Angraecum sororium ACC
Angraecum sterrophyllum acc
Angraecum tenellum acc
Angraecum waterlotii acc

Jumellea acc
Jumellea brachycentra acc
Jumellea gracilipes acc
Jumellea maxillarioides acc
Jumellea peyrotii acc
Jumellea rigida acc
Jumellea spathulata acc
Jumellea teretifolia acc

Microcoelia gilpinae acc

Neobathiea acc
Neobathiea grandidieriana acc
Neobathiea keraudrenae acc

Oeonia rosea acc
