### ISSUE TITLE
Lac Gémont

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#1848]
Geoff: il semble y avoir ambiguité quant à la localisation du lac Gémont dans Les Pays-d'en-Haut
Wentworth-Nord ou Saint-Adolphe-D'Howard?

Il faut tout harmoniser

Merci
Luc

**Comment by geoffreyhall** [comment]
Saint-Adolphe-d'Howard est le bon choix et j'ai mis à jour toutes les fiches
Geoff
