### ISSUE TITLE
Linaria dalmatica—Vascan et bD MT en conflit

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1865]
Selon la base de données MT-Ilex (ID de taxon 7893):
Linaria genistifolia subsp. dalmatica est le nom accepté pour le synonyme Linaria dalmatica

Selon Vascan:
(1) Linaria dalmatica subsp. dalmatica est le nom accepté pour le synonyme Linaria genistifolia subsp. dalmatica
http://data.canadensys.net/vascan/taxon/24822?lang=fr

(2) en Ontario il y a le Linaria dalmatica subsp. macedonica
http://data.canadensys.net/vascan/taxon/27911?lang=fr

(3) Linaria genistifolia subsp. genistifolia est exclu de Terre-Neuve
http://data.canadensys.net/vascan/taxon/7247?lang=fr

Geoff

**Comment by brouille** [comment]
Les synonimies prédatent FNA et je n'avais pas tout révisé

selon le traitement FNA (draft):
Linaria dalmatica acc [la bd MT Taxon est maintenant corrigée]
Linaria dalmatica subsp. dalmatica acc
Linaria genistifolia subsp. dalmatica = Linaria dalmatica subsp. dalmatica
Linaria dalmatica subsp. macedonica acc

Linaria genistifolia subsp. genistifolia est acc, mais non présent en AN et le taxon est exclu

**Comment by geoffreyhall** [comment]
Le problème théorique est réglé mais le nom accepté doit être ajouté à la table Taxon pour pouvoir annoter un spécimen

198522  dét. 2
Linaria dalmatica (Linnaeus) Miller subsp. dalmatica

Geoff

**Comment by brouille** [comment]
Linaria dalmatica subsp. dalmatica AJOUTÉ 22375
entrée ds bd faite
