### ISSUE TITLE
New Taxon Asclepias

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1869]
199722  (det. 1)
199723  (det. 1)
Asclepias syriaca f. inermis Churchill

---

199717  (det. 1)
199718  (det. 1)
199719  (det. 1)
199720  (det. 1)
199721  (det. 1)
Asclepias syriaca L. var. kansana (Vail) E.J. Palmer & Steyerm.

Geoff

**Comment by brouille** [comment]
Asclepias syriaca f. inermis = Asclepias syriaca
Asclepias syriaca var. kansana = Asclepias syriaca
