### ISSUE TITLE
"Potentilla tridentata" est encore le nom accepté pour la forme hirsutifolia?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1870]
ID de taxon 10612
Nom scientifique :  Potentilla tridentata f. hirsutifolia
Nom scientifique accepté :  Potentilla tridentata

Vascan
http://data.canadensys.net/vascan/taxon/20656?lang=fr
Nom scientifique :  Potentilla tridentata
Nom scientifique accepté :  Sibbaldia tridentata
http://data.canadensys.net/vascan/taxon/8961?lang=fr

Geoff

**Comment by brouille** [comment]
Sibbaldia tridentata acc
corrigé
