### ISSUE TITLE
Epilobium ciliatum subsp. ciliatum var. ciliatum :  var. acceptée?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1871]
ID de taxon 17322
Nom scientifique : Epilobium ciliatum subsp. ciliatum var. ciliatum
Nom scientifique accepté : Epilobium ciliatum subsp. ciliatum

Vascan
http://data.canadensys.net/vascan/taxon/6762?lang=fr
Nom scientifique : Epilobium ciliatum subsp. ciliatum var. ciliatum
Nom scientifique accepté : Epilobium ciliatum subsp. ciliatum var. ciliatum

NB :  Epilobium ciliatum subsp. ciliatum var. ecomosum est reconnu partout (Vascan, MT-Ilex)
ID de taxon 17739
Nom scientifique : Epilobium ciliatum subsp. ciliatum var. ecomosum
Nom scientifique accepté : Epilobium ciliatum subsp. ciliatum var. ecomosum

http://data.canadensys.net/vascan/taxon/6764?lang=fr
Nom scientifique : Epilobium ciliatum subsp. ciliatum var. ecomosum
Nom scientifique accepté : Epilobium ciliatum subsp. ciliatum var. ecomosum

Geoff

**Comment by brouille** [comment]
corrigé ajout de var. ciliatum
