### ISSUE TITLE
Achillea borealis (Vascan) ou lanulosa (MT) ou millefolium subsp. lanulosa (MT)?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1873]
VASCAN
nom acc. = Achillea borealis var. borealis
http://data.canadensys.net/vascan/taxon/29175?lang=fr

syn. = Achillea lanulosa subsp. lanulosa
http://data.canadensys.net/vascan/taxon/27264?lang=fr

syn. = Achillea lanulosa var. lanulosa
http://data.canadensys.net/vascan/taxon/10241?lang=fr

syn. = Achillea millefolium subsp. lanulosa
http://data.canadensys.net/vascan/taxon/27266?lang=fr

syn. = Achillea millefolium var. lanulosa
http://data.canadensys.net/vascan/taxon/2765?lang=fr

---

Base de données MT-Ilex
nom acc. = Achillea lanulosa
ID de taxon = 69

syn. = Achillea millefolium var. lanulosa
ID de taxon = 76

syn. = Achillea nigrescens
ID de taxon = 79

---

Base de données MT-Ilex
nom acc. = Achillea lanulosa var. lanulosa
ID de taxon = 19254

---

Base de données MT-Ilex
nom acc. = Achillea millefolium subsp. lanulosa
ID de taxon = 73

---

Base de données MT-Ilex
nom acc. = Achillea millefolium subsp. lanulosa var. lanulosa
ID de taxon = 14914

syn. = Achillea borealis
ID de taxon = 68

Geoff

**Comment by brouille** [comment]
tout est corrigé et harmonisé avec Achillea borealis ou var. borealis
