### ISSUE TITLE
Agalinis purpurea (Vascan) ou paupercula (MT); A. tenuifolia sans var. (Vascan+MT) ou 2 vars. (MT)?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1874]
VASCAN
nom acc. = Agalinis purpurea var. parviflora
http://data.canadensys.net/vascan/taxon/17748?lang=fr

syn. = Agalinis paupercula
http://data.canadensys.net/vascan/taxon/6960?lang=fr

syn. = Agalinis paupercula var. borealis
http://data.canadensys.net/vascan/taxon/6959?lang=fr

syn. = Agalinis paupercula var. paupercula
http://data.canadensys.net/vascan/taxon/6961?lang=fr

---

nom acc. = Agalinis purpurea var. purpurea
http://data.canadensys.net/vascan/taxon/27502?lang=fr

syn. = Agalinis purpurea var. carteri
http://data.canadensys.net/vascan/taxon/27503?lang=fr

syn. = Agalinis virgata
http://data.canadensys.net/vascan/taxon/27504?lang=fr

---

Base de données MT-Ilex
nom acc. = Agalinis paupercula
ID de taxon = 174

---

Base de données MT-Ilex
nom acc. = Agalinis purpurea
ID de taxon = 175

---

Base de données MT-Ilex
nom acc. = Agalinis paupercula var. borealis
ID de taxon = 176 [réf. Agalinis purpurea var. parviflora]
ID de taxon = 6286 [réf. Gerardia paupercula var. borealis]

syn. = Agalinis purpurea var. parviflora
ID de taxon = 176

---

Base de données MT-Ilex
nom acc. = Agalinis paupercula var. paupercula
ID de taxon = 6285 [réf. Gerardia paupercula]

---

---

VASCAN
nom acc. = Agalinis tenuifolia
http://data.canadensys.net/vascan/taxon/6965?lang=fr

syn. = Agalinis tenuifolia var. tenuifolia
http://data.canadensys.net/vascan/taxon/6967?lang=fr

syn. = Agalinis tenuifolia var. parviflora
http://data.canadensys.net/vascan/taxon/6966?lang=fr

---

Base de données MT-Ilex
nom acc. = Agalinis tenuifolia var. parviflora
ID de taxon = 6288 [réf. Gerardia purpurea var. parviflora]

---

Base de données MT-Ilex
nom acc. = Agalinis tenuifolia var. tenuifolia
ID de taxon = 6283  [réf. Gerardia besseyana]

---

Base de données MT-Ilex
nom acc. = Agalinis tenuifolia
ID de taxon = 177

syn. = Agalinis tenuifolia var. tenuifolia
ID de taxon = 19147

syn. = Agalinis tenuifolia var. parviflora
ID de taxon = 179

Geoff

**Comment by brouille** [comment]
Geoff

Les noms dans Taxon prédatent le manuscrit FNA (draft). VASCAN est correct.

Agalinis purpurea acc
Agalinis purpurea var. parviflora acc
Agalinis paupercula = Agalinis purpurea var. parviflora
Agalinis paupercula var. borealis = Agalinis purpurea var. parviflora
Gerardia paupercula var. borealis = Agalinis purpurea var. parviflora
Gerardia paupercula = Agalinis purpurea var. parviflora
Agalinis paupercula var. paupercula = Agalinis purpurea var. parviflora
Gerardia purpurea var. parviflora = Agalinis purpurea var. parviflora [corrigé ds Taxon]

Agalinis tenuifolia acc
Gerardia besseyana = Agalinis tenuifolia
Agalinis tenuifolia var. tenuifolia = Agalinis tenuifolia
Agalinis tenuifolia var. parviflora = Agalinis tenuifolia
