### ISSUE TITLE
Solidago sempervirens var. sempervirents :  var. n'est plus reconnue?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1878]
Désaccord entre Vascan et MT

MT Ilex:
ID de taxon 12479, 12480
Solidago sempervirens var. sempervirens = nom acc.

Vascan:
http://data.canadensys.net/vascan/taxon/3486?lang=fr
Solidago sempervirens = nom acc.

http://data.canadensys.net/vascan/taxon/3485?lang=fr
Solidago sempervirens var. sempervirens = synonyme

Geoff

**Comment by brouille** [comment]
Solidago sempervirens acc
