### ISSUE TITLE
attention quand on corrige

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#1880]
Geoff

Est-ce toi qui a changé la graphie de Saint-Adolphe-D'Howard en Saint-Adolphe-d'Howard ?
J'avais soigneusement corrigé toutes les fiches pour le premier nom. J'ai dû le refaire.

En effet, de façon inusitée, la graphie officielle de ce village prend le D majuscule (site officiel de la ville, wiki, etc.). À moins que tu me dises que le répertoire géo du Québec l'écrit avec une minuscule, j'aimerais qu'on ne change pas tout à nouveau svp

Juste pour information.
Luc

**Comment by geoffreyhall** [comment]
http://www.toponymie.gouv.qc.ca/ct/toposweb/fiche.aspx?no_seq=179139
Saint-Adolphe-d'Howard
Merci, Geoff
