### ISSUE TITLE
New Taxon (bryophytes Stéphanie)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1884]
Amblystegium varium 
Brachythecium erythrorhizon
Brachythecium luteum
Brachythecium rotaeanum
Callicladium haldanianum
Cephalozia bergerii
Dicranum bonjeani
Hypnum linbergii
Rhytiadelphus triquetrus
Scorpidium revolvens 

Salomé Pasquet

**Comment by brouille** [comment]
NB: il faut enlever TOUS les espaces après les noms quand on cherche dans Taxon, autrement, on peut manquer des noms déjà inclus
et faire attention aux fautes d'orthographe des déterminateurs originaux...

les suivants sont déjà ds la bd:
Amblystegium varium [inclus 470]= Hygroamblystegium varium
Brachythecium erythrorhizon = erythrorRhizon [inclus 2011] acc
Brachythecium rotaeanum acc
Callicladium haldanianum [inclus 2315] acc
Dicranum bonjeani = Dicranum bonjeanii [2 i] acc [inclus 4572]
Hypnum linbergii = linDbergii = acc [inclus 7136]
Rhytiadelphus triquetrus = Rhytidiadelphus triquetrus acc [inclus 11203]
Scorpidium revolvens acc [inclus 21205]

Questions:
Brachythecium luteum : est-ce Brachythecium laetum plutôt ? [Taxon 2023 acc]

Cephalozia bergerii ou bergeri n'existe pas ms loitlesbergeri existe - svp vérifier - quel est l'auteur cité par le récolteur?

**Comment by brouille** [comment]
Brachythecium luteum était Brachythecium laetum
Cephalozia bergerii était loitlesbergeri
