### ISSUE TITLE
Solidago puberula subsp. puberula

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1886]
Vascan
Solidago puberula = nom accepté
http://data.canadensys.net/vascan/taxon/3474

Solidago puberula subsp. puberula = synonyme
http://data.canadensys.net/vascan/taxon/3473

base de données MT
Solidago puberula subsp. puberula = nom accepté
ID de taxon 15261

**Comment by brouille** [comment]
Il y a eu un changement entre FNA 2006 et uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-puberula 
Solidago puberula subsp. puberula = Solidago puberula
