### ISSUE TITLE
New Person or combination Aeschynomene

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1888]
203750: récolteur et déterminateur: R. Dale Thomas, Kirk Cormier, et al.
203752, 203753: récolteur: William B. Fox
203752, 203753: déterminateur: Velva E. Rudd
203754, 203755: récolteur et détermination: herbier du Fr. Rolland-Germain ec.
203757: récolteur et déterminateur: Velva E. Rudd
203773: récolteur et déterminateur: voir photo (Illisible)
203777, 203780: récolteur et 1 ière détermination: sans nom

Claude Lucier, 16 octobre 2015

**Comment by geoffreyhall** [comment]
Noms ajoutés et fiches mises à jour
