### ISSUE TITLE
New Taxon Aeschynomene

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1889]
203748: 1 ière détermination: Aeschynomene hispida Willd
203749: 1 ière détermination: Aeschynomene indica (sans autorité) 
203750, 203751, 203752, 203753: 1 ière détermination: Aeschynomene indica L.203754, 203756, 203757, 203758, 203781: 1 ière détermination: Aeschynomene virginica (L.) B.S.P.
203755: 1 ière détermination: Aeschynomene virginica L.
203761: 1 ière détermination: Secula viscidula (sans autorité)
203771: 1 ière détermination: Aeschynomene nivea Brandegee
203775: 1 ière détermination: Aeschynomene biflora (Mill.) Faw & Rendle
203776: 1 ière détermination: Aeschynomene Brasiliana DC.
203777: 2e détermination: Aeschynomene fascicularis DC
        1 ière détermination: Aeschynomene
203778: 1 ière détermination: Aeschynomene montevidensis Vog 
203779: 1 ière détermination: Aeschynomene rudis Benth.
203780: 1 ière détermination: Aeschynomene sensitive L.

Claude Lucier 16 octobre 2015

**Comment by herbier** [comment]
203754, 203756, 203757, 203758, 203781: 1 ière détermination: Aeschynomene virginica (L.) B.S.P.
 # de spécimen allant avec le nom (pas clair dans le courriel)

**Comment by brouille** [comment]
Aeschynomene hispida = Aeschynomene virginica
Aeschynomene indica [Linnaeus] acc [annoter avec aut.]
Secula viscidula = Aeschynomene viscidula
Aeschynomene nivea acc
Aeschynomene biflora = Aeschynomene brasiliana
Aeschynomene Brasiliana = Aeschynomene brasiliana acc
Aeschynomene fascicularis Schlechtendal & Chamisso acc [corriger aut. par annot]
Aeschynomene montevidensis acc
Aeschynomene rudis acc
Aeschynomene sensitive L. : n'existe pas = Aeschynomene sensitiva Swartz [taxon 15019] [il faudra sans doute valider ce taxon]

J'ai fait quelques annotations - Luc
