### ISSUE TITLE
Rosa wichuraiana (syn.) et Rosa lucieae (nom acc.) selon FNA

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1890]
base de données MT
Rosa wichuraiana Crépin
ID de taxon = 11418
Spécimen à MT = MT-187926
protologue = http://www.biodiversitylibrary.org/page/3183566#page/547/mode/1up

Rosa lucieae Franchet & Rochebrune ex Crépin
FNA, vol. 9, p. 85
eFlora description et syn. = http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250100417
eFlora clef = http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=318050

Geoff

**Comment by brouille** [comment]
Rosa wichuraiana = Rosa lucieae

je suis heureux que Simon ait revu le spécimen et re-déterminé l'espèce à multiflora - cela fait que je ne l'ajouterai pas à VASCAN
