### ISSUE TITLE
New Person or combination Nouveau carex

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1891]
202096: 1 ière détermination: Schoenoxiphium sp.
202096: déterminateur #2: Det. B. K.
202097: récolteur: C.J. Ward
202099: 2e déterminateur: det. T.K. 68
202100: 2e déterminateur: Det. B.K. -68
202102: récolteur et déterminateur #1: Dr. W.H. Burk (nouveau projet)

Claude Lucier 19 octobre 2015

**Comment by geoffreyhall** [comment]
Ajouts et modifications effectuées, fiches mises à jour
