### ISSUE TITLE
New Taxon prêt MT15-14 plantes du Nunavut

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1900]
203782: 1 ière détermination: Tofieldia (écrit à la main sans autorité)
203785: 1 ière détermination: Tofieldia borealis (Wl.) Wahlenb.
203797, 203798, 203801: 1 ière détermination: Ranunculus sulphureus Solander
203802: 1 ière détermination: Ranunculus sulphureus Sol.
203799, 203800: 3e détermination: Ranunculus sulphureus

Claude Lucier,  30 octobre 2015

**Comment by brouille** [comment]
203782 écriture de S. Hay - ajouté dét par
Tofieldia borealis = Tofieldia pusilla [det él LB]
Ranunculus sulphureus acc
