### ISSUE TITLE
 famille des athyriaceaes

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1904]
Athyrium thelypteroides n'apparaît pas dans la banque lorsque recherché. Onle trouve seulement en mettant Athyrium

Diane Fournier

**Comment by brouille** [comment]
C'est pcq orthographe est erroné: Athyrium thelypterioides [il manque un i sur le spécimen - une erreur fréquente]
fiche 1620
je ne peux entrer un nom mal orthographié - LB
