### ISSUE TITLE
New Taxon Rhodoscirpus asper

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1906]
Rhodoscirpus asper (J. Presl & C. Presl) Léveillé-Bourret, Donadío & J.R. Starr

18980   dét. 2
48131   dét. 2
48707   dét. 2
50042   dét. 3

http://www.ingentaconnect.com/content/iapt/tax/2015/00000064/00000005/art00006;jsessionid=lwytgn2wpe64.alice

![leveille-bourret et al 2015_rhodoscirpus_taxon64 5 940](https://cloud.githubusercontent.com/assets/11761405/11120840/66635b36-8920-11e5-86df-977ac8ffd0d8.png)

Geoff

**Comment by brouille** [comment]
Rhodoscirpus asper acc
