### ISSUE TITLE
New Taxon_var. d'Aster macrophyllus

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1908]
132135
dét 1
dét. 2 (parce que "stet!", à moins que le 2e déterminateur ne soit pas d'accord)

Aster macrophyllus L. var. ianthinus (Burgess.) Fern.

Geoff

**Comment by brouille** [comment]
det 2 : le stet était pour l'espèce, pas la var. - mauvaise annotation de ma part en fait

Aster macrophyllus var. ianthinus = Eurybia macrophylla
