### ISSUE TITLE
New Taxon Salix hybride

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1909]
39304
dét. 3
Salix arctica Pall. x Salix glauca subsp. callicarpaea (Trautv.) Böcher

39306
dét. 3
Salix arctica Pall. x Salix glauca subsp. callicarpaea (Trautv.) Böcher

Geoff

**Comment by brouille** [comment]
Salix arctica × Salix glauca subsp. callicarpaea = Salix ×waghornei

le verbatim des coordonnées géographiques devrait être fourni pour tous les spécimens de cette série
ajouter: source coordonnées : label
