### ISSUE TITLE
New Taxon Carex Océanie

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1913]
197962: 2e détermination: Carex gaudichaudiana Kunth. answers to var. humilior Kukenthal

Claude Lucier, 25 novembre 2015

**Comment by brouille** [comment]
Carex gaudichaudiana Kunth. answers to var. humilior Kukenthal
non répertorié ds Flore NZ, mais acc ds ALA
syn de appendiculata var. app. ds WCSP - il y a ici conflit taxonomique sur l'interprétation de la var.
il ne faut PAS annoter avec le nom accepté car il se pourrait qu'il faille déterminer le spécimen à n ouveau
