### ISSUE TITLE
New Taxon Carex Amérique du Sud

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1923]
198271: 1 ière détermination àa vérifier s.v.p.(voir photo):Carex goodenoughii (Hay) (vulgaris Friey) B. pumila Kükenthal

claude Lucier  4 décembre 2015

**Comment by brouille** [comment]
Carex vulgaris Fries ß pumila Kükenthal
Carex goodenoughii J. Gay ß pumila Kükenthal
