### ISSUE TITLE
New Taxonfamille des thelypderidaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1924]
Aspidium thelypteris,Sw.........Nouvelle écosse

Thelypteris palustris (L.) Nieuwl.  var. pubescens (Laws.) Fern. différence dans les auteurs ....Nouveau Brunswick

Dryopteris palustris....Québec

Thelypteris thelypteridoides (Michaux) Holub...Québec

Dryopteris palustris O. Ktze....Québec

Dryopteris thelypteris (L.)  A. Gray var. pubescens (Lawson) A.R. Prince ex Weatherby...Québec les  auteurs multiples

Nephrodium patens Desv....USA

Thelypteris normalis....USA

Aspidium unitum var. glabrum Mett. ...USA

Aspidium unitum R. Br....USA

Diane Fournier

**Comment by brouille** [comment]
Aspidium thelypteris = Thelypteris palustris var. palustris [formellement - ms si NS = var. pubescens]
Thelypteris palustris var. pubescens acc [voir auteurs bd Taxon]

**Comment by brouille** [comment]
Dryopteris palustris [nom mal appliqué au QC] = Thelypteris palustris var. pubescens
Dryopteris thelypteris (L.) A. Gray var. pubescens (Lawson) A.R. Prince ex Weatherby [auteurs ± erronés] = Thelypteris palustris var. pubescens
Nephrodium patens = Christella patens [nom provisoire]
Thelypteris normalis = Christella normalis
Aspidium unitum var. glabrum = Cyclosorus interruptus
Aspidium unitum R. Br. : n'existe pas avec cette autorité = Cyclosorus interruptus

PROBLÈME:
Thelypteris thelypteridoides : le nom n'existe pas ds les bd - il me faudra vérifier le spécimen pour voir ce dont il s'agit

**Comment by herbier** [comment]
Thelypteris thelypteridoides= Thelypteris palustris Schott var. pubescens (Lawson) Fernald

**Comment by brouille** [comment]
Thelypteris thelypteridoides = Thelypteris palustris var. pubescens
