### ISSUE TITLE
Désaccord entre MT et Vascan, nom accepté de Sinapis alba

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#1943]
Vascan
http://data.canadensys.net/vascan/taxon/4117
nom acc. = Sinapis alba subsp. alba

Taxon table à MT:
ID de taxon
19677
nom acc. = Sinapis alba var. alba
syn. = Sinapis alba subsp. alba

Geoff

**Comment by brouille** [comment]
c'était une erreur de transcription - corrigé à subsp.
