### ISSUE TITLE
New Taxon - Schoenus

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1950]
Schoenus nigricans L. var. aggregatus (Thumb.) Kük.
Cyperus schoenoides (R. Br.) Poir.
Schoenus mucronatus L.
Schoenus nitens subsp. krausei (Phil.) Kük.
Schoenus rhynchosporoides (Steud.) Kük.
Schoenus rhynchosporoides (Steud.) Pfeiffer
Carpha paniculata Phil.
Schoenus andinus (Phil.) H. Pfeiff.
Schoenus apogon Roem. & Schult.
Schoenus calostachyus (R. Br.) Poir.
Schoenus nitens (R. Br.) Poir.
Schoenus pauciflorus (Hook.f.) Hook.f.
Schoenus pedicellatus (R. Br.) Poiret
Schoenus philippinensis (Palla) Kük. var. kinabaluensis (Stapf) Kük.
Schoenus pleiostemoneus F. Muell.
Schoenus setifolius Benth.
Helothrix axillaris (R. Br.) Palla
Chaetospora axillaris R. Br.
Helothrix pusilla Nees
Schoenus subaxillaris (R. Br.) Kük.
Schoenus tenuissimus (J. D. Hook.) Benth.
Schoenus tenuissimus Benth.
Chaetospora tenuissima J. D. Hooker
Lepidospora tenuissima F.Muell.
Schoenus tesquorum J.M.Black
Schoenus tetragonus (R.Br.) Poir.
Schoenus turbinatus (R.Br.) Poiret
Chaetospora turbinata R.Br.
Schoenus moorei Benth.
Schoenus maschalinus Roem. & Schult.
Schoenus imberbis R.Br.
Schoenus imberbis Poiret
Schoenus grandiflorus F.Muell.
Schoenus flavus Boeck.
Schoenus ericetorum R.Br.
Schoenus curvifolius Poir.
Schoenus curvifolius (R.Br.) Poir.
Schoenus brevifolius R.Br.
Helothrix imberbis (R.Br.) Palla
Chaetospora imberbis R.Br.
Schoenus brownii J. D. Hooker

Sarah

**Comment by brouille** [comment]
Schoenus nigricans var. aggregatus = Schoenus nigricans

Schoenus mucronatus = Cyperus capitatus

Cyperus schoenoides  = Fimbristylis squarrulosa

**Comment by brouille** [comment]
Schoenus nitens subsp. krausei = Schoenus nitens var. nitens
Schoenus nitens acc
Schoenus rhynchosporoides (Steud.) Pfeiffer : aucune donnée sous ces auteurs [auteur erroné]
Schoenus rhynchosporoides  (Steud.) Kük. acc
Carpha paniculata = Schoenus rhynchosporoides
Schoenus andinus acc
Schoenus apogon acc
Schoenus calostachyus acc
Schoenus pauciflorus acc
Schoenus pedicellatus acc
Schoenus philippinensis var. kinabaluensis = Schoenus curvulus

**Comment by brouille** [comment]
Schoenus pleiostemoneus acc
Helothrix axillaris = Schoenus maschalinus
Chaetospora axillaris = Schoenus maschalinus

Schoenus setifolius = Ficinia filiformis

**Comment by brouille** [comment]
Helothrix pusilla = Schoenus maschalinus
Schoenus maschalinus acc
Schoenus subaxillaris = Schoenus maschalinus
Schoenus tenuissimus = Schoenus lepidosperma subsp. lepidosperma
Chaetospora tenuissima [bien que ce soit le basionyme du nom ci-dessus et un nom illeg., WCSP reconnaît syn lepidosperma !] = Schoenus lepidosperma subsp. lepidosperma
Lepidospora tenuissima = Schoenus lepidosperma subsp. lepidosperma
Schoenus tesquorum acc
Schoenus turbinatus acc
Chaetospora turbinata = Schoenus turbinatus
Schoenus moorei acc
Schoenus imberbis R. Brown acc
Schoenus imberbis Poiret = Schoenus apogon [vérifier que ce spécimen diffère du précédent ; l'auteur attribué pourrait avoir été erroné] @geoffreyhall 
Helothrix imberbis = Schoenus apogon
Chaetospora imberbis = Schoenus apogon
Schoenus brownii = Schoenus apogon
Schoenus grandiflorus acc
Schoenus flavus Boeck. = Schoenus subflavus
Schoenus ericetorum acc
Schoenus curvifolius (R.Br.) Poir. = nom. illeg. = Schoenus curvifolius (R. Brown) Roemer & Schultes
Schoenus brevifolius acc

Schoenus tetragonus = Mesomelaena tetragona

**Comment by herbier** [comment]
Note sur Schoenus imberbis R. Brown et Schoenus imberbis Poiret

Sur l'étiquette originale de MT-206449 il est écrit:
Schoenus imberbis R. Br. Prodr. Fl. N. Holl., p. 231 (1810)

Sur l'étiquette originale de MT-206448 il est écrit:
Helothrix imberbis (R.Br.) Palla = Chaetospora imberbis R.Br. Prodr. Fl. N. Holl., p. 233 (1810) = Schoenus imberbis Poiret in Enc. méth. Suppl. II, p. 251 (1811) = Schoenus apogon R.S.  Syst. veg. II, p. 77 (1817) = Schoenus brownii J. D. Hooker Handb. of the New Zealand Flora, p. 298 (1867)

Geoff

**Comment by brouille** [comment]
Schoenus imberbis R. Br. acc
Schoenus imberbis (R. Brown) Poiret nom. inval. = Schoenus apogon
