### ISSUE TITLE
New Taxon Type Carex

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1963]
117630, 72450: 1 ière détermination: Carex lepidocarpa X distans, C. binderi Podp
196066: 1 ière détermination: Carex Brenneri Christ = Carex umbrosa Host ssp. sabyensis less ap. Kunth (acc. to Kükenth.)
72459: 2e détermination:  Carex olivacea Boott
117639: [Carex involueus?] non publié? (le nom peut être involvens 

Claude Lucier 20 janvier 2016

**Comment by brouille** [comment]
Carex lepidocarpa X distans, C. binderi Podp : la det sur le type est ambigüe car la formule hybride est une explication du nom proposé par Podpera - je crois que nous devrions entrer le nouveau nom (avec le x, déjà en bd sous 2516) et laisser la formule hybride en note de détermination
C. binderi = Carex ×binderi

Carex brenneri = Carex umbrosa subsp. sabynensis
annotation électronique au nom acc - annoter le spécimen

Carex olivacea acc

Carex involvens ou involuens Raymond ne semble pas avoir été publié - nom. nudum
il faudrait re-déterminer ce matériel - ou alors det2 eset correcte?
