### ISSUE TITLE
Documentation Actaea racemosa Québec

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2048]
Spécimens à MT:
5737     Rodrigue, Donald     no. 13a     Mont Saint-Bruno     1993-06-30
5738     Rodrigue, Donald     no. 13b     Mont Saint-Bruno     1994-07-25
19601     Sabourin, Denis; Bellerose, Pauline     no.5     Mont Saint-Bruno     2005-10-06

Geoff

**Comment by brouille** [comment]
ajouté à VASCAN - il eut été mieux d'utiliser le Github de VASCAN, cependant
