### ISSUE TITLE
New Taxon (projet d'Édeline)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2076]
**Nouveaux taxons**
#181833-183125-183126-183127-183128   (det2) Denisophytum madagascariense R. Viguier
#183090-91/212255-56-57-58-59/212429-30-31-32 (det2) Arquita mimosifolia (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes
#183070/183103-104-105/212248-49-50-51-52-53-54 (det 2) Erythrostemon Exilifolia (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes
#183068-69/212244-45-46-47 (det 2) Erythrostemon coluteifolia (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes
#183060/212040-41-42-43 (det 2) Erythrostemon coulterioides (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes
#183096-98-99-100-101-102/212401-02-03-04-15-16-17-18-19-20-21-22-23-24-25-26 (det2) Arquita trichocarpa (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes var. trichocarpa

Merci!

Chloé F.

**Comment by brouille** [comment]
Denisophytum madagascariense acc
Arquita mimosifolia acc

**Comment by brouille** [comment]
Erythrostemon exilifolia [ined.] acc [à valider]
Erythrostemon coluteifolia [ined.] acc [à valider]
Erythrostemon coulterioides [ined.] acc [à valider]
Arquita trichocarpa var. trichocarpa acc : no 183097 avait été manqué - compléter date annot. det2

**Comment by brouille** [comment]
183097 date complétée
