### ISSUE TITLE
Problème géoréférence de 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2127]

**Comment by herbier** [comment]
Problème géographique avec quelques unes de vos anciennes récoltes (13 en 1975).

Est-ce que vous vous rappelez d'un certain ruisseau Saint-Jean à La Prairie? J'ai 13 planches que vous avez récolté là avec J. Dufour en 1975. Le problème est que le seul ruisseau de ce nom dans la MRC est dans le coin de Chateauguay. Les fiches ont été relevés car la proposition de localisation est dans l'eau, à l'embouchure de ce ruisseau de l'ouest de la Montérégie... loin de La Prairie.
En passant, Geoffrey aimerait savoir qui est derrière les initiales C.V. ainsi que le prénom de J. Dufour avec qui vous avez fait ces récoltes.

Merci à l'avance

Daniel C. votre géographe "en résidence" ;-)

**Comment by brouille** [comment]
Je n'ai jamais récolté avec cette personne en 1975. Quelqu'un a remplacé L.B. par Luc Brouillet dans ces fiches, ce qui était erroné.

Il faut remettre L.B.

Je ne peux aider en ce qui concerne la localité.
Luc
