### ISSUE TITLE
Lilaea sp.

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2136]
216280  Lilaea sp.  de l'Argentine 

auttres spécimens
216213 Lilaea scilloides  (Alberta)
 216277 Lilaea scilloides Mexique
216278 Lilaea scilloides  USA
216279 Lilaea scilloides   USA   

à annoter comme Triglochin 

Claire Picotte

**Comment by brouille** [comment]
Lilaea sp. de l'Argentine  = scilloides = Triglochin scilloides
