### ISSUE TITLE
New Person or combination  Triglochin

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2137]
216277  Lilaea scilloides  couple de récolteur et identif.  Bye, Robert; Weber, W.A.
216278  ajouter parc  "Laguna de Santa Rosa Wetlands Preserve'  
                       http://www.visitredwoodcoast.com/content/laguna-de-santa-rosa-wetlands-preserve/nco7E83F9EEEFB0937A4
 216279  couple de récolteur (Verne Grant et Irving Schneider) déjà Verne dans notre liste mais pa trouvé référence pour Schneider sauf même récolte à Berkeley  https://webapps.cspace.berkeley.edu/ucjeps/publicsearch/publicsearch/

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour
Geoffrey
