### ISSUE TITLE
New Taxon : 2 espèces remplacent 2 variétés

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2145]
L'article suivant enlèverait la var. austrolucorum du Carex lucorum ne laissant apparemment que la var. lucorum dans le complexe.  Conclusion :  les deux taxons deviendraient les Carex lucorum et Carex austrolucorum

http://link.springer.com/article/10.1007/s12228-014-9348-y
http://download.springer.com/static/pdf/566/art%253A10.1007%252Fs12228-014-9348-y.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2Fs12228-014-9348-y&token2=exp=1468619846~acl=%2Fstatic%2Fpdf%2F566%2Fart%25253A10.1007%25252Fs12228-014-9348-y.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.1007%252Fs12228-014-9348-y*~hmac=606011248e6775b13461cb02178288b851cd74df2cef766b4a972767531e355a

Poindexter, Derick B. & Robert F.C. Naczi.  2014.  Taxonomy and geographic distribution of Carex lucorum var. austrolucorum (section Acrocystis, Cyperaceae).  Brittonia 66(4): 358-370.

Abstract:
Carex lucorum currently comprises two morphologically similar varieties. We revise 
the taxonomy of C. lucorum, and map the distribution of the taxa. Based on multivariate 
analyses and analyses of variance of measured characters, allopatry, and previous studies 
revealing differences in achene micromorphology, chromosome differences, and flavonoid 
chemistry, we elevate C. lucorum var. austrolucorum to species status as C. austrolucorum. 
We provide an identification key to C. lucorum and its closest relatives.

Geoff

**Comment by brouille** [comment]
Carex austrolucorum acc
Carex lucorum var. austrolucorum = Carex austrolucorum
Carex lucorum acc
Carex lucorum var. lucorum = Carex lucorum
