### ISSUE TITLE
Juncus bufonius Linnaeus :  les var. ne sont plus acceptées

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2146]
Selon Vascan ("Juncus bufonius Linnaeus var. bufonius est un synonyme sensu TROPICOS de Juncus bufonius Linnaeus, un nom accepté d'espèce sensu Kirschner et al., 2002") ---
Juncus bufonius Linnaeus var. bufonius = Juncus bufonius Linnaeus
http://data.canadensys.net/vascan/taxon/6259
## ID de taxon 7436, 16923, 17180, 18316 ne devraient plus comporter de variété

Selon Vascan ("Juncus bufonius var. halophilus Buchenau & Fernald est un synonyme sensu Kirschner et al., 2002 de Juncus ranarius Songeon & E.P. Perrier, un nom accepté d'espèce sensu Kirschner et al., 2002") ---
Juncus bufonius Linnaeus var. halophilus Buchenau & Fernald = Juncus ranarius Songeon & E.P. Perrier
http://data.canadensys.net/vascan/taxon/6261
ID de taxon 7437 ne devrait pas comporter de variété mais plutôt changer de nom d'espèce

Geoff

**Comment by brouille** [comment]
corrigé dans la bd Taxon
