### ISSUE TITLE
Juncus bufonius vars. bufonius & halophilus = 2 spp. dans Vascan

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2158]
MT (ID de taxon 7436)
## Juncus bufonius var. bufonius = Juncus bufonius var. bufonius

Vascan
Juncus bufonius var. bufonius = Juncus bufonius Linnaeus
http://data.canadensys.net/vascan/taxon/6260?lang=fr

---

MT (ID de taxon 7437)
## Juncus bufonius var. halophilus = Juncus bufonius var. halophilus

Vascan
Juncus bufonius var. halophilus = Juncus ranarius Songeon & E.P. Perrier
http://data.canadensys.net/vascan/taxon/16758?lang=fr

Geoff

**Comment by brouille** [comment]
Juncus bufonius var. bufonius = Juncus bufonius 
Juncus bufonius var. gracilis = Juncus bufonius
Juncus bufonius var. occidentalis = Juncus bufonius
Juncus bufonius var. halophilus = Juncus ranarius
Juncus ranarius acc
tout est mis à jour et ranarius ajouté
fiches de bd corrigées, incluant fiches WAT complétées et une annotation él. SBLUM
Luc
