### ISSUE TITLE
Complexe Juncus effusus (MT ≠ Vascan)

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2159]
MT (ID de taxon 18318)
Juncus effusus Linnaeus subsp. effusus [syn.] =
## Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus effusus Linnaeus subsp. effusus [syn.] =
Juncus effusus Linnaeus subsp. effusus [nom acc.]
http://data.canadensys.net/vascan/taxon/25005?lang=fr

---

MT (ID de taxon 7478)
Juncus pylaei Laharpe [syn.] =
Juncus effusus Linnaeus [nom acc.]
MT (ID de taxon 7453, 7454)
Juncus effusus Linnaeus var. pylaei (Laharpe) Fernald & Wiegand [syn.] =
## Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus pylaei Laharpe [syn.] =
Juncus pylaei Laharpe [nom acc.]
Juncus effusus Linnaeus var. pylaei (Laharpe) Fernald & Wiegand [syn.] =
Juncus pylaei Laharpe [nom acc.]
http://data.canadensys.net/vascan/taxon/16783?lang=fr

---

MT (ID de taxon 7455)
Juncus effusus Linnaeus var. solutus Fernald & Wiegand [syn.] =
Juncus effusus Linnaeus [nom acc.]
MT (ID de taxon 7448)
Juncus effusus Linnaeus subsp. solutus (J. Presl) G. Weimarck [syn.] =
## Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus effusus Linnaeus var. solutus Fernald & Wiegand [syn.] =
Juncus effusus subsp. solutus (Fernald & Wiegand) Hämet-Ahti [nom acc.]
Juncus effusus Linnaeus subsp. solutus (J. Presl) G. Weimarck [syn. non trouvé] =
Juncus effusus subsp. solutus (Fernald & Wiegand) Hämet-Ahti [nom acc.]
http://data.canadensys.net/vascan/taxon/16775?lang=fr

---

MT (ID de taxon 7452)
Juncus effusus Linnaeus var. decipiens Buchenau [syn.] = 
##  Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus effusus Linnaeus var. decipiens Buchenau [syn.] =
Juncus effusus Linnaeus subsp. effusus [nom acc.]
http://data.canadensys.net/vascan/taxon/25005?lang=fr

---

MT (ID de taxon 7451)
Juncus effusus Linnaeus var. conglomeratus (Linnaeus) Engelmann [syn.] = 
Juncus effusus Linnaeus [nom acc.]
MT (ID de taxon 7445)
Juncus conglomeratus Linnaeus [syn.] = 
## Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus effusus Linnaeus var. conglomeratus (Linnaeus) Engelmann [syn.] =
Juncus conglomeratus Linnaeus [nom acc.]
Juncus conglomeratus Linnaeus [syn.] =
Juncus conglomeratus Linnaeus [nom acc.]
http://data.canadensys.net/vascan/taxon/23554?lang=fr

---

MT (ID de taxon 7449)
Juncus effusus Linnaeus var. compactus Lejeune [syn.] =
## Juncus effusus Linnaeus [nom acc.]

Vascan
Juncus effusus Linnaeus var. compactus Lejeune [syn.] =
Juncus effusus Linnaeus subsp. effusus [nom acc.]
http://data.canadensys.net/vascan/taxon/25005?lang=fr

Geoff

**Comment by brouille** [comment]
Juncus effusus acc
Juncus effusus subsp. solutus acc
Juncus effusus var. compactus = Juncus effusus subsp. effusus
Juncus effusus var. conglomeratus = Juncus conglomeratus
Juncus effusus var. decipiens = Juncus effusus subsp. effusus
Juncus effusus var. pylaei = Juncus pylaei
7454 répétition de 7453 effacé
Juncus effusus var. solutus = Juncus effusus subsp. solutus
Juncus effusus subsp. effusus acc
Juncus pylaei acc
Juncus conglomeratus acc
