### ISSUE TITLE
New Taxon (Crataegus)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2161]
205661, 205663: 1ière détermination: Crataegus rotundifolia Moench var. pubera Sargent
205662: 1ière détermination: Crataegus rotundifolia var. pubera Sarg
205675: 1ière détermination: Crataegus rotundifolia Moench var. pubera Sarg.
205671: 1ière détermination: Crataegus Douglasii Lindl
205672: 3e détermination: Crataegus lumaria Ashe

Claude Lucier 22 août 2016

**Comment by brouille** [comment]
Crataegus rotundifolia var. puber [pubera corrigé à puber] 
Crataegus douglasii acc
Crataegus lumaria acc
