### ISSUE TITLE
New Taxon (Solidago)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2163]
214093, 214101, 214103, 214105: 1 ière détermination: Solidago rugosa Mill. var. cronquistiana Semple, in. ed.

214095, 214099, 214107: 1 ière détermination: Solidago rugosa Mill. var cronquistiana Semple

Claude Lucier 24 août 2016

**Comment by brouille** [comment]
Solidago rugosa var. cronquistiana acc
