### ISSUE TITLE
New county: Morrison County, Minnesota

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#217]
[Originally posted on GoogleCode (id 429) on 2013-02-26 by portokayak]

Country: United States
Province/State: Minnesota
MRC/District/County: Morrison County
<b>Park:</b>

ID of the specimen(s):183922

Your name:Diane Juteau

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-04 23:39Z]

Nom ajouté et enregistrement mis à jour
