### ISSUE TITLE
New Taxon (Solidago WAT)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2172]
214203: 2e détermination: Solidago rugosa Mill. var. aspera
214109, 214111, 214113, 214115, 214121, 214123: 1ière détermination: Solidago rugosa Ait. var. aspera (Ait.) Fernald
214119: 1ière détermination: Solidago rugosa Ait. var. aff. aspera (Ait.) Fernald
214217, 214221: 1 ière détermination: Solidago rugosa Mill. ssp. aspera (Ait.) Cronq. var celtidifolia (Small) Fern.
214223: 1 ière détermination: Solidago rugosa Mill. var. celtidifolia (Small) Fernald
214215: 1ière détermination: Solidago rugosa Mill. var. aff. celtidifolia (Small) Fernald
214277, 214285, 214287: 1ière détermination: Solidago ulmifolia Muhl.
214279: 1ière détermination: Solidago ulmifolia Muhl. ex Willd.
214281: 1ière détermination: Solidago ulmifolia Muhl. ex Willd. var. ulmifolia Cronq.
214277, 214279, 214285, 214287: 2e détermination: Solidago ulmifolia Muhl. ex Willd. var. ulmifolia
214283: 1ière détermination: Solidago ulmifolia Muhl. ex Willd. aff. palmeri Cronq.
214273, 214275: 1 ière détermination: Solidago ulmifolia Muhl. ex Willd. var. aff. palmeri Cronq.

Claude Lucier   7 septembre 2016

**Comment by brouille** [comment]
Solidago rugosa var. aspera = acc = Solidago rugosa subsp. aspera var. aspera
Solidago rugosa subsp. aspera var celtidifolia acc
Solidago rugosa var. celtidifolia = acc = Solidago rugosa subsp. aspera var celtidifolia
Solidago ulmifolia acc
Solidago ulmifolia var. ulmifolia acc
Solidago ulmifolia var. palmeri acc
