### ISSUE TITLE
New Taxon Solidago (WAT)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2173]
214227: 2e détermination: Solidago simplex Kunth ssp. randii (Porter) Ringius var. monticola

214309: 3e détermination: Solidago canadensis X uliginosa   [? can X ulig] voir photo
        2e détermination: Solidago canadensis cf. va bartramiana Fern.  voir photo
        1ière détermination: Solidago bartramiana Fern.
214131: 1ière détermination: Solidago rugosa Mill. aff. ssp. aspera (Ait.) Cronq. var aspera  

214325, 214609: 4e détermination: Solidago lepida DC. var. molina Fern.

214323: 2e détermination: Solidago lepina aff. molina
214321: 2e détermination: Solidago fallax var. molina

Claude Lucier   12 septembre 2016

**Comment by brouille** [comment]
Solidago simplex subsp. randii : ds bd
Solidago canadensis X S. uliginosa : unknown
Solidago canadensis var. bartramiana = Solidago bartramiana = S. x bartramiana
Solidago rugosa subsp. aspera var. aspera acc
Solidago lepida var. molina = Solidago lepida aff. molina = Solidago fallax var. molina acc

**Comment by geoffreyhall** [comment]
214227: 2e détermination: Solidago simplex Kunth ssp. randii (Porter) Ringius var. monticola

la variété monticola a été oublié (ajout svp)

Geoff

**Comment by brouille** [comment]
Solidago simplex subsp. randii var. monticola = S. randii
