### ISSUE TITLE
New Taxon (Solidago WAT)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2175]
214245, 214213: 2e détermination: Solidago wrightii A. Gray var. guadalupensis G.L. Nesom
                1ière détermination: Solidago wrightii A. Gray
214173: 2e détermination: Solidago [aff.] virgata Michx. (S. stricta sensu authors not. Ait.) voir photo
214247, 214249 : 1ière détermination: Solidago litoralis Savi214155: 1ière détermination: Solidago rugosa Mill. ssp. rugosa var, villosa (Pursh) Fern.
214269: 1 ière détermination: Solidago elliottii T. & G.
        2e détermination: Solidago pulverulenta Nutt. (voir photo)
214271: 2e détermination: Solidago pulverulenta Nutt.
        1ière détermination: Solidago puberula Nutt. ssp. pulverulenta (Nutt.) Semple

Claude Lucier 14 septembre 2016

**Comment by herbier** [comment]
214155: 1ière détermination: Solidago rugosa Mill. ssp. rugosa var, villosa (Pursh) Fern.

Cette ligne n'est pas claire dans la demande

**Comment by brouille** [comment]
Solidago wrightii var. guadalupensis acc
Solidago wrightii acc
Solidago virgata acc
Solidago litoralis acc

**Comment by brouille** [comment]
Solidago rugosa subsp. rugosa var. villosa = Solidago rugosa subsp. rugosa var. rugosa
Solidago elliottii = Solidago latissimifolia
Solidago pulverulenta acc
Solidago puberula subsp. pulverulenta = Solidago pulverulenta

214269 : je crois ici que l'auteur a utilisé une étiquette de pulverulenta car il n'en avait pas de latissima - il a corrigé le nom - donc j'ai enlevé l'annotation à pulverulenta pour ce spécimen
