### ISSUE TITLE
New Taxon (Vérification SBLUM)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2176]
44865: 1ière détermination: Hypericum boreale (Britt.) Bickn. var. callitrichoides Fassett

Claude Lucier  19 Septembre 2016

**Comment by brouille** [comment]
Hypericum boreale var. callitrichoides [var. n'existe pas, mais f. existe avec cet auteur] = Hypericum boreale f. callitrichoides = Hypericum boreale
