### ISSUE TITLE
New person - E.A. Rau

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#218]
[Originally posted on GoogleCode (id 430) on 2013-02-26 by portokayak]

Person name(s): E.A. Rau (serait Eugene Abraham Rau, 1848-1932 selon HUH)
Date de collecte: 30 juillet 1900. Nouvelle-Écosse

<b>Field (collector, determined by, catalogued by, etc.):</b>

ID of the specimen(s): 183927

Your name: Diane Juteau

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-02-26 18:22Z]

nom ajouté et fiche mise à jour
