### ISSUE TITLE
New Taxon(projet herbier des poètes montréalais

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2182]
217065: 1ière détermination: Cucumis melo L. 
217064: 1ière détermination: Cucumis sativa L.
217069: 1ière détermination: Salisburia adiantifolia Gray
217070: 1 ière détermination: Malus Malus (L) Britton
217078: 1 ière détermination:Cosmos bipinnatus Cav. cv. sensation

Claude Lucier 3 octobre 2016

**Comment by brouille** [comment]
Cucumis melo acc
Cucumis sativa acc
Salisburia adiantifolia Gray = [pas Gray ms Smith] = Ginkgo biloba
Malus Malus = Malus pumila
Cosmos bipinnatus cv. 'Sensation' acc
