### ISSUE TITLE
New Taxon (herbier des poètes montréalais)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2187]
17241: 1 ière détermination: Polupus deltoides Marsh. X tacamahacca Mill.

Claude Lucier  10 octobre 2016

**Comment by brouille** [comment]
vérifier det - est-ce vraiment l'hybride Populus ×jackii ?
je n'ai pas e-annoté le spécimen pour cette raison - Luc

**Comment by geoffreyhall** [comment]
Déterminé à Populus ×jackii et annoté; base de données mise à jour
Geoff
