### ISSUE TITLE
New Taxon famille des Fabacea

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2189]
Cassia armata Wats...Usa

Cassia roemeriana Scheele...Usa

Cassia Wislizeni Gray...Usa

Cassia bahamensis Mill.

Cassia hebecarpa Fern...Ontario

Cassia marylandica...Ontario

Ditremexa marilandica (L.) Britton & Rose...Usa

Diane Fournier

**Comment by brouille** [comment]
Cassia armata = Senna armata
Cassia roemeriana = Senna roemeriana
Cassia wislizeni = Senna wislizeni
Cassia bahamensis = Senna ligustrina
Cassia hebecarpa = Senna hebecarpa
Cassia marylandica [nom. illeg. = Cassia marilandica] = Senna marilandica 
[NOTE: cette plante ne se trouve pas en Ontario - il faudrait valider la det. avant d'annoter - probablement hebecarpa ?]
Ditremexa marilandica = Senna marilandica

**Comment by geoffreyhall** [comment]
2 spécimens ontariens de Cassia marylandica / Cassia hebecarpa déterminés à Senna hebecarpa et annotés; base de données mise à jour.
Geoff
