### ISSUE TITLE
Histoire du spécimen - Nouveau nom

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#219]
[Originally posted on GoogleCode (id 508) on 2013-03-22 by portokayak]

Institution name(s):Memorial University College Herbarium
Autre appellation pour NFLD

<b>Field (collector, determined by, catalogued by, etc.):</b>

ID of the specimen(s):184540

Your name:Diane Juteau

J'ai déjà indiqué le bon acronyme dans le champ &quot;Histoire du spécimen&quot;

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-04-08 17:47Z]

Nom(s) ajouté(s) et fiche(s) mis(es) à jour
