### ISSUE TITLE
New Taxon Plantes enthéogènes des Amériques 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2191]
217090: 2e détermination: Virola surinamersis
        1ière détermination: Myristica surinamensis Rol. "Cajuca"
217091: 3e détermination: Virola sebifera Aubl. 
        2e détermination: Virola sebifera Aubl.
        1ière détermination: Dialyanthera  
217092: 2e détermination: Virola theiodora 
217104: 1ière détermination: Datura sanguinea R. et P.
217105: 1ière détermination: Brugmansia Wrightii
217107: 1ière détermination: Brugmansia suavolens
217093: 1ière détermination: Strychnos brasiliensis (Spr.) Mart.
217094: 1ière détermination: Strychnos brasiliensis (Spreng.) Mart.
217095: 1ière détermination: Strychnos guianensis (Aubl.) Mart.
217096: 1ière détermination: Strychnos guianensis (Aubl.) Mart. "irary verdadeiro"
217098: 1ière détermination: Strychnos guianensis (Aubl.) Mart. "cuare verdadeiro"
217099: 1ière détermination: Strychnos parviflora Spruce "irary-acu"
217100: 1ière détermination: Strychnos micrantha Spruce

Claude Lucier 14 octobre 2016

**Comment by brouille** [comment]
Virola surinamensis acc
Dialyanthera = Otoba
Virola sebifera acc
Virola theiodora  acc

Datura sanguinea = Brugmansia sanguinea

**Comment by brouille** [comment]
Brugmansia wrightii [unpublished] = Datura wrightii
Brugmansia suaveolens acc

Strychnos brasiliensis acc
Strychnos guianensis acc
Strychnos parviflora acc
Strychnos micrantha = Strychnos tarapotensis
