### ISSUE TITLE
New Taxon (Tetraria)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2193]
217360: 2e détermination: Tetraria capillaris (F. Muell.) J.M. Black
217361, 217362: 1ière détermination:Tetraria capillaris (F. Muell.) J.M. Black
217363: 1ière détermination: Tetraria borneensis (sans autorité)
217364: 1ière détermination: Macrochaetium dregei Steud.
217365: 1ière détermination: Tetraria 
217366, 217370: 1ière détermination: Tetraria picta  C.B. Cl.
217367, 217369: 1ière détermination: Tetraria crinifolia C.B. Cl.
217368: 1ière et 2e détermination: Tetraria sp.
217371, 217373: 1ière détermination: Tetraria cuspidata C.B. Cl.
217372: 1ière détermination: Tetraria compar Lestib.
217374: 1ière détermination: Tetraria punctoria C.B. Cl.

Claude Lucier 17 octobre 2016

**Comment by brouille** [comment]
Tetraria capillaris acc
217360 y avait-il une det par Blake? cf fiches suivantes
Tetraria borneensis acc
Tetraria acc
Tetraria picta acc
Tetraria crinifolia acc
Tetraria cuspidata acc
Tetraria compar acc

Tetraria punctoria = Neesenbeckia punctoria

Macrochaetium dregei = Cyathocoma hexandra
