### ISSUE TITLE
New Taxon famille des Fabacea

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2194]
Cassia medsgeri Shafer ...USA

Chamaecrista brachiata Pollard.....Usa

Cassia chamaecrista L....USA

Cassia nictitans L. var. hebecarpa Fern....USA

Cassia nictitans L. ...USA

Cassia nictitans Michx.

Cassia nictitans L. var. nictitans L...USA

Chamaecrista aspera (L.) Grt....USA

Chamaecrista aspera (Muhl.) Greene...USA

Cassia aspera Muhl.....USA

Cassia obtusifolia L...USA

Cassia (senna) obtusifolia

Chamaecrista cinerea Pollard...USA

Cassia bicapsularis L...USA

Cassia covesii Gray...USA

Cassia gooddingii  A. Nels.

Chamaecrista littoralis Polld...USA

Cassia mohrii Pollard....USA

Chamaecrista multipinnata (Pollard) Greene..USA

Chamaecrista procumbens (L.) Greene...USA

Psilorhegma suffuticosa (Koenig) Britton (suffuticosa serait suffruticosa)

Chamaecrista aeschinomene (DC.) Greene..Amérique centrale

Cassia glandulosa   (collecteur Moss,Smith & Millman) Amérique centrale

Cassia goldmanii Rose...Amérique centrale

Chamaecrista juruensis (Hoehne) Irwin & Barneby   (juruensis=juruenensis)  Amérique centrale

Cassia laevigata, Willd..Amérique centrale

Cassia racemosa Mill....Amérique centrale

Cassia tristicula H.B.K...Amérique centtrale

Cassia singueana Del. var. Kethulleana (D.W.) Ghess....Afrique

Cassia mimosoides Linn....Afrique

Cassia fistulosa Linn....Afrique

Cassia bacillaris   ..Afrique

Cassia aphylla Cav...Asie

Cassia angustissima Lam....Asie

Cassia artemisioides Gaudich. ex. DC.....Océanie

Cassia chrysosepala Irwin & Barneby.....Océanie

Cassia divaricata Nees. & Bl.....Océanie

Cassia helmsii Symon...Océanie

Cassia nemophila var. platypoda (R.Br.) Benth....Océanie

Cassia nemophila var. coriacea...Océanie
Cassia nemophila var. coriacea  (Benth.) Symon

Cassia nemophila var. zygophylla (Benth.) Benth....Océanie

Cassia nemophila  Cunn. ex Vog...Océanie

Cassia pruinosa F. Muell.....Cassia pruinosa F. Muell.

Cassia punctata Vog.....Océanie

Chamaecrista rotundifolia (Pers.) Greene var. rotundifolia...Océanie

Cassia neesiana Mart. var. goyazensis ......Océanie

Cassia nemophila var. nemophila Cunn. ex Vogel...Océanie

Diane Fournier

**Comment by brouille** [comment]
Cassia medsgeri = Senna marilandica
Cassia obtusifolia = Cassia (senna) obtusifolia = Senna obtusifolia
Cassia bicapsularis = Senna bicapsularis
Cassia covesii = Senna covesii

Cassia chamaecrista = Chamaecrista fasciculata var. fasciculata
Chamaecrista brachiata = Chamaecrista fasciculata var. fasciculata

Cassia nictitans Michx. [erreur auteur] = Cassia nictitans L. = Chamaecrista nictitans subsp. nictitans var. nictitans
Cassia nictitans var. nictitans = Chamaecrista nictitans subsp. nictitans var. nictitans
Cassia nictitans var. hebecarpa = Chamaecrista nictitans subsp. nictitans var. nictitans

Chamaecrista aspera (L.) Grt [aut. erroné] = (Muhl.) Greene = Chamaecrista nictitans subsp. nictitans var. aspera
Cassia aspera = Chamaecrista nictitans subsp. nictitans var. aspera

**Comment by brouille** [comment]
Cassia gooddingii = Senna hirsuta var. glaberrima
Psilorhegma suffruticosa = Senna surattensis

Chamaecrista littoralis = Chamaecrista fasciculata
Cassia mohrii Pollard : nom. nudum [= Cassia aspera var. mohrii Pollard] = Chamaecrista nictitans subsp. nictitans var. nictitans
Chamaecrista multipinnata = Chamaecrista nictitans subsp. nictitans var. nictitans
Chamaecrista procumbens = Chamaecrista nictitans subsp. nictitans var. nictitans
Chamaecrista aeschinomene = Chamaecrista nictitans subsp. patellaria var. glabrata

**Comment by brouille** [comment]
Cassia glandulosa = Chamaecrista glandulosa var. glandulosa
Chamaecrista juruenensis acc
Cassia tristicula = Chamaecrista glandulosa var. tristicula
Cassia mimosoides = Chamaecrista mimosoides
Cassia angustissima = Chamaecrista mimosoides
Cassia chrysosepala [ce spécimen vient bien d'Océanie? sp. du Brésil] = Chamaecrista chrysosepala

Cassia goldmanii = Senna polyantha
Cassia laevigata = Senna septemtrionalis
Cassia racemosa = Senna racemosa
Cassia singueana var. kethulleana (De Wildeman) Ghesquière = Senna singueana
Cassia bacillaris = Senna bacillaris
Cassia aphylla = Senna aphylla
Cassia artemisioides = Senna artemisioides
Cassia divaricata = Senna divaricata
Cassia helmsii = Senna artemisioides subsp. helmsii

Cassia fistulosa L, [mal épelé] = Cassia fistula L. acc [Taxon 3352] [annoter le spécimen au nom correct svp]

**Comment by brouille** [comment]
Cassia nemophila var. platypoda = Senna artemisioides subsp. ×petiolaris
Cassia nemophila var. zygophylla = Senna artemisioides subsp. zygophylla
Cassia nemophila var. coriacea = Senna artemisioides subsp. ×coriacea
Cassia nemophila = Senna artemisioides subsp. ×coriacea
Cassia nemophila var. nemophila = Senna artemisioides subsp. ×coriacea
Cassia pruinosa = Senna glutinosa subsp. pruinosa

Cassia punctata = Chamaecrista punctata
Chamaecrista rotundifolia var. rotundifolia acc
Cassia neesiana var. goyazensis = Chamaecrista neesiana var. goyazensis

**Comment by herbier** [comment]
chamaecrista cinerea Pollard....USA pas fait

 Lorsque je mets "Chamaecrista brachiata"..." Cassia chamaecrista ".....j'obtiens "Chamaecrista fasciculata var. fasciculata" et si je mets ce nom pour la recherche je reviens à "Chamaecrista fasciculata (Michaux) Greene" comme nom scientifique accepté pour l'étiquette

**Comment by herbier** [comment]
Pour "Cassia nemophila  Cunn. ex Vogel"  le nom donné est "Senna artemisioides subsp. x coriaces" mais ce nom n'apparaît pas dans la banque

**Comment by brouille** [comment]
Senna artemisioides subsp. ×coriacea est ds la bd, id 24165
le signe × est un signe de multiplication et non un x

Chamaecrista fasciculata var. fasciculata corrigé
