### ISSUE TITLE
MRC/County/District

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2196]
217360 https://en.wikipedia.org/wiki/Walshs_Pyramid
Cairn's Region : ajouter à la liste des subdivisions du Queensland
https://en.wikipedia.org/wiki/Cairns_Region

L'Australie a-t-elle été complétée ?
Luc

**Comment by brouille** [comment]
217363 Bako National Park
https://en.wikipedia.org/wiki/Bako_National_Park

Luc

**Comment by brouille** [comment]
217365 https://en.wikipedia.org/wiki/Kouebokkeveld_Mountains
ajouter Western Cape Province https://en.wikipedia.org/wiki/Western_Cape
Ceres Division: est-ce un comté de cette province?
Luc

**Comment by brouille** [comment]
217368 South Africa : ajouter Prov. Transvaal 
https://en.wikipedia.org/wiki/Transvaal_Province
et Dist. Lydenburg https://en.wikipedia.org/wiki/Transvaal_Province#Districts_in_1991
svp vérifier pour ce spécimen s'il y a 2 det ou une seule, par B. de Winter - Claude a mis 2 det ms elles semblent identiques

**Comment by brouille** [comment]
217373 Hlabisa distr
 ajouter district

**Comment by brouille** [comment]
217372 et -4 : Caledon Division, Western Cape Province
Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour.  L'Australie n'est pas encore complétée, l'Afrique du Sud non plus, mais certaines provinces le sont.
Geoff
