### ISSUE TITLE
New Taxon (Plantes pour la botaniste d'Argentine)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2198]
217396: 1ière détermiantion: Serjania reticulata Camb.
217404, 217403: 1ière détermination: Cardiospermum halicacabum L.  
217402: 1ière détermination: Paullinia leiocarpa Griseb.
217403: 1ière détermination: Paullinia macrophylla H.B.K.
217400: 1ière détermination: Paullinia hispida Jacq.
217399: 1ière détermination: Serjania exarata Radlk.
         2e détermination: Serjania glabrata Kunth
217398: 1ière détermination: Serjania paradoxa Radlk.
214627: 1ière détermination: Sejania atrolineata Sauv. & Wright

Claude Lucier 19 octobre 2016

**Comment by herbier** [comment]
la demande pour la fiche 217403 est pour la fiche 217401: 1ière détermination: Paullinia macrophylla H.B.K.

**Comment by brouille** [comment]
Serjania reticulata acc
Serjania exarata acc
Serjania glabrata acc
Serjania paradoxa acc
Serjania atrolineata acc

Cardiospermum halicacabum acc

Paullinia macrophylla acc
Paullinia hispida acc
