### ISSUE TITLE
New Taxon (Cassia)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2213]
Cassia fistulosa Lim.
 Cassia baccilaris (sans autorité)
 Cassia hookeriana Gill
 Cassia crassiramea Benth.
 Cassia obovata Collad.
 Cassia oxyphylla Kunth.
 Cassia multijuga L.C. Rich.
 Cassia aff. tomentosa L.
 Adipera indecora (KBK.) Britton & Rose
 Cassia reniformis G. Don
 Cassia reticulata Willd.
 Cassia carnaval Speg.
 Cassia stipulacea (sans autorité)
 Cassia subulata Gris.
 Cassia viminea L.
 Senna machaeriifolia (Benth.) Irwin & Barneby
 Cassia orenocensis Spruce
 Cassia lavradiiflora Harms
 Cassia pilosa L.
 Cassia trichopoda Benth.
 Cassia repens Vog. var multijuga (Bth.) Irwin & Barneby
 Cassia rotundiflia Pers. var. rotundifolia
 Martiusia elata f. occidentalis Ducke

Claude Lucier 7 novembre 2016

**Comment by brouille** [comment]
Cassia fistulosa Linn. = Cassia fistula L.

Cassia bacillaris [j'ai présumé que l'autorité est L. f., antérieure à Willd. ex Steud. nom. illeg.] = Senna bacillaris
Cassia hookeriana = Senna birostris var. hookeriana
Cassia crassiramea = Senna crassiramea
Cassia obovata = Senna italica
Cassia oxyphylla = Senna oxyphylla
Cassia multijuga = Senna multijuga subsp. multijuga
Cassia tomentosa L.f. [pas L. - il faudrait corriger sur annotation] = Senna multiglandulosa
Adipera indecora = Senna pendula var. indecora [besoin de validation]
Cassia reniformis = Senna reniformis
Cassia reticulata = Senna reticulata
Cassia carnaval = Senna spectabilis
Cassia stipulacea [j'ai présumé Ait., auteur prioritaire - valider] = Senna stipulacea
Cassia subulata = Senna subulata
Cassia viminea = Senna viminea

Senna machaeriifolia [nom. nudum - comb. faite sous Chamaecrista et non Senna avec ces auteurs] = Chamaecrista machaeriifolia
Cassia orenocensis = Chamaecrista orenocensis
Cassia lavradiiflora = Chamaecrista lavaradiiflora
Cassia pilosa = Chamaecrista pilosa
Cassia trichopoda = Chamaecrista trichopoda
Cassia rotundifolia var. rotundifolia = Chamaecrista rotundifolia var. rotundifolia

Cassia repens Vog. var multijuga (Bth.) Irwin & Barneby : ce nom n'existe pas et en fait a peu de sens étant donné les auteurs de la var.
la seule var. multijuga Bentham est  Cassia brachypoda var. repens = Chamaecrista repens var. multijuga (Benth.) H.S. Irwin & Barneby
le récolteur semble avoir attribué à Cassia une combinaison de Chamaecrista

Martiusia elata f. occidentalis Ducke : Ducke a créé var. occidentale et non f. occidentale [noter orthographe] = Martiodendron elatum var. occidentale
