### ISSUE TITLE
New Taxon (Cassia)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2214]
Cassia cinerascens Vog.
Cassia basifolia Vog.
Cassia cathartica Mart.
Cassia cordistipula Mart.
Cassia brevipus D.C.
Leonocassia stenophylla (Benth.) Britton
Chamaecrista riparia (H.B.K.) Britton
Cassia mimosoides L. var. glaloriuscula Gherg.
Cassia crassiramea Benth.
Ditremaxa (Cassia) occidentalis (sans autorité)
Cassia nictitans L. var. ramosa (Vog.)

Claude Lucier 9 novembre 2016

**Comment by brouille** [comment]
Cassia cinerascens = Chamaecrista cinerascens
Cassia basifolia = Chamaecrista basifolia
Cassia cathartica = Chamaecrista cathartica
Cassia cordistipula = Chamaecrista cordistipula
Cassia brevipEs = Chamaecrista desvauxii var. brevipes
Chamaecrista riparia = Chamaecrista nictitans var. jaliscensis
Cassia crassiramea = Senna crassiramea [déjà bd 24289]

Leonocassia stenophylla = Senna stenophylla
DitremExa (Cassia) occidentalis = Senna occidentalis

**Comment by brouille** [comment]
Cassia mimosoides var. glaloriuscula Gherg. = var. glabriuscula Ghesq.  [nom. nud.?] = Chamaecrista mimosoides [ce spécimen pourrait être un isotype ou à tout le moins un spécimen associé au nom qui ne semble pas avoir été décrit)
voir: apps.kew.org/herbcat/detailsQuery.do?imageId=15513&pageCode=1&presentPage=1&queryId=3&sessionId=B1C7F635A884D271FC85CF790E07E858&barcode=K000232484

Cassia nictitans var. ramosa = Chamaecrista nictitans var. jaliscensis
ne semble pas avoir été publié - basionyme : Cassia patellaria var. ramosa Vogel  www.tropicos.org/Name/13007785
par contre: Chamaecrista nictitans var. ramosa (Vogel) H.S. Irwin & Barneby www.tropicos.org/Name/13045807
il y a ambiguité sur le nom acc : certains utilisent plutôt Chamaecrista nictitans var. patellaria (DC. ex Collad.) Kartesz & Gandhi
