### ISSUE TITLE
New Taxon Famille des brassicaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2225]
Wasabia tenuis Matsum...avec autre annotation "Eutrema alliaria"à  la main au-dessus de l'étiquette Asie

Bunias cochlearioides L.   et   Calepina corvini sur le même étiquette....Europe

 Erysium officinale L. ...Québec
 
 Brassica nigra (Juncea)...Québec
 
  Brassica oleracea L. var. botrytis L...Québec
  
  Brassica oleracea L. var. botrytis Desf..
  
  Brassica oleracea L. var. rubra..Québec
  
  Brassica oleracea L. var. italica Plenck...usa
  
  Brassica oleracea L. (forma)...usa
  
  Brassica rampa L. [syn.] Brassica campestris L.].....TNO

Diane Fournier

**Comment by brouille** [comment]
Eutrema alliaria n'existe pas ; cependant, pour le wasabi, les synonymes suivants existent:
Alliaria wasabi et Eutrema wasabi - le récolteur a sans doute fait une confusion
je n'entrerai pas ce nom car il ne s'agit pas d'une détermination mais d'une note, semble-t-il

Bunias cochlearioides acc
Calepina corvini [24053] n'est pas un syn - il se pourrait qu'il y ait 2 plantes sur la planche?

ErysiMum officinale = Sisymbrium officinale

Brassica nigra [fiche 2082] acc
Brassica juncea acc [fiche 2078]
je ne sais pourquoi il y a cette ()

Brassica oleracea var. botrytis L. [seule autorité correcte] acc [chou-fleur]
Brassica oleracea var. rubra = Brassica oleracea
Brassica oleracea var. italica acc [broccoli]
Brassica oleracea L. (forma) = Brassica oleracea

Brassica rampa [mal épelé] = Brassica rapa acc
Brassica campestris = Brassica rapa
