### ISSUE TITLE
New Taxon (Specimen Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2246]
182896: 2e détermination: Wagatea spicata (Dalz.) Wright (=Caesalpinia spicata Dalz.)  
214703: Larrea (sans autorité) 
214705, 214707, 214709, 217711, 214713: 3e détermination: Arquita trichocarpa (Grisebach) E. Gagnon, G.P. Lewis & C.E. Hughes var. boliviana E. Gagnon, G.P. Lewis & C.E. Hughes 
214717, 214719: 1ière détermination: Mezoneuron welwitschianum Oliv.

Claude Lucier, 10 février 2017

**Comment by brouille** [comment]
Wagatea spicata (Dalz.) Wright = Moullava spicata
Larrea Ortega [Fabaceae] = nom. rej. = Hoffmannseggia
Arquita trichocarpa var. boliviana acc
Mezoneuron welwitschianum = Moullava welwitschiana
