### ISSUE TITLE
New Taxon (spécimen de Edeline)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2249]
214723: 1 ière détermination: Hoffmanseggia jamesii T. & G. 
214725: 1ière et 2e détermination: Pterolobium cf. hexapetalum (Roth) Santapau & Wagh. 
214727: 1ière et 2e détermination: Pterolobium hexapetalum (Roth.) Sant. & Wagh  
214729:1 ière et 2e détermination: Pterolobium indicum A. Rich. 
214731:1ière et 2e détermination: Pterolobium micranthum Gagnep-emend-Craib 

Claude Lucier, 15 février 2017

**Comment by brouille** [comment]
Hoffmanseggia jamesii = Hoffmannseggia jamesii = Pomaria jamesii
Pterolobium hexapetalum acc
Pterolobium indicum = Pterolobium hexapetalum
Pterolobium micranthum acc [il ne faut pas ajouter emend. Craib]
