### ISSUE TITLE
New Taxon (Specimen Edeline)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2253]
214745, 214747: 2e détermination: Gelrebia trothae (Harms) E. Gagnon & G.P. Lewis 
214749: 3e détermination: Coulteria velutina (Britton & Rose) Sotuyo & G.P. Lewis
214773: 1ière et 2e détermination: Mezoneuron kauaiense (sans autorité)
214783- 214785, 214787: 2e détermination: Hultholia mimosoides (Lamarck) E. Gagnon & G.P. Lewis

Claude Lucier 20 février 2017

**Comment by brouille** [comment]
Gelrebia trothae acc
Coulteria velutina acc [ined]
Mezoneuron kauaiense acc
Hultholia mimosoides acc
