### ISSUE TITLE
parc - Labrador

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2254]
Okak National Historic Site of Canada
http://www.historicplaces.ca/en/rep-reg/place-lieu.aspx?id=14408

localisé au village fantôme de Okak [Okkak], Labr., ancienne mission morave

ce site historique doit être ajouté pour ttes les localités Okkak ou Okak de bd - cf 125729

Luc

**Comment by brouille** [comment]
Gannet Islands Ecological Reserve
http://www.ecc.gov.nl.ca/parks/wer/r_gie/index.html

cf 127535 - tttes loc. Gannet Islands

Luc

**Comment by geoffreyhall** [comment]
--125729, ajout de nom , 109 fiches mises à jour
--127535, ajout de nom , 8 fiches mises à jour

Geoff
