### ISSUE TITLE
New Taxon (Asclépias)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2258]
220741: 1ière détermination: Asclepias Phytolaccoides Pursh
220777: 1ière détermination: Asclepias cornuti Decne

Claude Lucier 27 février 2017

**Comment by brouille** [comment]
Asclepias phytolaccoides = Asclepias exaltata [noter que ce taxon a été considéré une var. de syriaca]
Asclepias cornuti = Asclepias syriaca
