### ISSUE TITLE
New Taxon (Asclepias)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2265]
220900, 220899: 1ière détermination: Asclepias syriaca L. x A. speciosa Torr.
220898: 1ière détermination: Asclepias syriaca L. var. syriaca
220897: 1ière détermination: Asclepias syriaca L. f. syriaca

Claude Lucier, 3 mars 2017

**Comment by brouille** [comment]
Asclepias syriaca f. syriaca = Asclepias syriaca
Asclepias syriaca var. syriaca = Asclepias syriaca
Asclepias speciosa × Asclepias syriaca acc
