### ISSUE TITLE
Nom acc. dans bD MT ≠ nom acc. dans Vascan

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2266]
Vascan/Tropicos/IPNI =
Sabulina stricta (Swartz) Reichenbach
[réf. oblique dans Dillenberger 2016 <http://public.bibliothek.uni-halle.de/index.php/schlechtendalia/article/viewFile/1876/2108>]

base de données MT =
Sabulina stricta (Swartz) Dillenberger & Kadereit

Geoff

**Comment by brouille** [comment]
Correction effectuée partout où nécessaire. Merci
L
