### ISSUE TITLE
New Taxon (Asclépias)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2267]
220907: 1ière détermination: Asclepias incarnata [espace] pulchra 
(la forme, la sous espèce et la variété existe dans tropicos: )

Claude Lucier , 6 mars 2017

**Comment by brouille** [comment]
Asclepias incarnata var. pulchra [j'ai choisi la var. car la subsp. n'avait pas été décrite à cette période et il me semble moins probable qu'on aurait reconnu la f.] = Asclepias incarnata subsp. pulchra
