### ISSUE TITLE
national forest USA

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2275]
214217
Francis Marion and Sumter National Forests
https://www.fs.usda.gov/scnfs

Luc

**Comment by brouille** [comment]
214281
Mount Magazine State Park
http://www.mountmagazinestatepark.com/
https://en.wikipedia.org/wiki/Mount_Magazine

Luc

**Comment by brouille** [comment]
214299
Henry Horton State Park
http://tnstateparks.com/parks/about/henry-horton

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour.
Geoff
