### ISSUE TITLE
New Taxon(prêt MT-17-03 Potamogeton et Bromus)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2277]
221195 : 1ière détermination : Potamogeton tenuifolius Raf. var. subellipticus Fernald
221207 : 1ière détermination : Bromus tectorum L. var. glabratum
221216,  221217 : 1ière détermination : Avena (sans autorité)

Claude Lucier 13 mars 2017

**Comment by brouille** [comment]
Avena acc
Bromus tectorum var. glabratum = Bromus tectorum
Potamogeton tenuifolius var. subellipticus [(Fernald) Fernald] = Potamogeton alpinus
