### ISSUE TITLE
New Taxon (Solidago Nova Scotia  MT-17-04)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2280]
221239, 221240, 221241, 221242, 221243, 221244, 221245, 221246, 221247:
3e détermination: Euthamia caroliniana (Linnaeus) Greene ex Porter & Britton

221239, 221241, 221242, 221243, 221244, 221245, 221246: 
2e détermination: Euthamia tenuifolia (Pursh) Nutt. var. pycnocephala (Fern.) C & J Taylor
221239, 221241, 221242, 221243:
 
1ière détermination: Solidago tenuifolia Pursh. var. pycnocephala Fern.

221240, 221247: 2e détermination: Euthamia tenuifolia (Pursh) Nutt.
221240, 221247: 1ière détermination: Solidago tenuifolia Pursh.

221244: 1ière détermination: Solidago graminifolia (L.) Salisb. var. Nuttalli (Greene) Fernald
221245, 221246: 1ière détermination: Solidago galetorum Greene

221248, 221249: 4e détermination: Euthamia caroliniana (Linnaeus) Greene ex Porter & Britton
221248: 3e détermination: Euthamia tenuifolia (Pursh) Nutt. var. pycnocephala (Fern.) C & J Taylor
221248: 2e détermination: Solidago tenuifolia Pursh.

221249: 3e détermination: Euthamia tenuifolia (Pursh) Nutt.
221249: 2e détermination: Solidago tenuifolia (sans autorité)

Claude Lucier 17 mars 2017

**Comment by brouille** [comment]
Euthamia caroliniana acc
Euthamia tenuifolia var. pycnocephala = Euthamia caroliniana
Euthamia tenuifolia = Euthamia caroliniana
Solidago tenuifolia var. pycnocephala = Euthamia caroliniana
Solidago galetorum = Euthamia caroliniana
Solidago graminifolia var. nuttallii = Euthamia graminifolia
