### ISSUE TITLE
New Taxon (plantes de Pierre Dansereau)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2285]
220251, 220042: Détermination: Cedronella canariensis (L.) W & B
220409: Détermination: Chrysanthemum broussonetti Balb.
220353, 220288: Détermination: Ardisia excelsa Ait.
220095: Détermination: Pimpinella buchii W & B (P. cubrae Buch)
220094: Détermination: Smilax canariensis Willd.
220041: Détermination: Prunus lusitanica L. 

Claude Lucier 24 mars 2017

**Comment by brouille** [comment]
Cedronella canariensis acc
Chrysanthemum broussonetti = Argyranthemum broussonetii
Ardisia excelsa = Heberdenia excelsa
Pimpinella buchii = Pimpinella cumbrae Link ex de Candolle

**Comment by brouille** [comment]
Smilax canariensis acc

**Comment by brouille** [comment]
Prunus lusitanica acc
