### ISSUE TITLE
New Taxon (Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2295]
214807: 1 ière détermination: Caesalpinia exilifolia Gris.

Claude Lucier 5 avril 2017

**Comment by brouille** [comment]
Caesalpinia exilifolia = Erythrostemon exilifolius fiche 15101

récolteur et det par auraient dû être : Jörgensen, P. [nouvelle personne] - j'ai corrigé
Luc
