### ISSUE TITLE
New Taxon (plantes Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2301]
214857, 214859: 4e détermination: Arquita ancashiana (Ulibarri) E. Gagnon, G.P. Lewis & C.E. Hugues
182014, 214865: 3e détermination: Arquita ancashiana (Ulibarri) E. Gagnon, G.P. Lewis & C.E. Hugues
214861, 214863, 214867: 2e détermination: Arquita ancashiana (Ulibarri) E. Gagnon, G.P. Lewis & C.E. Hugues

Claude Lucier  10 avril 2017

**Comment by brouille** [comment]
Arquita ancashiana acc
