### ISSUE TITLE
Corée: provinces

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2318]
152905
Seoul National Capital Area
https://en.wikipedia.org/wiki/Seoul

Il faudrait faire le niveau 2 de Corée

Luc

**Comment by geoffreyhall** [comment]
Seoul Capital Area inclut les divisions administratives du niveau provincial de 1) Seoul Special Metropolitan City, 2) Incheon Metropolitan City, et 3) Gyeonggi Province; fiches mises à jour.
Geoff
