### ISSUE TITLE
New Taxon (récolte Edeline)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2323]
212291: det.#1: Vigna
212292: det.#1: Mimosa revoluta (Kunth.) Benth.
212294: det.#1: Mimosa montana Kunth.
212294: det.#2: Mimosa montana Kunth. var. montana
212303: det.#1: Coursetia fruticosa (Cav.) Macbride
212307: det.#1: Lupinus piurensis C.P. Sm.

Claude Lucier 3 mai 2017

**Comment by brouille** [comment]
Vigna acc
Mimosa revoluta acc
Mimosa montana acc
Mimosa montana var. montana acc
Coursetia fruticosa acc
Lupinus piurensis 
ATT: 212294: det.#2: PAR QUI?

**Comment by herbier** [comment]
#2323: j"ai vérifié avec Edeline; le déterminateur est M. Colin E. Hughes

**Comment by brouille** [comment]
212294 det2 corrigé
