### ISSUE TITLE
New Taxon (récoltes de Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2335]
212290: det #1: Acacia macracantha Humb. & Bonpl. ex Willd.
212273: det.#1: Vicia andicola Kunth.
212280: det.#1: Galactia (sans autorité)
212313: det.#1: Lupinus semperflorens Hartw. ex Benth.
212312: det.#1: Zacoteca carascana (Jacq.) H. Hern.
212340: det.#1: Coursetia cajamarcana Lavin
212339: det.#1: Desmanthus acuminatus Benth.
212336: det.#1: Tephrosia (sans autorité)
212331: det.#1: Albizia multiflora var. multiflora (Kunth) Barneby & Grimes
212326: det.#1: Rhynchosia (sans autorité)

Claude Lucier 12 mai 2017

**Comment by brouille** [comment]
Acacia macracantha = Vachellia macracantha [annoté él. par LB - mais peut-être Édeline voudra annoter?]
Vicia andicola acc
Galactia acc
Lupinus semperflorens acc
Coursetia cajamarcana acc
Desmanthus acuminatus acc
Tephrosia acc
Albizia multiflora var. multiflora acc
Rhynchosia acc

Question:
Zacoteca carascana est-il mal épelé ?

**Comment by herbier** [comment]
Le nom est Zapoteca carascana (Jacq.) H. Hern.

Claude Lucier 15 mai 2017

**Comment by brouille** [comment]
Zapoteca caracasana acc [noter orthographe]
