### ISSUE TITLE
New Taxon  Familles des rocaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2337]
Sorbus aucuparia fastigiata 

Il y a une problématique avec Malus hyb. 'Prof. Sprenger car lorsque je met le nom j'obtiens "Malus × zumi cv. 'Prof. Sprenger'" et lorsque je mets ce nom je n'obteins pas " Malus × zumi 'Prof. Sprenger'" suggéré dans le message 2322 

 Autre problématique avec (Malus pumila "niedzwetzkyana hybrid  'Arrow'") car le nom "Malus pumila 'Arrow'" me ramène à "Malus pumila Miller var. niedzwetzkyana (Dieck) C.K. Schneider 'Arrow'. C'est comme si on tournait en rond

Plantes cultivées
 
 Sorbus intermedia minima     
 
 Sorbus intermedia var. arranensis
 
 Sorbus intermedia (Ehrh.) Pers. (S.scandica Fries)
 
 Sorbus intermedia var. minima   (% 1330-54 S. mougeotii)
 
 Sorbus japonica (Dcne) Hedl. var. calocarpa  Rehd.
 
 Sorbus koehneana Schneid
 
 Sorbus lancifolia    'c/o 2788-54 Sorbus fennicia
 
 Sorbus lancifolia   Hedl.    (% S.mougeotii)
 
 Sorbus lancifolia   
 
 Sorbus latifolia (Lam.) Pers.
 
 Sorbus mougeotii
 
  Sorbus pohuashanensis (Hance) Hedl.
  
  Sorbus pratii var. munda f. sub-arachnoidea   
  
  Sorbus pratii Koehne
  
  Sorbus randaiensis Koidzumi

Sorbus reflexipetala

Sorbus rufo-ferruginea

 Sorbus scalaris Koehne
 
 Sorbus serotina Koehne
 
 Sorbus sitchensis (Roe.)Piper
 
 Sorbus xthuringiaca (Isle) Fritsch
 
 Sorbus tianshanica Rupr.
 
 Sorbus vilmorinii C.K.Schneid.	
 
 Raphiolepis indica Lindl.
 
 Raphiolepis umbellata Makino
 
 Eriobotrya prionophylla Franch
 
 Eriobotrya  japonica Lindley
 

Diane Fournier

**Comment by brouille** [comment]
Malus ×zumi cv. 'Prof. Sprenger' ajouté Taxon 25824
Malus pumila 'Arrow' ajouté Taxon 25825  - mais il s'agit d'un cas non résolu car non trouvé

Sorbus intermedia minima = Sorbus intermedia var. minima = Sorbus minima
Sorbus intermedia var. arranensis = Sorbus arranensis
Sorbus intermedia déjà entré Taxon 25530
Sorbus japonica var. calocarpa acc
Sorbus koehneana acc
Sorbus lancifolia acc
Sorbus latifolia acc
Sorbus mougeotii acc
Sorbus pohuashanensis acc
Sorbus prattii acc [noter orthographie avec 2 t]
Sorbus randaiensis acc
Sorbus rufoferruginea = Sorbus randaiensis
Sorbus reflexipetala = Sorbus commixta
Sorbus serotina = Sorbus commixta
Sorbus scalaris acc
Sorbus sitchensis (Roe.)Piper [erroné] = Sorbus sitchensis M. Roemer Taxon 25506
Sorbus tianshanica [mal épelé] = Sorbus tianschanica fiche Taxon 22764

Raphiolepis indica [var. orthogr. rejeté] = Rhaphiolepis indica acc
Raphiolepis umbellata [var. orthogr. rejeté] = Rhaphiolepis umbellata acc

Eriobotrya prionophylla = Photinia prionophylla
Eriobotrya japonica acc

**Comment by herbier** [comment]
Sorbus prattii var. munda f. sub-arachnoidea   

 je n'ai pas de résultat pour ce nom

**Comment by brouille** [comment]
Sorbus pratii var. munda f. subarachnoidea : Sorbus munda = Sorbus prattii pas de var. munda et par de f. subarachnoidea
Sorbus prattii var. munda = unpublished = Sorbus prattii
je n'entrerai pas la f. subarachnoidea car je ne trouve rien, mais = Sorbus prattii
