### ISSUE TITLE
New taxon famille des brassicaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2349]
Sisymbrium parviflolium Phil. ...europe

Sisymbrium pinnatifidum DC....europe

Sisymbrium pinnatifidum DC. var. Peyrusianum Fourn. = S. Lapeyrousianum R.F....Europe

Sisymbrium polyceratium L....europe

Sisymbrium pyrenaicum Vill.....europe

Sisymbrium rhedonense Degland......

Sisymbrium runcinatum Lag. ex DC....europe

Sisymbrium runcinatum Lag. var. hirsutum (Lag.  pr. sp.) Coss.

Sisymbrium strictissimum L....europe
 
 Sisymbrium supinum L...europe
 
 Sisymbrium tanacetifolium L. = Hugeninia tanacetifolium Rchb.....europe
 
 Sisymbrium villarsii Jrd....europe
 
 Sisymbrium volgense Bieb. ex. E.Fournier ..europe
 
 Sisymbrium zanonii Gay         Erucastrum zanonii Ball.
 
 Sisymbrium wolgense MB......europe
 
Sisymbrium junceum MB.,....Asie

Sisymbrium luteum O.E. Schultz      Nom. Jap. Kibana-hatazao..Asie

Nasturtiopsis coronopifolia (Desf.) Boiss.     (Sisymbrium coronopifolia Desf.)   ......Afrique

Sisymbrium Doumetianum Coss....afrique

Sisymbrium irio L. var. multisiliquosum......Afrique

Sisymbrium incisum Gray

Sisymbrium incisum Engelm...USA...Ontario

Sisymbrium incisumEngl. var. filipes Gray

Sisymbrium incisum filipes Gray...usa

Sophia incisa (Engelm.) Greene...USA

Sophia richardsonii (Sweet) Rydb....usa

Descurainia richardsonii (Sweet) Schulz ssp. viscosa (Rydb.) Detling ...USA

Descurainia richardsonii  ssp. procera (Greene) Detling ...usa

Descurainia richardsonii  (Sweet) O.E.  Schulz   procera (Greene) Detling ..usa

Descurainia richardsonii  (Sweet) O.E.  Schulz var. viscosa (Rydb.) Peck......usa

Descurainia richardsonii  (Sweet)   Schulz  subsp. incisa (Engelm.) Detl...usa

Sophia hartwegiana (Fourn.) Greene...usa

 Sophia filipes (A. Gray) Heller ..usa

 Sophia andrenarum Cockerell	

Sophia andrenarum Arkerell..usa

Sisymbrium incisum Engelm. var.hartwegianum (Fourn.) Wats...Québec

Descurainia richardsonii  (Sweet) O.E.  Schulz var. richardsonii....Québec

Descurainia hartwegianum (Watson) Britton...Québec

Descurainia richardsonii (Sweet) Schulz ssp. typica Detling ......manitoba

Diane Fournier

**Comment by brouille** [comment]
Sisymbrium parviflolium = parvifolium = Pennellia parvifolia

Sisymbrium pinnatifidum = Murbeckiella pinnatifida

**Comment by brouille** [comment]
Sisymbrium polyceratium acc
Sisymbrium pyrenaicum

**Comment by brouille** [comment]
Sisymbrium pinnatifidum var. lapeyrousianum (Rouy & Foucaud) P.Fourn. = Murbeckiella pinnatifida
Sisymbrium lapeyrousianum = Murbeckiella pinnatifida
Sisymbrium zanonii = Murbeckiella zanonii
Erucastrum zanonii = Murbeckiella zanonii

Sisymbrium supinum = Erucastrum supinum

Sisymbrium tanacetifolium [= Hugeninia tanacetifolium] = Descurainia tanacetifolia
Hugeninia tanacetifolia = Descurainia tanacetifolia
Sisymbrium incisum var. filipes = Sisymbrium incisum filipes =  Descurainia longepedicellata
Sophia filipes =  Descurainia longepedicellata
Sisymbrium incisum Engelmann ex A. Gray [noter 2 auteurs] = Descurainia incisa subsp. incisa
[NB: taxon non rapporté de Ont. - valider détermination]
Sophia incisa = Descurainia incisa subsp. incisa
Descurainia richardsonii subsp. viscosa = Descurainia incisa subsp. incisa
Descurainia richardsonii var. viscosa = Descurainia incisa subsp. incisa
Descurainia richardsonii subsp. incisa = Descurainia incisa subsp. incisa
Sophia richardsonii = Descurainia incana
Descurainia richardsonii var. richardsonii = Descurainia incana
Descurainia richardsonii subsp. typica [= nom. inval.] = Descurainia incana
Descurainia richardsonii subsp. procera = Descurainia richardsonii procera = Descurainia incana
Sophia hartwegiana = Descurainia incana
Descurainia hartwegiana  = Descurainia incana
Sisymbrium incisum var. hartwegianum = Descurainia incana
Sophia richardsonii (Sweet) Rydb = [aut. = (O.E. Schulz) Rydberg] = Descurainia incana
Sophia andrenarum Cockerell = [Ackerell : Cockerell mal écrit] = Descurainia pinnata subsp. ochroleuca

Sisymbrium rhedonense = Sisymbrium austriacum subsp. chrysanthum
Sisymbrium villarsii = Sisymbrium austriacum subsp. austriacum
Sisymbrium runcinatum acc
Sisymbrium runcinatum var. hirsutum = Sisymbrium runcinatum
Sisymbrium strictissimum acc
Sisymbrium wolgense [mal épelé] = Sisymbrium volgense = acc
Sisymbrium junceum = Sisymbrium polymorphum
Sisymbrium luteum [Nom. Jap. Kibana-hatazao = vernaculaire !] acc
Sisymbrium irio var. multisiliquosum = var. pas ds bd ms S. multisil. = Sisymbrium irio
Note : Sisymbrium pyrenaicum Vill : il n'y a pas entente entre les sources en ce qui concerne la disposition de ce taxon - les auteurs se contredisent et je ne peux décider quelle option est bonne - il faudra déterminer ce spécimen à nouveau

Nasturtiopsis coronopifolia acc
Sisymbrium coronopifolium = Nasturtiopsis coronopifolia

Sisymbrium doumetianum = Malcolmia doumetiana

**Comment by herbier** [comment]
Taxon 25993 erreur dans le nom scientifique pour l'étiquette , mauvais nom Diane Fournier

**Comment by brouille** [comment]
corrigé

**Comment by herbier** [comment]
Descurainia pinnata subsp. ochroleuca  taxon 26023, les noms d'auteurs non inscrits dans le nom scientifique pour l'étiquette

Diane Fournier

**Comment by brouille** [comment]
autorités ajoutées
