### ISSUE TITLE
New Taxon (plantes récoltées par Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2351]
212342: det. #1: Pithecellobium exceslum (Kunth.) Benth. 
212359: det. #1: Otholobium (sans autorité)

Claude Lucier 31 mai 2017

**Comment by brouille** [comment]
Pithecellobium excelsum acc
Otholobium acc

Pourquoi certains spécimens de cette série sont "specimen at MT" et d'autres "in preparation/being mounted" ?
