### ISSUE TITLE
New Taxon (plantes de Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2353]
212379, 212381, 212382: det.#1: Mimosa jaenensis T.E. Sarkinen, J.L. Marcelo-Pena & C.E. Hughes 
212375: det.#1: Acacia weberbaueri Harms
212373: det.#1: Mimosa lamolina C.E. Hughes & G.P. Lewis 
212372: det.#1: Mimosa pectinatipinna Burkart
212367: det.#1: Coursetia grandiflora Benth.
212385, 212386,212387,212392: det #2: Mimosa montana Kunth. var. sandemanii Barbeby
212398: det. #2: Arnoldoa weberbaueri (Muschl.) Ferreya vel sp. alf.
212398: det.#1: Arnoldoa (sans autorité)

Claude Lucier 2 juin 2017

**Comment by brouille** [comment]
Mimosa jaenensis acc
Acacia weberbaueri = Senegalia weberbaueri
Mimosa lamolina acc
Mimosa pectinatipinna acc
Coursetia grandiflora acc
Mimosa montana var. sandemanii acc
Arnaldoa acc
Arnaldoa weberbaueri acc
