### ISSUE TITLE
New TaxonFamille des rosaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2357]
Aronia arbutifolia  var. atropurpurea (Britt.) Schneider ..usa

Sorbus arbutifolia  var. atropurpurea (Britt.) Schneider ..USA

Diane Fournier

**Comment by brouille** [comment]
Aronia arbutifolia var. atropurpurea = Aronia ×prunifolia
Sorbus arbutifolia var. atropurpurea = Aronia ×prunifolia
