### ISSUE TITLE
New Taxon (plantes Edeline Gagnon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2406]
212237, 212238, 215636, 215637: 2e détermination: Hoffmannseggia doelli Philippi subsp. argentina Ulibarri
182132, 212343, 182131, 212338: 2e détermination: Arquita celendiniana (G.P. Lewis & C.E. Hughes) E. Gagnon, G.P. Lewis, & C.E. Hughes

Claude Lucier 16 août 2017

**Comment by brouille** [comment]
Hoffmannseggia doelli subsp. argentina acc
Arquita celendiniana acc
