### ISSUE TITLE
New Taxon famille des brasscacées

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2445]
Sisymbrium vilaenadalis Sennen  ...europe

Sisymbrium erysimoides Desf. var. xerophilum Fournier,,,,,,afrique

Sisymbrium columnae Jacq. ...afrique,europe                                                ..note importante lorsque j'ai inscrit le mot "Sisymbrium columnae Jacq."j'ai ajouté une lettre qu'il faut enlever "Sisymbarium columnae Hook f." afin d'obtenir le nom exact

Sophia sophia (L.) Britton...Québec

Diane Fournier

**Comment by brouille** [comment]
Sisymbrium vilaenadalis = Sisymbrium erysimoides
Sisymbrium erysimoides var. xerophilum = Sisymbrium erysimoides
Sisymbrium columnae = Sisymbrium orientale [j'ai corrigé Sisymbarium]

Sophia sophia = Descurainia sophia
