### ISSUE TITLE
New Taxon (saint-Pierre et Miquelon)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2471]
224057 2e det.: Eriophorum chamissonis C.A. Meyer var. chamissonis
224061,224060, 224059 :3e det.: Eriophorum vaginatum Linnaeaus subsp. spissum (Fernald) Hultèn f. erubescens (fern.) Boivin
224070, 224069, 224068: 2e det.:Eriophorum tenellum Nutt. var. tenellum

Claude Lucier 27 octobre 2017

**Comment by brouille** [comment]
Eriophorum chamissonis var. chamissonis
Eriophorum vaginatum subsp. spissum f. erubescens = Eriophorum vaginatum subsp. spissum [acc Cayouette ined?]
Eriophorum tenellum var. tenellum = Eriophorum tenellum
