### ISSUE TITLE
Parathelypteris noveboracensis : nom acc. ou syn.?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2475]
ID de taxon 5069 : Dryopteris noveboracensis (syn.), Parathelypteris noveboracensis (nom acc.)

ID de taxon 13397 : Thelypteris noveboracensis (nom acc.)

ID de taxon 21778 : Parathelypteris noveboracensis (syn.), Thelypteris noveboracensis (nom acc.)

Geoff

**Comment by brouille** [comment]
Le problème de Parathelypteris est que les ptéridologues sont encore en train de travailler sur ce problème. Alan Smith m'a dit que ce serait peut-être le nom ultime, mais présentement, le groupe se trouvait aussi à la base d'Amauropelta.

Pour l'instant, je propose de retenir Parathelypteris (Thelypteris ne sera pas le nom acc): ce sera à valider plus tard. J'ai modifié les fiches en conséquence pour les harmoniser.

Dans VASCAN, comme rien n'est final, je préfère ne pas changer Thelypteris .
Luc
