### ISSUE TITLE
New TaxonFamille des brassicacea

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2489]
fiche 27157 le nom scientifique pour étiquette on a  "Draba beckeri A. Kerner"        alors que le nom scientifique accepté est "Draba aizoides subsp. beckeri"

Stanleya elata Jones....usa

fiche 27177 le nom scientifique pour étiquette on a "Draba hederifolia Cosson"  alors que le nom scientifique accepté est "Graellsia hederifolia subsp. hederifolia"

Draba kananaskis Mulligan (2n=64) X Draba porsildii Mulligan (2n=32)........cultivée

Draba lactea Adams (2n=48) x Draba porsildii Mulligan (2n=32)

Draba lactea Adams (2n=48) X Draba praealta Greene (2n=56)

Draba longipes Raup. (2n = 64) X Draba lactea Adams (2n = 48)

Draba porsildii G.A. Mulligan (2n = 32) X Draba lonchocarpa Rydb. (2n = 16)

Draba porsildii G.A. Mulligan (2n = 32) X Draba Liljebl. (2n = 16)

Draba porsildii G.A. Mulligan (2n = 32) X Draba praealta Greene (2n = 56)

Draba tomentosa var. frigida ....cultivée

Draba traunsteineri...cultivée

Aubrietia columnae Guss...europe

Aubrietia deltoidea var. cilicica...cultivée

Aubrietia deltoidea var. Dr. Mules 

Alyssopsis mollis (Jacq.) O.E. Schulz...Asie

Schivereckia podolica Andrz....Asie

Athysanus pusillus (Hook.) Greene....USA

Thysanocarpus amplectens Greene....usa

Thysanocarpus curvipes Hooker var. madocarpus (Piper) Macbr...usa

Thysanocarpus elegans Benth....usa

Thysanocarpus elegans F.& M. (T. curvipes Hook. var. elegans Rob.)..usa

Thysanocarpus laciniatus Nutt. ex. T. & G.....usa

Thysanocarpus radians Benth.......usa

Thysanocarpus radians montanus Jepson........usa

Smelowskia americana Rybd....usa

Smelowskia calycina (Steph.) C.A. Mey. var. media (Drury & Rollins) Hult...Alaska
 
 Smelowskia calycina (Steph.) C.A. Mey. var. integrifolia (Seem.) Rollins...alaska
 
 Smelowskia calycina (Steph.) C.A. Mey subsp. calycina var. media (Drury & Rollins) Hult. laska
 
 Smelowskia calycina (Stephan) C.A. Mey. var. americana (Rybd.) Drury & Rollins...Alberta
 
 Smelowskia calycina (Desv.) C.A. Meyer...alberta
 
 Smelowskia calycina (Stephan) C.A. Meyer..usa
 
 Smelowskia calycina (Stephan) C.A. Meyer...usa
 
 Braya pectinata Greene.......usa
 
 Smelowskia ovalis M. E. Jones...usa
 
 Smelowskia ovalis M. E. Jones  subsp. congesta Rollins
 
 Smelowskia ovatus M. E. Jones
 
 Arabidopsis glauca (Nutt.) Rydb.....TNO
 
 Arabidopsis mollis (Hook.) O.E. Schulz...Nunavut..TNO
 
 Stenophragma thaliana (L.) Celax...usa
 
 Sisymbrium thalianum (L.) J. Gay...usa
 
 A la fiche 23716 il y a un problème pour "Arabidopsis suecica" le nom de lÉtiquette est "Cardaminopsis suecica (Fries) Norrlin " alors que le nom scientifique accepté est  "Arabidopsis suecica"
 
 Arabidopsis pumila (Steph.) N.Busch	....Asie

Diane Fournier

**Comment by brouille** [comment]
fiches 27157, 27177 & 23716 corrigées

Stanleya elata acc

Draba kananaskis × Draba porsildii = Draba juvenilis × Draba porsildii
Draba lactea × Draba porsildii acc
Draba lactea × Draba praealta
Draba lactea × Draba longipes
Draba lonchocarpa × Draba porsildii
NB: manque nom sp: Draba porsildii G.A. Mulligan  X Draba ????  Liljebl. 
Draba porsildii × Draba praealta
Non trouvé ds bd: Draba tomentosa var. frigida
Draba traunsteineri = Draba ×traunsteineri

[Aubrietia = Aubrieta]
Aubrieta columnae acc
Aubrieta deltoidea var. cilicica = Aubrieta canescens subsp. cilicica [provisoire]
Aubrieta deltoidea 'Dr. Mules' acc

Alyssopsis mollis acc

Schivereckia podolica acc provisoire [= Draba podolica?]

Athysanus pusillus acc

**Comment by brouille** [comment]
Thysanocarpus amplectens = Thysanocarpus curvipes
Thysanocarpus curvipes var. madocarpus [pas de var. ms f. avec ces auteurs] = Thysanocarpus curvipes
Thysanocarpus elegans [Benth. n'existe pas = F. & M.] = Thysanocarpus curvipes
Thysanocarpus laciniatus acc
Thysanocarpus radians acc
Thysanocarpus radians [var.] montanus= Thysanocarpus radians

Smelowskia americana acc
Smelowskia calycina var. americana [pas (Rybd.)]= Smelowskia americana
Smelowskia calycina var. media = Smelowskia media
Smelowskia calycina subsp. calycina var. media = Smelowskia media
Smelowskia calycina (Desv.) C.A. Meyer [= (Stephan) C.A. Meyer] = acc [ms pas en AN - redéterminer les spécimens] [ne pas annoter svp]
Smelowskia calycina var. integrifolia = Smelowskia porsildii

**Comment by brouille** [comment]
Smelowskia ovatus M.E. Jones [erreur orthogr.] = Smelowskia ovalis acc
Smelowskia ovalis subsp. congesta Rollins = var. congesta Rollins [pas subsp.] = Smelowskia ovalis

Braya pectinata = Polyctenium fremontii

Arabidopsis glauca = Eutrema salsugineum

Stenophragma thaliana = thalianUM = Arabidopsis thaliana
Sisymbrium thalianum = Arabidopsis thaliana

Arabidopsis pumila = Olimarabidopsis pumila

Il reste à composer avec Arabidopsis mollis [nom acc]

**Comment by brouille** [comment]
Arabidopsis mollis = Crucihimalaya bursifolia
modification: 
Schivereckia podolica = Draba podolica

**Comment by herbier** [comment]
27177  correction n'apparaît pas    le nom scientifique pour étiquette on a "Draba hederifolia Cosson" alors que le nom scientifique accepté est "Graellsia hederifolia subsp. hederifolia"

**Comment by brouille** [comment]
correction faite

**Comment by herbier** [comment]
Smelowskia americana Rybd. lorsque mets ce nom j'obtiens la fiche 27227  qui ne correspond pas au nom accepté        

Pour  Smelowskia media   j'obtiens la fiche  27228 qui présente la même problématique 

NB: manque nom sp: Draba porsildii G.A. Mulligan X Draba ???? Liljebl.
  =  Draba porsildii G.A. Mulligan (2n = 32) X Draba nivalis Liljebl. (2n = 16)

**Comment by brouille** [comment]
Smelowskia americana acc added

 Smelowskia media : il existe une fiche pour cette espèce: 27229 - quand tu veux obtenir un résultat précis, il faut metttre  =Smelowskia media dans la recherche
Quand j'ai cherché, j'avais 3 résultats : il faut regarder les trois

Draba nivalis × Draba porsildii acc
