### ISSUE TITLE
États du Brésil

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2499]
117358
État : Minas Gerais

il serait bon d'ajouter les états du Brésil étant donné le nombre de spécimens que nous avons
Luc

**Comment by geoffreyhall** [comment]
Tous les états brésiliens sont dans le système, mais pas le niveau administratif inférieur (5569 municípios, dans 26 états); parmi les 1057 fiches du Brésil, 482 ne se sont pas faites attribuées d'état, souvent parce que la saisie est partielle.
Geoff
