### ISSUE TITLE
New Taxon famille des brassiceae 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2508]
Arabis fendleri (Wats.) Greene

Arabis collina (Ten.)...europe

Arabis boryi  Boiss.DC. var. castellana F.Q. et Sennen...europe

Arabis brassicaeformis Wallroth Sched....europe

Arabis cebennensis DC.....europe

Cardaminopsis halleri (L.) Hayek...europe

Arabis halleri L. var. trachytica Fritsch...europe

Arabis hirsuta (L.) Scop. var. subalpstris Ahlfvengr.....europe

Arabis hirsuta Scop.    A. sagittata DC. var. exauriculata Willk. et Lge...europe

Arabis hirsuta Scop. var. sagittata DC....europe

Arabis hirsuta Scop.    B. pubigera Jord.....europe

Arabis hirsuta (L.) Scop. v. glabra ..europe

Arabis hirsurta All....europe

Arabis hirsurta (L.) Scop. var. glaberrima Wahlenb.....europe

Arabis saxatilis All....europe

Arabis nova Vill. = A. saxatilis All.....europe

Arabis serrata Fr. et Sav.

Arabis serrata Fr. et Sav. var. japonica Ohwi...europe

Arabis sessilifolia Gaud....europe

Arabis sagittata DC. ..europe

Arabis sagittata DC.   A. virgata       Turritis multiflora Lapeyr.

Arabis sagittata DC.       A. vulgaris Lyman.  

Arabis serpyllifolia Vill.....europe

Arabis soyeri Ruter...europe

Arabis scabra All.

Arabis stricta Huds......europe

Arabis suecica....europe

Arabis turrita L...europe

Arabis turrita L.       Turritis ochroleuca Lamk 

Arabis verna All. (Boiss)

Arabis verna R. Brown.....europe

Arabis vochinensis Sprengel....europe

Arabis hispida Mygind....europe

Arabis incana D.C....europe

Arabis jacquiniana J.Beck.....europe

Arabis muralis Bert...europe

Arabis muricola Jord.

Diane Fournier

**Comment by brouille** [comment]
Arabis fendleri = Boechera fendleri

Arabis collina acc

Arabis boryi var. castellana = unpublished = Murbeckiella boryi

**Comment by brouille** [comment]
Arabis brassicaeformis = Arabis brassiciformis [selon bd] = Fourraea alpina

Arabis cebennensis = Arabidopsis cebennensis
Cardaminopsis halleri = Arabidopsis halleri subsp. halleri
Arabis halleri var. trachytica Fritsch = Arabidopsis halleri subsp. halleri

**Comment by brouille** [comment]
Arabis hirsUta acc [fiche 940]
Arabis hirsuta var. subalpestris = Arabis hirsuta
Arabis hirsuta var. glaberrima acc
Arabis hirsuta var. glabra = Arabis hirsuta var. glaberrima
Arabis hirsuta var. sagittata DC [ = (Bertoloni) de Candolle] = Arabis sagittata

**Comment by brouille** [comment]
Arabis saxatilis = Arabis nova subsp. nova
Arabis nova acc
Arabis serrata acc [Asie]
Arabis serrata var. japonica = Arabis serrata [Asie]
Arabis sessilifolia Gaud[in] [ne semble pas exister] = Arabis hirsuta subsp. sessilifolia Gaudin = Arabis hirsuta
Arabis sagittata acc
[Arabis sagittata DC. A. virgata Turritis multiflora Lapeyr.
Arabis sagittata DC. A. vulgaris Lyman. - dans les 2 cas, noms à mettre en note de dét.]
Arabis serpyllifolia = Arabis serpillifolia acc
Arabis soyeri acc
Arabis scabra acc
Arabis stricta = Arabis scabra

Arabis suecica = Arabidopsis suecica

Arabis turrita = Pseudoturritis turrita

**Comment by brouille** [comment]
[Arabis turrita L. Turritis ochroleuca Lamk ; note de détermination] = Pseudoturritis turrita

Arabis verna All. (Boiss) : n'existe pas avec ces auteurs - valider que semblable à R. Brown ; si oui = Arabis verna (Linnaeus) R. Brown acc
Arabis vochinensis acc
Arabis jacquiniana Beck [mal épelé] = Arabis jacquinii Beck = Arabis soyeri subsp. subcoriacea
Arabis muralis = Arabis collina
Arabis muricola = Arabis collina

Arabis hispida = Arabidopsis lyrata subsp. petraea

NB
Arabis incana DC : n'existe pas ds bd avec cet auteur [il faudra déterminer le spécimen]

**Comment by herbier** [comment]
Fiche 27530  Arabis  serpyllifolia Villars est écrit de façon différente
on a Arabis serpillifolia et Arabis  serpyllifolia sur la fiche

**Comment by brouille** [comment]
corrigé Arabis serpillifolia
Merci 
LB
