### ISSUE TITLE
New Taxon Nova Scotia et Saint-Pierre et Miquelon

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2522]
224269, 224470 2e det.: Alnus viridis (Chaix) DC. var. sinuata Regel
224467, 224468 3e det.: Alnus viridis (Chaix) DC. var. sinuata Regel
224500: Viola adunca Sm. var. minor (Hook.) Fern.

Claude Lucier 9 février 2018

**Comment by brouille** [comment]
Alnus viridis var. sinuata = Alnus alnobetula subsp. sinuata [ms pas pour ces spécimens]
Viola adunca var. minor = Viola labradorica
