### ISSUE TITLE
New Taxon (projet 383)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2549]
215554: Aralia racemosa f. foliosa Vict.

Claude Lucier 30 mars 2018

**Comment by brouille** [comment]
Aralia racemosa f. foliosa Vict. nom. ined.
il s'agissait sans doute d'un nom préliminaire (nom. ined.) car il est impossible que Victorin et al. aient nommé cette plante f. foliosa Vict. car ce nom a d'abord été publié en 1940 sous var. foliosa Vict. & Rousseau, puis sous f. foliosa (V. & R.) Scoggan en 1978
