### ISSUE TITLE
Schoenoplectus x steinmetzii

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2551]
Originally Scirpus steinmetzii Fernald. We have a topotype at MT collected any Steinmetz. Taxon changes statut by Smith in 1997 to Schoenoplectus x steinmetzii (= Schoenoplectus heterochaetus x Sch. tabernaemontani)

**Comment by brouille** [comment]
Scirpus ×steinmetzii = Schoenoplectus ×steinmetzii
