### ISSUE TITLE
New Taxon (Chine 1988)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2559]
232179: Quercus toumeyi Sargent
232223: Selaginella uncinata (Desvaux) Spring
232224: Cynanchum auriculatum Royle ex Wight
232225: Galinsoga parviflora Cavanilles
232226: Cornus multinervosa (Pojark.) Q.Y. Xiang
232227: Ligustrum sinense Loureiro
232228: Daphniphyllum macropodum Miquel
232229: Vaccinium urceolatum Hemsley
232230: Carpinus fargesii Franchet
232231: Lysimachia trientaloides Hemsley
232232: Viburnum cylindricum Buch.-Ham ex D. Don
232233: Ilex fragesii Franchet
232234: Staphylea holocarpa Hemsley
232235: Ampelopsis megalophylla Diels & Gilg
232237: Lyonia ovalifolia (Wallich) Dude var. hebecarpa (Franchet ex Forbes & Hemsely) Chun
232238: Pittosporum podocarpum Gagnepain
232239: Perrottetia racemosa (Oliver) Loesener
232240: Quercus serrata Thunberg
232241, 232246, 232252, 232254, 232256: 1 ière det.: Actinidia
212241: 2e det.: Actinidia kolomikta (Maxim. & Ruprecht) Maxim. var. gagnepainii (Nakai) H.L. Li
232242: Vitis wilsonii Veitch 
232243: Rubus aff. setchuenensis Bur. & Franchet
232244: Spiraea japonica L. f. var. acuminata Franchet
232245: Cyathula officinalis Kuan
232246: 2e det.: Actinidia callosa Lindley var. henryi Maxim.
232247: Taxillus setchuenensis (Lecompte) Danser
232248: Symplocos (sans autorité)
232249: Dumasia villosa DC.
232250: Lasianthus longicauda J.D. Hooker
232251: Gaultheria nummularia D. Don
232252, 232254: 2e det.: Actinidia polygama (Siebold & Zuccarini) Maxim.
232253: Hemsleya chinensis Cogniaux ex forbes & Hemsley
232255, 232257: Lepisorus macrosphaerus (Baker) Ching var. asterolepis (Baker) Ching
232256: 2e det.: Actinidia venosa Rehder 
232258: Neanotis hirsuta (L. f.) W.H. Lewis
232259: Triplostegia glandulifera Wallich in DC.
232260: Rubus lambertianus Ser. var. glaber Hemsley
232261: Viburnum adenophorum W.W. Smith
232262: Cucubalus baccifera L.
232263: Viburnum betulifolium Batalin

Claude Lucier 20 avril 2018

**Comment by brouille** [comment]
Quercus toumeyi acc
Selaginella uncinata acc
Cynanchum auriculatum acc
Galinsoga parviflora acc
Cornus multinervosa acc
Ligustrum sinense acc

**Comment by brouille** [comment]
Daphniphyllum macropodum acc
Vaccinium urceolatum acc
Carpinus fargesii = Carpinus viminea var. viminea
Lysimachia trientaloides = Lysimachia paridiformis var. stenophylla
Viburnum cylindricum acc
Ilex fargesii acc
Staphylea holocarpa acc
Ampelopsis megalophylla = Nekemias megalophylla

**Comment by brouille** [comment]
Lyonia ovalifolia var. hebecarpa acc
Pittosporum podocarpum acc
Perrottetia racemosa acc
Quercus serrata Thunberg = nom. illeg. hom. = Quercus serrata Murray
Actinidia acc
Actinidia kolomikta var. gagnepainii = Actinidia kolomikta
Vitis wilsonii [mal épelé] = Vitis wilsoniae
Rubus setchuenensis acc
Spiraea japonica var. acuminata acc
Cyathula officinalis acc
Actinidia callosa var. henryi acc
Taxillus setchuenensis [mal épelé] = Taxillus sutchuenensis
Symplocos acc
Dumasia villosa acc
Lasianthus longicauda [mal épelé]= Lasianthus longicaudus = Lasianthus japonicus subsp. longicaudus
Gaultheria nummularia D. Don [aut. : DC.] = Gaultheria nummularioides D. Don
Actinidia polygama acc
Hemsleya chinensis acc
Lepisorus macrosphaerus var. asterolepis = Lepisorus macrosphaerus
Actinidia venosa acc
Neanotis hirsuta acc
Triplostegia glandulifera acc
Rubus lambertianus var. glaber acc
Viburnum adenophorum = Viburnum betulifolium
Cucubalus baccifera = Silene baccifera
Viburnum betulifolium acc
