### ISSUE TITLE
Bolboschoenus robustus (Pursh) Sojak

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2561]
One specimen from Nova Scotia annotated by Galen Smith as B. robustus; other specimens annotated as hybrids with B. maritimus. Bolboschoenus maritimes (L.) Palla x B. robustus (Pursh) Sojak.

**Comment by brouille** [comment]
Bolboschoenus robustus acc
[je note que ds FNA, Smith excluait ce taxon de NS (au N de l'aire)- est-ce que la dét. est OK?
ms il notait des hybrides!]
Bolboschoenus matirimus × Bolboschoenus robustus acc
