### ISSUE TITLE
County NV, USA

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2579]
233492-3
Ormsby County, Nevada
https://en.wikipedia.org/wiki/Ormsby_County,_Nevada

Luc

**Comment by brouille** [comment]
Hungary regions (niveau 2): il faut refaire svp

**Comment by geoffreyhall** [comment]
Ormsby County, Nevada was a county of Nevada from 1861 until 1969; it contained Carson City, the county seat, and later, the state capital, founded two years earlier; on April 1, 1969, Ormsby County and Carson City officially merged as the Consolidated Municipality of Carson City (<https://en.wikipedia.org/wiki/Ormsby_County,_Nevada>).  Nom ajouté comme synonyme, fiches mises à jour.
Geoff
