### ISSUE TITLE
New Taxon(prêt MT18-15-Solidago)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2586]
233890: Solidago elliptica Ait.
233904: Solidago sempervirens L. X canadensis L.

233905, 233906, 233907, 233908, 233909, 233910, 233911, 233912, 233913, 233914, 233915, 233916: Solidago missouriensis Nutt. var. fasciculata Holz

Claude Lucier 1 juin 2018

**Comment by brouille** [comment]
Solidago elliptica Ait. = Solidago latissimifolia
Solidago sempervirens × Solidago canadensis : svp inscrire Solidago canadensis × Solidago sempervirens [nom original en note] [fiche 24361]
Solidago missouriensis var. fasciculata = Solidago missouriensis
