### ISSUE TITLE
motification d'Herbier

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2592]
Luc -  il y a deux fiches, 102135 et 102136, où c'est indiqué que  les spécimens se trouvent à MT. Nous n'avons pas ces spécimens dans la chemise. Selon moi, ils se trouvent plutôt ailleurs, notamment à GH. C'est moi qui a fait le relevé selon l'information - donc j'ai fait l'erreur. D'ailleurs, les annotations me disent que se sont des spécimen empruntés de GH.

**Comment by brouille** [comment]
maintenant dataset elsewhere

Il y avait pourtant des nos MT ds No de spécimen - je les ai enlevés jusqu'à ce qu'on trouve des spécimens à MT

Luc
