### ISSUE TITLE
F. Louis-Marie c.s.c. vs P. Louis-Marie

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2632]
Geoff

Spécimen 237006
Il est clair que sur ce spécimen on fait allusion à un frère Louis-Marie: FF. Lucien et Louis-Marie, c.s.c.
Or quand on entre Fr. Lucien = Lucien Lévesque, on obtient: Lévesque, Lucien, Fr.; Louis-Marie, Pr.

Est-il possible qu'il y ait 2 Louis-Marie, un Frère et un Père
Ou alors, louis-Marie a été frère avant de devenir père?
Svp, démêler cela
Luc

**Comment by brouille** [comment]
Mais en 1942, Père Louis-Marie était déjà père  - donc?

**Comment by geoffreyhall** [comment]
Le Père Louis-Marie (1896-1978) était trappiste (ordre cistercien de la Stricte Observance), o.c.s.o., tandis que nos 20 récoltes des FF. Lucien & Louis-Marie (tous à Nominingue en 1942 sauf 237006 en 1915 - mais date originale en 1942, à corriger) indiquent la congrégation de Sainte-Croix, c.s.c.  Je conclus qu'il s'agit de deux individus distincts et j'ai modifié la base de données pour en tenir compte
Geoff
