### ISSUE TITLE
Scirpus atrovirens Muhl. f. proliferous Hermann

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2683]
Luc - I wonder why the species epithet is followed by Muhlenberg?????

**Comment by brouille** [comment]
Scirpus atrovirens Muhl. f. proliferous Hermann : Muhl. est tout simplement une erreur de la part du déterminateur
Scirpus atrovirens f. proliferus F.J. Hermann = Scirpus atrovirens × Scirpus hattorianus

voir https://www.biodiversitylibrary.org/item/14510#page/85/mode/1up pour descr orig
