### ISSUE TITLE
Personal herbarium, California

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2684]
240755, 240757
The Frank W. Hubby Herbarium
[presented to the California Academy of Sciences by the Ojai Branch of the VEntura County Library, January 1949]

ajouter à historique svp
Luc

**Comment by brouille** [comment]
242411
Kellogg-Herbarium Americanum
John H. Kellogg

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés et fiches mises à jour
