### ISSUE TITLE
Collection to add

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2730]
243189 
RCAM [Rutgers university Herbarium]
http://sweetgum.nybg.org/science/ih/herbarium_details.php?irn=125837

Luc

**Comment by geoffreyhall** [comment]
RCAM ajouté (RCAM = Biology Department, Rutgers University, ca. 1960-2001, 10 000 spécimens, défunt), mais CHRB est sans doute l'herbier à l'Université Rutgers où Chrysler et Minton ont déposé la récolte (CHRB = Department of Plant Biology and Pathology, Rutgers University, 1881-2019, 151 000 spécimens, actif)
Fiche mise à jour
Geoff
