### ISSUE TITLE
US county missing

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2737]
243675 Solidago
Sedgiwck Co. Colorado
www.colorado.gov/sedgwickcounty
https://en.wikipedia.org/wiki/Sedgwick_County,_Colorado

Luc

**Comment by brouille** [comment]
243762
Montana: Valley County
https://en.wikipedia.org/wiki/Valley_County,_Montana

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés et fiches mises à jour.
Geoff
