### ISSUE TITLE
New Taxon (Taxon 4638 à vérifier)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2780]
Selon Remarque de nom scientifique: NY type annotated Trichostomum cylindricum sweetgum.nybg.org/vh/specimen.php?irn=525279
www.tropicos.org/Name/35132229
emuweb.fieldmuseum.org/botany/taxDisplay.php?irn=434940
Nom accepté: Trichodon cylindricus
Lucie

**Comment by brouille** [comment]
Trichostomum cylindricum = Trichodon cylindricus fide BFNA 
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242443773

je ne vois pas où est le problème car le nom acc est Trichodon
Luc
