### ISSUE TITLE
Région du Chili

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2803]
230743
Région du Chili [niveau province]
Aysén del General Carlos Ibáñez del Campo Region [Aysén Region]
https://es.wikipedia.org/wiki/Regi%C3%B3n_de_Ays%C3%A9n_del_General_Carlos_Ib%C3%A1%C3%B1ez_del_Campo
https://en.wikipedia.org/wiki/Ays%C3%A9n_Region
Luc

**Comment by geoffreyhall** [comment]
Nom ajouté à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
