### ISSUE TITLE
Scirpus rubricosus Fernald

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2806]
Luc - Il faut inscrire ce nouveau nom de Fernald. J'ai trouvé une dizaine de spécimens portant ce nom sur l'étiquette dans la chemise «d'indéterminées et espèces reliées» à la fin du classement des chemises.

**Comment by brouille** [comment]
Scirpus rubricosus  = S. cyperinus fide FNA
[S. Hay croît que ce taxon est valable ms demanderait une étude - disposition  préliminaire]
