### ISSUE TITLE
New Taxon(+ vieux spécimen)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2811]
247576: Desmoschoenus spiralis Hook f.

Claude Lucier 26 avril 2019

**Comment by brouille** [comment]
Desmoschoenus spiralis = Ficinia spiralis
Scirpus spiralis = nom. illeg. = Ficinia spiralis
Ce spécimen n'est pas un type car le type est de A. Richard
Luc
