### ISSUE TITLE
New Taxon (Scripus)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2815]
234960: Scirpus atrovirens Willd. f. sychnocephalus (S.N. Cowles) S.F. Blake
235433 : Scirpus atrovirens Willd.  var. georgianus (Harper.) Fern. f. cepahlanthus Fern.
239668: Scirpus atrovirens Willd. var. atrovirens
239674: Scirpus georgianus Harper f. viviparus Vict.

Claude Lucier 1 mai 2019

**Comment by brouille** [comment]
Scirpus atrovirens f. sychnocephalus = Scirpus atrovirens
Scirpus atrovirens var. georgianus f. cephalanthus = Scirpus atrovirens
Scirpus atrovirens var. atrovirens = Scirpus atrovirens
Scirpus georgianus f. viviparus Vict. = [n'existe pas: Scirpus atrovirens f. viviparus Vict.]
