### ISSUE TITLE
Acronymes d'herbier pour Holotype à et Histoire

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2840]
Les acronymes d'herbier histoire devraient être automatiquement ajoutés aussi pour Holotype à

227134 : Holotype à : VPI
vérifier si c'est aussi ds histoire

Il faut ajouter LL à histoire et Holotype à

Luc

**Comment by brouille** [comment]
250730
Ajouter acronyme MBM
Prefeitura Municipal de Curitiba, Museo Botânico Municipal
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125352

Luc

**Comment by brouille** [comment]
250751
Poland
WA 
Herbarium Universitatis Varsaviensis
Luc

**Comment by brouille** [comment]
250765
Herbier A.F. Jeanjean

Luc

**Comment by brouille** [comment]
250775
Herbier L. Girod
Histoire

Luc

**Comment by brouille** [comment]
250801
Herbarium Louis Bruneau
Histoire
Luc

**Comment by brouille** [comment]
250827
Herbarium Vadense = Wageningen WUR
Cet herbier est probablement fusionné à AMD - vérifier

Luc

**Comment by brouille** [comment]
250856
Turku University Herbarium TUR
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126877
history
Luc

**Comment by brouille** [comment]
250867
Herbarium Scandinavicum

Luc

**Comment by brouille** [comment]
250874
Musée d'histoire naturelle de Fribourg (Suisse) - Herbarium Helveticum
NHMF
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=160109
et
Herbier Jaquet
Luc

**Comment by brouille** [comment]
250882
Herb. Musei Hist. Natur. Vindob.
Hongrie?
Je n'ai pu déterminer quel herbier c'est 
Luc

**Comment by brouille** [comment]
250888
herb. E.F. Linton
[BM]
Luc

**Comment by brouille** [comment]
250890
Société Vogéso-Rhénane
STR [Strasbourg]
herbier.unistra.fr/herbier-de-strasbourg/centuries-et-collections-des-societes/la-societe-vogeso-rhenane/#c43058
Luc

**Comment by brouille** [comment]
250923
Herb. Osw. Sandberg

LB

**Comment by brouille** [comment]
250926
Herbarium C. Simon
étiquette écrite en allemand, ms Flora Gallica
LB

**Comment by brouille** [comment]
250929
Herbier G. et M. Tardieu

LB

**Comment by brouille** [comment]
250937
TCD
Herb. Collegii SS. Trin., Dublin
Luc

**Comment by brouille** [comment]
251204
Herbarium of Kate Furbish [donné GH]

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
