### ISSUE TITLE
District [MRC] Europe

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2842]
250747
Slovakia
District : Nové Mesto nad Váhom
https://en.wikipedia.org/wiki/Nov%C3%A9_Mesto_nad_V%C3%A1hom_District

250748
Slovakia
District : Piešťany
https://en.wikipedia.org/wiki/Piešťany_District

250749
Czech Republic
District : Přerov
https://en.wikipedia.org/wiki/P%C5%99erov_District

**Comment by brouille** [comment]
250750
Austria : provinces
Quand je sélectionne Styria, j'obtiens Steiermark
Or les deux sont des provinces distinctes d'Autriche - rétablir Styria

distr. Deutschlandsberg
https://en.wikipedia.org/wiki/Deutschlandsberg_District

Luc

**Comment by brouille** [comment]
250752
Poland
Krakow County
https://en.wikipedia.org/wiki/Krak%C3%B3w_County

Luc

**Comment by brouille** [comment]
250754
Austria
prov. Vorarlberg
ajouter: District Bregenz
https://en.wikipedia.org/wiki/Bregenz_District

Luc

**Comment by brouille** [comment]
250827
Netherlands: Province Overijssel
https://en.wikipedia.org/wiki/Overijssel
250828
North Holland = Noord-Hollands
https://en.wikipedia.org/wiki/North_Holland
Luc

**Comment by brouille** [comment]
250847
India: Himachal Pradesh
District Shimla
https://en.wikipedia.org/wiki/Shimla
Luc

**Comment by brouille** [comment]
250988
District Uckermark
Brandenburg, Germany
https://en.wikipedia.org/wiki/Uckermark_(district)
Luc

**Comment by geoffreyhall** [comment]
(1) 250750: dans la bD,  les 9 états sont représentés par leurs noms en allemand; "Steiermark" est le nom en allemand pour "Styria" (le nom en anglais); changer tous les noms n'est pas nécessaire (NB: le district de "Deutschlandsberg" est disponible dans la liste déroulante, si on sélectionne l'état de "Steiermark").
(2) 250827 + 250828: dans la bD, "Netherlands" (Kingdom of the Netherlands) est composé de 3 territoires + 1 état (Aruba, Curaçao, Netherlands, Sint Maarten); les provinces de l'état qui s'appelle "Netherlands", incluant "Overijssel" et "North Holland", se trouvent dans le 3e niveau de divisions administratives (=MRC au Qc).
(3) Noms nécessaires ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
