### ISSUE TITLE
Europe: Jersey

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2847]
250845
Dans la liste des pays d'Europe de la bd, tu as placé Jersey comme une province de United Kingdom

Mais en fait, Jersey est indépendant de UK, bien que sous la couronne de la Reine

https://en.wikipedia.org/wiki/Jersey

Il faut donc déplacer Jersey de la liste des provinces à celle des pays d'Europe.
Luc

**Comment by geoffreyhall** [comment]
Selon <https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country>, Jersey n'est pas un pays comme le Canada ou le Bélize, mais un "crown dependency".  On a suivi l'idée ici <https://en.wikipedia.org/wiki/Administrative_geography_of_the_United_Kingdom> qui l'incorpore au R.-U.  Les paroisses sont ici <https://en.wikipedia.org/wiki/Parishes_of_Jersey>.
Geoff
