### ISSUE TITLE
Portugal: subdivisions à refaire

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2848]
Geoff

Aucune des régions actuelles du Portugal ne sont dans la liste déroulante. Il n'y a rien à comprendre ou à faire avec cette liste. Voir:
https://en.wikipedia.org/wiki/Subdivisions_of_Portugal

Luc

**Comment by geoffreyhall** [comment]
La bonne liste se trouve au site suivant <https://fr.wikipedia.org/wiki/Districts_du_Portugal>.  La base de données semble être conforme avec ces divisions.
Geoff

**Comment by brouille** [comment]
Les districts sont une subdivision des régions. LEs régions devraient être retrouvées sous Province, ce qu'elles ne sont pas. Les districts devraient se trouver sous MRC, districts, etc.

Luc
