### ISSUE TITLE
New Taxon  cannabaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2852]
Celtis crassifolia Lam  ..........   Québec  USA

Celtis tenuifolia Nutt. .............Ontario

Celtis occidentalis L. var.canina (Raf.) Sarg......USA

Celtis occidentalis  L. var.  georgiana (Small) H.E.Ahles  ....USA

Celtis occidentalis L. var.canina (Raf.) Sarg.....USA

Celtis occidentalis  L. var.  georgiana (Small) H.E.Ahles  ....USA

 Celtis pumila Pursh....USA
 
 Celtis canina Raf......USA
 
Celtis pumila var. georgiana (Small) Sarg. .....USA

Celtis tenuifolia var. georgiana (Small) Fernald & B.G.Schub.......USA

Celtis georgiana Small...USA

Celtis laevigata Willd......USA

Celtis laevigata Willd. Var. texana Sarg......USA

Celtis mississippiensis Bosc.....USA

Celtis smallii Beadle   USA

Celtis reticulata Torr.......USA

Celtis douglassii Planch....USA

Celtis pubescens (H.B.K.) Spr.....Amérique du sud

Celtis anfractuosa Liebm.......A du S

 Celtis spinosa Spreng. var. weddeliana (Planchon) Baehni.....AduS
 
Celtis australis.....Asie

Celtis biondii Pampanini...Asie

Celtis bungeana Blume...Asie

Celtis bungeana Blume var. jessoensis Kudo...Asie

Celtis caucasica Willd...Asie

Celtis julianae Schneider...asie

Celtis sinensis Persoon...Asie

Celtis sinensis Person var. japonica

Celtis tournefortii Lam.....Europe Nakai....Asie

Diane Fournier

**Comment by brouille** [comment]
Celtis crassifolia = Celtis occidentalis
Celtis pumila = Celtis occidentalis
Celtis canina = Celtis occidentalis
Celtis occidentalis var. canina = Celtis occidentalis

Celtis tenuifolia acc
Celtis georgiana = Celtis tenuifolia
Celtis occidentalis var. georgiana = Celtis tenuifolia
Celtis pumila var. georgiana = Celtis tenuifolia
Celtis tenuifolia var. georgiana = Celtis tenuifolia

Celtis laevigata acc
Celtis laevigata var. texana = Celtis laevigata
Celtis mississippiensis = Celtis laevigata
Celtis smallii = Celtis laevigata

Celtis reticulata acc
Celtis douglasii [un seul s] = Celtis reticulata

Celtis pubescens = Celtis iguanaea
Celtis anfractuosa = Celtis iguanaea
Celtis spinosa var. weddeliana = Celtis iguanaea

Celtis australis acc
Celtis biondii acc
Celtis bungeana acc
Celtis bungeana var. jessoensis = Celtis jessoensis
Celtis caucasica acc
Celtis julianae acc
Celtis sinensis acc
Celtis sinensis var. japonica = Celtis sinensis
Celtis tournefortii Lamarck [ii n'y a pas Nakai en Asie - je ne sais ce que le spécimen d'Asie représente] acc
