### ISSUE TITLE
New Taxon  Famille des cannabaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2859]
Celtis rugosa n. sp......USA

Celtis wightii var. consimilis Gagnep.....Asie

Celtis philippensis Blanco...Océanie

Celtis rubrovenia, Elm......Océanie

Celtis harperi Horne.......Oceanie

Celtis tyfe Wightii Planch.....Océanie

Celtis mildbraedii Engl.    Afrique

Celtis pumila var. deamii...cultivées 

Pteroceltis tartarinowii Maximowicz...Asie

Gironniera subaequalis Pl. .......Asie

Gironniera celtidifolia Gaud....Oceanie

Trema floridana Britton.......USA

Trema mollis lour......USA

Trema rufescens Blume..A du S

Trema micrantha (Linnaeus) Blume...A du S

Trema velutina (Planch.) Blume	....Asie

Trema cannabina Lour.	...Asie

Trema philippinensis Merr....Océanie

Trema amboinensis (Willd.) Blume ....Océanie

Trema aspera (Brongn.) Blume ......océanie

Trema cannabina Lour. Var.scabra (Bl.) de Wit......Océanie

Diane Fournier

**Comment by brouille** [comment]
Celtis rugosa Rydberg nom. illeg. = Celtis reticulata [à valider]
Celtis wightii var. consimilis = Celtis philippensis
Celtis tyfe [= type?] Wightii = Celtis philippensis
Celtis rubrovenia acc
Celtis harperi acc
Celtis mildbraedii acc
Celtis pumila var. deamii = Celtis occidentalis

Pteroceltis tatarinowii [pas de r à tar] : acc

Gironniera subaequalis acc
Gironniera celtidifolia acc

Trema floridana [floridanum?] = Trema micranthum
Trema mollis = Trema micranthum
Trema micranthum acc
Trema rufescens = Trema micranthum
Trema velutinum = Trema tomentosum
Trema cannabinum acc
Trema cannabinum var. scabrum
Trema philippinense = Trema eurhynchum
Trema amboinense acc
Trema asperum acc
Trema cannabinum var. scabrum [inconnu]
