### ISSUE TITLE
Famille cannabaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2861]
Sur la fiche 3009 le nom scientifique pour l'étiquette ne correspond pas au nom scientifique accepté   (Trema micranthum on a Trema mollis Blume)
Diane Fournier

**Comment by herbier** [comment]
Trema velutina devient Trema tomentosum mais ce nom n'est pas dans la base

**Comment by brouille** [comment]
30079 Trema micranthum acc
Trema velutina : Trema velutinum fiche 20080 = Trema tomentosum [ajouté]
