### ISSUE TITLE
 Famille des cannabaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2862]
Humulus scandens (Lour.) Merr.   .........Ontario

Humulus americanus Nutt......manitoba    usa

Humulus lupulus Neo-mexicanus Ckll......usa

Humulus neomexicanus Nels. & Ckll....usa

Humulus lupulus L. var. neomexicanus Nels. &  Ckll.........usa

Famille terminée

Diane Fournier

**Comment by brouille** [comment]
Humulus scandens acc
Humulus americanus = Humulus lupulus var. lupuloides
Humulus lupulus Neo-mexicanus = Humulus lupulus var. neomexicanus acc
Humulus neomexicanus = Humulus lupulus var. neomexicanus
