### ISSUE TITLE
New Taxon    Blechnaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2865]
Stenochlaena smithii (Fée)    océanie

Stenosemia aurita  Presl......océanie

Stenochlaena palustris (Burm. F.) Bedd.......océanie

Blechnum lanceola Sw.....Océanie.....AduS

Blechnum longifolium H.B.K.....AduS

Blechnum meridense (Klf.) Mett.......adus

Blechnum schomburgkii (Klotzsch) C. Chr.....AduS

Blechnum serrulatum Desv.........AduS

Blechnum jamaicense (Broadh.) C. Chr. .........Antilles

Blechnum polypoioides (Sw.) Kuhn ....Antilles

Blechnum blechnoides (Lag) C. Chr.

Blechnum intermedium Link......Antilles

Diane Fournier

**Comment by brouille** [comment]
Stenochlaena smithii = Lomariopsis lineata
Stenosemia aurita = Tectaria aurita
Stenochlaena palustris acc
Blechnum lanceola acc
Blechnum longifolium Kunth = Blechnum gracile
Blechnum meridense (Klf.) Mett = Blechnum meridense (Klotzsch) Mett. nom. illeg. = Blechnum meridense Klotzsch

**Comment by brouille** [comment]
Blechnum schomburgkii = Lomariocycas schomburgkii
Blechnum serrulatum Desv : n'existe pas= Blechnum serrulatum Rich. (Amer. S.) fiche 18801 = Telmatoblechnum serrulatum
Blechnum jamaicense = Austroblechnum jamaicense
Blechnum polypoDioides (Sw.) Kuhn = nom. illeg. (homonyme ultérieur) = Lomaridium fragile
Blechnum blechnoides  (Lagasca) C. Christensen = nom. illeg. = Blechnum polypodioides
Blechnum intermedium = Blechnum gracile
