### ISSUE TITLE
New Taxon famille des cannabaceae et blechnaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2868]
Celtis monoica Hemsl...... Amérique centrale

Mirandaceltis....Amérique centrale

Trema micrantha (L.) Blume var. floridana (Britton) Standl. & Steyerm. (T.mollis (Humb. & Bonpl.) Blume).......Amérique centrale

Trema micranthum (L.) Blume var. Strigillosa (Lund.) Standl. & Steyerm.   ....Amérique centrale

Blechnum fragile.....amérique centrale

Lomaria boryana (Sw.) Willd....Amérique du sud

Lomaria procera Spreng...Amérique du sud

Blechnum tabulare (Thbg.) Kuhn.......Afrique

Lomaria attenuata...Afrique

Plagiogyria matsumureana Makino.....Asie

Plagiogyria adnata (Bl.) Bedd....Asie

Blechnum alpinum ....Oceanie

Lomaria alpina ....Océanie

Lomaria fluviatilis Spreng....Oceanie

Lomaria membranacea Colenso.....Océanie

Lomaria capensis Willd ....océanie

Lomaria discolor Willd.....Océanie

Lomaria lamceolata Spr......Océanie

Lomaria patersoni Spr....Océanie

Blechnum onocleoides ...USA. Photo de la plante

Blechnum serrulatum Michx....USA

Blechnum diversifolium Mett.....usa

Blechnum boreale Lois........Colombie britannique

Lomaria spicant (Desv.)....Colombie britannique

Blechnum auriculatum.......A du Sud

Blechnum australe...A du Sud

Blechnum (Klf.) Mett....Adu sud

Blechnum distans Prsl. ....A du sud

Blechnum fraxineum (Willd.)...A du sud

Blechnum glandulosum Lk....A du sud

Diane Fournier

**Comment by brouille** [comment]
Celtis monoica = Aphananthe monoica
Mirandaceltis = Aphananthe
la seule espèce de ce genre est Mirandaceltis monoica = Aphananthe monoica - annoter à ce nom svp

Trema micranthUM var. floridanUM = Trema micranthum
Trema micranthum var. strigillosUM =  Trema micranthum

**Comment by brouille** [comment]
Palgiogyriaceae
Plagiogyria matsumureana acc
Plagiogyria adnata acc

Blechnaceae
Blechnum fragile = Lomaridium fragile
Lomaria attenuata = Lomaridium attenuatum
Blechnum onocleoides = Lomaridium fragile

Lomaria procera = Parablechnum procerum
Lomaria capensis = Parablechnum capense

Lomaria boryana = Lomariocycas tabularis
Blechnum tabulare = Lomariocycas tabularis

Lomaria fluviatilis = Cranfillia fluviatilis

Blechnum alpinum = Austroblechnum penna-marina subsp. alpina
Lomaria membranacea = Austroblechnum membranaceum
Lomaria lanceolata = Austroblechnum lanceolatum
Lomaria patersoni = Austroblechnum patersonii

Lomaria discolor  acc

Blechnum serrulatum = Telmatoblechnum serrulatum fiche 18801

Blechnum diversifolium USA? la plante provient de Nouvelle-Calédonie! en cult.? = Diploblechnum diversifolium

**Comment by brouille** [comment]
Blechnum boreale = Struthiopteris spicant (Linnaeus) Weis
Lomaria spicant = Struthiopteris spicant (Linnaeus) Weis

Blechnum auriculatum acc
Blechnum australe acc
Blechnum distans = Blechnum laevigatum
Blechnum fraxineum = Blechnum gracile
Blechnum glandulosum = Blechnum appendiculatum

NB: Blechnum (Klf.) Mett : il manque le nom d'espèce!
