### ISSUE TITLE
New Taxon Famille des blechnaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2871]
Sadleria hillerandii  x S. cyatheoides...océanie
 
 Woodwardia orientalis Swartz.....asie
 
 Woodwardia unigemmata Nakai...asie
 
 Woodwardia caudata Cav.......Asie
 
 Woodwardia japonica Sw.....asie
 
 Woodwardia orientalis Sw. var. prolifrra (Hk. & Arn.) Ching....Cultivée
 
 Woodwardia spinulosa  Mart. & Gal.....C.B.
 
 Woodwardia aspera Mett.=Doodia aspera R.Br.....océanie
 
 Doodia media Br.....océanie
 
 Doodia cf. media ....océanie
 
 Doodia maxima J. Sm......cultivée
 
 Doodia dives....cultivée
 
 Brainea insignis (Hook.) Sm.....Océanie

Diane Fournier .....fin d'inventaire de cette famille

**Comment by brouille** [comment]
Sadleria cyatheoides × Sadleria hillebrandii  = Sadleria cyatheoides × Sadleria pallida

Woodwardia orientalis acc
Woodwardia unigemmata acc
Woodwardia japonica acc
Woodwardia orientalis var. prolifera = Woodwardia prolifera
Woodwardia spinulosa acc

Woodwardia aspera = Doodia aspera
Woodwardia caudata = Doodia caudata
Doodia dives acc
Doodia media = Doodia cf. media [cf est qualificateur] acc
Doodia maxima acc

Brainea insignis acc
