### ISSUE TITLE
New Taxon famille des selaginellaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2893]
Selaginella spinosa Beauv.....québec

Selaginella bigelovii Underwood...usa

Selaginella arenicola Underwood var. ridellii (Van Eselt.) Tryon...Usa

Selaginella riddellii Van Eseltine....usa

Selaginella arenicola Underw.....usa

Selaginella arenicola Underw. Ssp. acanthanota (Underw.) Tryon....usa

Selaginella floridana Maxon...usa

Selaginella funiformis Van Eseltine.....usa

Selaginella mutica D.C. Eaton...usa

Selaginella cinerascens A. A. Eaton...usa

Selanigella watsonii...usa

Selanigella standleyi Maxon....usa

Selaginella sheldoni Maxon....usa

Selaginella underwoodii Hieron.....usa

Selaginella hansenii Hier.....usa

Selaginella leucobryoides....usa

Selaginella arizonica Maxon...usa

Selaginella ludoviciana A.Br.....usa

Selaginella apoda (L.) Fernald   et Selaginella apoda (L.)Link auteurs différents de ceux acceptés..... usa

Selaginella rhodospora Baker...usa

Selaginella weatherbiana Tryon....usa

Selaginella weatherbiana Tryon, sp.nov. Isotypus (on aurait un isotype)

Selaginella utahensis S. Flowers....usa

Selaginella affinis A.Br.......amérique du sud

Selaginella asperula Spring.....A du Sud

Selaginella bombycina Spring....A du Sud

Selaginella brachylepis Christ ....A du Sud

Selaginella calosticha Spring....A du Sud

Selaginella convoluta Spring...A du sud

Selaginella diffusa (Presl) Spring.....A du Sud

Selaginella erythropus (Mart.) Spring ....A du Sud

Selaginella excurrens Spring...A du Sud

Selaginella filicaulis Sod....A du Sud

Selaginella flagelllata Spring.....A du Sud

Selaginella haematodes Spring.....A du Sud

Selaginella haenkeana Spring ....A du Sud

Selaginella hartwegiana Spring...A du Sud

Selaginella leptoblepharis A.Brown...A du Sud

Selaginella lindigii A. Braun.....A du Sud

Selaginella moritziana Spring .....A du Sud

Selaginella microphylla Spring.....A du Sud

Selaginella mollis A. Braun.....A du Sud

Selaginella montevidensis Hier.........A du Sud

Selaginella pargiana Spring......A du sud

Diane Fournier

**Comment by brouille** [comment]
AN
Selaginella spinosa = Selaginella selaginoides
Selaginella bigelovii acc
Selaginella arenicola acc
Selaginella arenicola var. riddellii = Selaginella arenicola subsp. riddellii
Selaginella riddellii = Selaginella arenicola subsp. riddellii
Selaginella arenicola subsp. acanthOnota = Selaginella acanthonota
Selaginella floridana = Selaginella acanthonota
Selaginella funiformis = Selaginella acanthonota
Selaginella mutica D.C. Eaton ex Underwood acc
Selaginella cinerascens acc
Selaginella watsonii acc
Selaginella standleyi acc
Selaginella sheldoni[i] = Selaginella peruviana
Selaginella underwoodii acc
Selaginella hansenii acc
Selaginella leucobryoides acc
Selaginella arizonica acc
Selaginella ludoviciana acc
Selaginella apoda (L.) Fernald = nom. illeg. = Selaginella apoda (Linnaeus) C. Morren
Selaginella apoda (L.) Link [ne semble pas exister donc non entré en bd] = Selaginella apoda (Linnaeus) C. Morren
[NB: si spécimen canadien, alors apoda = eclipes et non apoda - attention en annotant]
Selaginella rhodospora = Selaginella armata [Caraïbes et non US - si US valider spécimen]
Selaginella weatherbiana 
[le spécimen indiqué isotypus pourrait être un isotype - montrer à Geoff svp = cf http://www.tropicos.org/Name/26602909]
Selaginella utahensis acc
AS
Selaginella affinis A. Br. = Selaginella epirrhizos
Selaginella asperula Martius ex Spring acc
Selaginella bombycina acc
Selaginella brachylepis = Selaginella fragilis
Selaginella calosticha acc
Selaginella convoluta acc
Selaginella diffusa (C. Presl) Spring acc
Selaginella erythropus acc
Selaginella excurrens = Selaginella marginata
Selaginella filicaulis acc
Selaginella flagellata acc
Selaginella haematodes acc
Selaginella haenkeana acc
Selaginella leptoblepharis = Selaginella haenkeana
Selaginella hartwegiana acc
Selaginella lindigii = Selaginella lingulata
Selaginella microphylla acc
Selaginella mollis acc
Selaginella montevidensis = Selaginella sellowii
Selaginella moritziana acc

Selaginella pargiana : je ne trouve ce nom nulle part, ni des noms proches - svp vérifier

**Comment by brouille** [comment]
Selaginella poeppigiana Spring [mal écrit sur étiq. poepigiana] = nom. illeg. = Selaginella poeppigiana (Spring) Spring ex Splitgerber
