### ISSUE TITLE
New Taxon (check author)

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2898]
ID de taxon 8868, table Taxon :
Nom scientifique :  Nuphar variegata Durand
Nom scientifique accepté :  Nuphar variegata Engelmann ex Durand

selon Vascan et Plants of the World online :
Nuphar variegata Engelmann ex Durand
<http://data.canadensys.net/vascan/taxon/6715>
<http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:1117161-2>

selon Tropicos et FNA :
Nuphar variegata Durand
<http://www.tropicos.org/Name/22600101>
<http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=233500821>

Geoff

**Comment by brouille** [comment]
correction faite: Engelmann ex Durand
