### ISSUE TITLE
Mexico: Baja California municipio

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2900]
252783-6
Municipio Ensenada
https://en.wikipedia.org/wiki/Ensenada_Municipality

Luc

**Comment by brouille** [comment]
252789
Puebla: Municipio de Nicolás Bravo
https://es.wikipedia.org/wiki/Municipio_de_Nicol%C3%A1s_Bravo_(Puebla)

Luc

**Comment by brouille** [comment]
252790
Zimapán (municipio), Hidalgo, Mex.
https://es.wikipedia.org/wiki/Zimap%C3%A1n_(municipio)

Luc

**Comment by brouille** [comment]
252792
Natural Site Monument [IUCN] of Mexico
https://en.wikipedia.org/wiki/Yagul

Municipio : Tlacolula de Matamoros [Oaxaca]
https://en.wikipedia.org/wiki/Tlacolula_de_Matamoros

**Comment by brouille** [comment]
252794
Municipio: Vicente Guerrero
https://es.wikipedia.org/wiki/Vicente_Guerrero_(Durango)

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
