### ISSUE TITLE
USA : Parc

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2902]
252788
Davy Crockett National Forest
https://www.fs.usda.gov/detail/texas/about-forest/districts/?cid=fswdev3_008441
https://en.wikipedia.org/wiki/Davy_Crockett_National_Forest

Luc

**Comment by brouille** [comment]
252851
White River National Forest, COLO
https://www.fs.usda.gov/whiteriver
https://en.wikipedia.org/wiki/White_River_National_Forest

Luc

**Comment by brouille** [comment]
252852-3
https://bouldercolorado.gov/osmp/buckingham-picnic-area
Buckingham Park boulder Colo
Luc

**Comment by brouille** [comment]
258943
McConnels Mill State Park
https://www.dcnr.pa.gov/StateParks/FindAPark/McConnellsMillStatePark/Pages/default.aspx
https://en.wikipedia.org/wiki/McConnells_Mill_State_Park

Luc

**Comment by brouille** [comment]
116494
Allegheny National Forest
https://www.fs.usda.gov/allegheny
https://en.wikipedia.org/wiki/Allegheny_National_Forest

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
