### ISSUE TITLE
New Taxon faille des selaginellaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2905]
Selaginella douglasii (Hook. & Grev.) Spring.....usa

Selaginella flexuosa Spring....A du sud

Pour "Selaginella arenicola Underwood var. riddellii (Van Eselt.) Tryon" fiche 30341 le nom scientifique accepté est "Selaginella arenicola subsp. riddellii"     mais à la fiche 30342 le nom scientifique pour l'étiquette ne correspond pas car on a "var. et non subsp. " dans le nom

 

Selaginella sericeae  A. Braun...A du Sud

Selaginella smithii Hieron....A du Sud

Selaginella schlechteri Hieron.....europe

Selaginella spinulosa A.Br.....europe

Selaginella heterostachys Bak.....asie

Selaginella involvens Spr....Asie

Selaginella japonica Franch. & Sav   .......Asie

Selaginella mongholia Rupr.   ....Asie

Selaginella pouzolziana Spr.....Asie

Selaginella repanda (Desv.) Spring.......Asie

Selaginella savatieri....Asie

Selaginella tamariscina Spr.....Asie

Selaginella trachyphylla A.Br....Asie

Selaginella xipholepis Bak....Asie

laginella abyssinica Spring....afrique

Selaginella balansae Hier.......afrique

Selaginella dregei (Presl.) Hieron...afrique

Selaginella fissidentoides (Hook. & Grev.) Spring.......Afrique

Selaginella nivea Alston....afique

Selaginella pectinata Spring.....afrique

Selaginella scandens....afrique

Selaginella versicolor Spr.....afrique

Selaginella arbuscula Spring...oceanie

Selaginella agusanensis Hieron.....Oceanie

Selaginella bellula Cesati.....oceanie

Selaginella benguetensis Hieron.....océanie

Selaginella canaliculata Bak......oceanie

Selaginella caulescens Spring....oceanie

Selaginella cupressina (Willd.)  ...oceanie

Selaginella davaona Hieron......oceanie

Selaginella distans Warb......oceanie

Selaginella engleri Hieron.....oceanie

Selaginella fimbriata Spring.....oceanie

Selaginella firmula A. Br.....oceanie

Selaginella frondosa Warb....oceanie

Selaginella hellwigii Hieron....oceanie

Selaginella hombronii Hieron....oceanie

Selaginella lacerata Warb......oceanie

Selaginella llianosii Hiern......oceanie

Selaginella magnifica Warb. ...Philippines

Selaginella neo-caledonica océanie

Selaginella pervaga Hieron........philippines

Selaginella permula (Desv.)....philippines

Selaginella remotifolia Spring........Philippines

Selaginella sonneratii Hieron......oceanie

Diane Fournier

**Comment by brouille** [comment]
Selaginella arenicola subsp. riddellii corrigé

**Comment by brouille** [comment]
US
Selaginella douglasii acc
AS
Selaginella flexuosa acc
Selaginella sericea [pas de e] acc
Europe
Selaginella spinulosa = Selaginella selaginoides
Asie
Selaginella heterostachys acc
Selaginella involvens acc
Selaginella bellula  = Selaginella involvens
Selaginella caulescens = Selaginella involvens
Selaginella japonica Franch. & Sav.  [ aucun japonica avec ces auteurs ms] =  Selaginella nipponica Franch. & Sav.
Selaginella savatieri = Selaginella nipponica
Selaginella mongholiCa = Selaginella sinensis
Selaginella pouzolziana = Selaginella delicatula
Selaginella canaliculata = Selaginella delicatula
Selaginella davaona [mal épelé] = davaoensis = Selaginella delicatula
Selaginella repanda acc
Selaginella tamariscina acc
Selaginella trachyphylla acc
Selaginella xipholepis acc
Selaginella agusanensis = Selaginella latifrons
Selaginella benguetensis  = Selaginella eschscholzii
Selaginella cupressina acc
Selaginella engleri acc
Selaginella fimbriata Spring = Selaginella ornata
Selaginella frondosa acc
Selaginella hombronii = Selaginella philippina
Selaginella lacerata acc
Selaginella llanosii [pas de i après ll] acc
Selaginella magnifica Warburg acc
Selaginella pervaga = Selaginella opaca
Selaginella remotifolia acc
Afrique
Selaginella abyssinica = Selaginella goudotiana var. abyssinica
Selaginella balansae acc
Selaginella dregei acc
Selaginella fissidentoides acc
Selaginella nivea acc
Selaginella pectinata acc
Selaginella scandens = Selaginella myosurus
Selaginella versicolor acc
Océanie
Selaginella arbuscula acc
Selaginella distans acc
Selaginella firmula acc
Selaginella hellwigii acc
Selaginella neo-caledonica acc
Selaginella soneratii acc

non trouvé ds bd
Selaginella smithii HIeron.
Selaginella schlechteri Hieron.....europe : ce taxon est en Nvelle-Guinée, pas Europe - vérifier
Selaginella permula  Philippines

**Comment by brouille** [comment]
Selaginella smithii HIeron. nom. ined. = ?
Selaginella pennula (Desv.) Spring nom. inval. = Selaginella involvens
