### ISSUE TITLE
New Taxon Famille des Selaginellaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2909]
"Selaginella neo-caledonica" message 2905.....ce nom est accepté mais il n'y a pas de fiche dans la banque sous ce nom
 
 
 "Selaginella schlechteri Hieron." pas de fiche à ce nom
 
 Selaginella uliginosa Spr.,,,,,,oceanie
 
 Selaginella usteri Hieron...oceanie
 
 Selaginella victoriae Bull....oceanie
 
 Selaginella viridangula Spring......oceanie
 
 Selaginella waruskioldii Hieron (ou warnskioldii) ......Oceanie difficile à trouver
 
 
 Selaginella willdenowii Bak.....oceanie
 
 Selaginella emmeliana Gert....cultivé
 
 Selaginella martensii...cultivé
 
 Selaginella braziliensis.... cultivé
 
 Selaginella cocsia-arborea.......cultivé
 
  Selanigella umbrosa....cultivé
  
  Selaginella willdenowii...cultivé
  
  Selaginella de wildenow...cultivé
  
  Selanigella cultivar.....cultivé
  
  Selaginella densa Rydb.......wat.... .Alberta
  
  Selaginella apoda (L.)  Spring....wat québec
  
  Selaginella plumieri Hieron....A centrale république dominicaine
  
  Selaginella plana (Desv.) Hieron......A Centrale
  
  Selaginella pilifera var. pringlei (Baker)......A centrale
  
  Selaginella cupidata Link.....A centrale
  
  
  Le nom "Selaginella galeotti Spring" fiche 12165 Amérique centrale devient "Selaginella stellata" maiss il n'y a pas de fiche pour ce nom dans la base de données
  
  
  
 Selaginella mnioides,,,......A centrale
 
 Selaginella cuspidata Spr. (forma typica)....A centrale
 
 Selaginella confusa Spring....A centrale
 
 Selaginella cladorrhizans A. Br....A centrale
 
 Selaginella chrismari var. karwinskyana Hieron...A centrale
 
 Selaginella broadwayi Hieron.......A centrale
 
 Selaginella flabellata (L.) Spring....A centrale

Diane Fournier

**Comment by brouille** [comment]
Selaginella neo-caledonican = Selaginella neocaledonica 30529
il faut parfois essayer sans trait d'union car ils ne sont plus toujours conservés en nomenclature.
Océanie
Selaginella schlechteri acc
Selaginella uliginosa acc
Selaginella usteri acc
Selaginella victoriae acc
Selaginella viridangula acc
Selaginella willdenowii [Océanie ou cultivé, ou de Willdenow cult] acc
NB: Selaginella waruskioldii Hieron (ou warnskioldii) - il faut vérifier le nom sur le spécimen - rien de semblable ds les bd

Canada
Selaginella densa acc
Selaginella apoda (L.) Spring nom. illeg. = [ms pas au Canada] = annoter: S. eclipes

Amérique centrale-Caraïbes
Selaginella plumieri acc
Selaginella plana acc [int en AC]
Selaginella pilifera var. pringlei = Selaginella pilifera
Selaginella cuSpidata = Selaginella cuspidata Spr. [cet auteur est aut. d'une var et non sp] = Selaginella pallescens
Selaginella stellata acc ajouté
Selaginella mnioides = Selaginella diffusa
Selaginella confusa acc
Selaginella cladorrhizans acc
Selaginella chrismarii [2i] var. karwinskyana = Selaginella rupincola
Selaginella broadwayi = Selaginella minima
Selaginella flabellata acc

cultivé
Selaginella emmeliana = Selaginella pallescens
Selaginella martensii acc
Selaginella umbrosa acc
NB:
Selaginella braziliensis = Selaginella braSiliensis - avec quel auteur? il y a 2 synonymes
Selaginella cocsia-arborea : valider ce nom - est-ce un cv?
Selaginella cultivar = Selaginella - on ne peut rien faire sans un nom de cv

**Comment by brouille** [comment]
trouvé:
Selaginella wormskioldii = Selaginella eschscholzii
spécimen NY = MT: www.pteridoportal.org/portal/collections/individual/index.php?occid=718271&clid=0
