### ISSUE TITLE
New Taxon famille des salaginellaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2912]
Selaginella cuspidata Spring    .....Amerique centrale

Selaginella denudata (Willd.) Spring...Amerique centrale

Selaginella martensii Spring.....Amerique centrale

Selaginella lemairei Hieron.....Amerique centrale

Selaginella guatemalensis Baker ...Amerique centrale

Selaginella arthritica Alston......Amerique centrale

Lycopodium volubile ........Amerique centrale

Selaginella serpens (Desv.) Spring........Amerique centrale

Selaginella saccharata A.Br.....Amerique centrale

Selaginella rupinicola Underwood....Amerique centrale

Selaginella rotundifolia Spring....Amerique centrale

Derniers noms pour cette famille Diane Fournier

**Comment by brouille** [comment]
Selaginella cuspidata [auteur Link et non Spring] 30557 = S. pallescens
Selaginella denudata acc
Selaginella martensii 30548
Selaginella lemairei = Selaginella umbrosa
Selaginella guatemalensis acc
Selaginella arthritica acc
Selaginella serpens acc
Selaginella saccharata = Selaginella delicatissima
Selaginella rupinicola [mal épelé] = Selaginella rupincola 12167
Selaginella rotundifolia acc

Lycopodiaceae: spécimen mal rangé ; pas Amérique centrale ms Océanie?
Lycopodium volubile = Pseudodiphasium volubile
