### ISSUE TITLE
Parcs USA

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2919]
232206
Lookout Mountain Park
Spearfish, S.Dak.
https://www.cityofspearfish.com/310/Lookout-Mountain-Park

Luc

**Comment by brouille** [comment]
253965
Frank Raines Regional Park, Stanislaus Co., Calif.
http://www.stancountyparks.com/frank-raines/

Luc

**Comment by brouille** [comment]
254007
USF Forest Preserve
http://facilities.cas.usf.edu/forestpreserve/

Luc

**Comment by brouille** [comment]
254139-40
Bighorn National Forest
WY
https://www.fs.usda.gov/bighorn
https://en.wikipedia.org/wiki/Bighorn_National_Forest
Luc

**Comment by brouille** [comment]
254343
University of South Florida [USF] Forest Preserve
http://biology.usf.edu/ib/research/forest/

Luc

**Comment by brouille** [comment]
254415
Pine Creek Natural Area
Fairfield, CT
https://www.fairfieldct.org/openspace/pinecreek
Luc

**Comment by brouille** [comment]
254424 ss
Mill Hollow Park
Southport, CT
https://www.facebook.com/pages/Mill-Hollow-Park/144339072255583
Luc

**Comment by brouille** [comment]
254434
Chapman Pond Preserve​s
https://www.ehlt.org/chapman-pond-preserves

**Comment by brouille** [comment]
254454-7
Bluff Point State Park
https://en.wikipedia.org/wiki/Bluff_Point_State_Park
https://www.alltrails.com/trail/us/connecticut/bluff-point-state-park-and-coastal-reserve-trail

Luc

**Comment by brouille** [comment]
254617-8
Los Padres National Forest
Calif.
https://www.fs.usda.gov/lpnf/
https://en.wikipedia.org/wiki/Los_Padres_National_Forest

Luc

**Comment by brouille** [comment]
232160
Monte Vista National Wildlife Refuge
https://www.fws.gov/refuge/monte_vista/
https://en.wikipedia.org/wiki/Monte_Vista_National_Wildlife_Refuge

Luc

**Comment by brouille** [comment]
254752
Umpqua National Forest
Oregon
https://www.fs.usda.gov/umpqua/
https://en.wikipedia.org/wiki/Umpqua_National_Forest

Luc

**Comment by brouille** [comment]
208807
White Sands Missile Range, N.M.
https://www.wsmr.army.mil/Pages/home.aspx
https://en.wikipedia.org/wiki/White_Sands_Missile_Range

Luc

**Comment by brouille** [comment]
255288-9
Los Padres National Forest
Calif
https://www.fs.usda.gov/lpnf/
https://en.wikipedia.org/wiki/Los_Padres_National_Forest

Luc

**Comment by brouille** [comment]
255488
Pawnee Rock State Park
https://en.wikipedia.org/wiki/Pawnee_Rock

Luc

**Comment by brouille** [comment]
255492-3
Kaibab National Forest
Ariz.
https://www.fs.usda.gov/kaibab/
https://en.wikipedia.org/wiki/Kaibab_National_Forest

Luc

**Comment by brouille** [comment]
255542-3
Appalachicola National Forest
Florida
https://www.fs.usda.gov/apalachicola
https://en.wikipedia.org/wiki/Apalachicola_National_Forest

Luc

**Comment by brouille** [comment]
255577-8
Shawnee State Forest
Ohio
http://forestry.ohiodnr.gov/shawnee
https://en.wikipedia.org/wiki/Shawnee_State_Forest
Luc

**Comment by brouille** [comment]
255699-700
Willamette National Forest
Oregon
https://www.fs.usda.gov/willamette/
https://en.wikipedia.org/wiki/Willamette_National_Forest

Je ne sais si ce fut déja suggéré, ms non fait encore
Luc

**Comment by brouille** [comment]
257579
Grayson Highlands State Park
www.dcr.virginia.gov/state-parks/grayson-highlands
https://en.wikipedia.org/wiki/Grayson_Highlands_State_Park
Luc

**Comment by brouille** [comment]
257580
Comers Rock Recreation Area
www.fs.usda.gov/wps/portal/fsinternet/cs/recarea?ss=110808&navtype=BROWSEBYSUBJECT&cid=FSE_003738&navid=110240000000000&pnavid=110000000000000&position=BROWSEBYSUBJECT&recid=73661&ttype=recarea&pname=Comers%20Rock%20Recreation%20Area
Luc

**Comment by brouille** [comment]
257582
October Mountain State Forest
MAss
https://www.mass.gov/locations/october-mountain-state-forest
https://en.wikipedia.org/wiki/October_Mountain_State_Forest

Luc

**Comment by brouille** [comment]
257602
Mount Mitchell State Park
https://en.wikipedia.org/wiki/Mount_Mitchell_State_Park
https://www.ncparks.gov/mount-mitchell-state-park/home

Luc

**Comment by brouille** [comment]
132126
Brady's Run Park
Pennsylvania

Luc

**Comment by brouille** [comment]
257722
Kettle Moraine State Forest
WIS
https://dnr.wi.gov/topic/parks/name/kms/
https://en.wikipedia.org/wiki/Kettle_Moraine_State_Forest

Luc

**Comment by brouille** [comment]
258483-4
Stone Mountain Park
https://www.stonemountainpark.com/
https://en.wikipedia.org/wiki/Stone_Mountain
Luc

**Comment by brouille** [comment]
258489
NC
Gorges State Park
https://www.ncparks.gov/gorges-state-park/home
https://en.wikipedia.org/wiki/Gorges_State_Park
Luc

**Comment by brouille** [comment]
258494-5
Virginia
George Washington and Jefferson National Forests
https://en.wikipedia.org/wiki/George_Washington_and_Jefferson_National_Forests
https://www.fs.usda.gov/gwj

Luc

**Comment by brouille** [comment]
130867 & 258568
Helena-Lewis and Clark National Forest
Montana
https://www.fs.usda.gov/hlcnf/
https://en.wikipedia.org/wiki/Helena_National_Forest

Luc

**Comment by brouille** [comment]
130870
Mount Spokane State Park
Washington
https://www.historylink.org/file/7819
https://parks.state.wa.us/549/Mount-Spokane
https://en.wikipedia.org/wiki/Mount_Spokane_State_Park

Luc

**Comment by brouille** [comment]
258569
Bighorn National Forest
WYo.
https://www.fs.usda.gov/bighorn
https://en.wikipedia.org/wiki/Bighorn_National_Forest

Luc

**Comment by brouille** [comment]
130844
Caribou-Targhee National Forest
Wyoming
https://en.wikipedia.org/wiki/Caribou%E2%80%93Targhee_National_Forest
https://www.fs.usda.gov/ctnf

Luc

**Comment by brouille** [comment]
258651
Custer-Gallatin National Forest
https://www.fs.usda.gov/main/custergallatin/home
https://en.wikipedia.org/wiki/Gallatin_National_Forest

Luc

**Comment by brouille** [comment]
258655
Uinta-Wasatch-Cache National Forest
https://www.fs.usda.gov/uwcnf
https://en.wikipedia.org/wiki/Wasatch_National_Forest
Luc

**Comment by brouille** [comment]
258662
Plumas National Forest
Calif.
https://www.fs.usda.gov/recarea/plumas/recarea/?recid=71118
https://en.wikipedia.org/wiki/Plumas_National_Forest

Luc

**Comment by brouille** [comment]
258677
Bighorn National Forest
WY
https://www.fs.usda.gov/bighorn
https://en.wikipedia.org/wiki/Bighorn_National_Forest

Luc

**Comment by brouille** [comment]
258733-35
Umpqua National Forest
Oregon
https://www.fs.usda.gov/umpqua
https://en.wikipedia.org/wiki/Umpqua_National_Forest

Luc

**Comment by brouille** [comment]
258740
Jackson State Forest
Calif.
https://www.stateparks.com/jackson_state_forest_in_california.html
https://en.wikipedia.org/wiki/Jackson_Demonstration_State_Forest

Luc

**Comment by brouille** [comment]
258745
Los Padres National Forest
Calif.
https://en.wikipedia.org/wiki/Los_Padres_National_Forest
https://www.fs.usda.gov/lpnf/

Luc

**Comment by brouille** [comment]
258752-3
Tilden Regional Park
https://en.wikipedia.org/wiki/Tilden_Regional_Park
https://www.ebparks.org/parks/tilden/

Luc

**Comment by brouille** [comment]
258768
Hogback Mountain Conservation Area
VT
https://www.hogbackvt.org/

luc

**Comment by brouille** [comment]
47402
Nockamixon State Park
https://www.dcnr.pa.gov/StateParks/FindAPark/NockamixonStatePark/Pages/default.aspx
https://en.wikipedia.org/wiki/Nockamixon_State_Park

Luc

**Comment by brouille** [comment]
258960-3
Mass.
October Mountain State Forest
https://www.mass.gov/locations/oct
https://en.wikipedia.org/wiki/October_Mountain_State_Forestober-mountain-state-forest

Luc

**Comment by brouille** [comment]
258984-5
Hocking State Forest
Ohio
https://en.wikipedia.org/wiki/Hocking_State_Forest
http://forestry.ohiodnr.gov/hocking

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
