### ISSUE TITLE
New TaxonFamille des Selaginellaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2921]
Selaginella sibirica (Milde) Hieron..... TNO,Yukon Alaska

Selaginella densa Rydberg var. densa.....Yukon.Labrador 
Diane Fournier

**Comment by herbier** [comment]
Selaginella rupestri (L.) Spring. var densa

**Comment by brouille** [comment]
Selaginella sibirica acc
Selaginella densa var. densa = Selaginella densa

**Comment by brouille** [comment]
Selaginella rupestris var densa = Selaginella densa
