### ISSUE TITLE
Herbier - acronyme

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2922]
227134
ajouter à : Specimen history et Holotype at: 
VPI
Virginia Polytechnic Institute and State University
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126949

Luc

**Comment by brouille** [comment]
207882 et autres
FTG - Fairchild Tropical Botanic Garden 
Histoire
Luc

**Comment by brouille** [comment]
255380
historique
BROC
The College at Brockport, SUNY

Luc

**Comment by brouille** [comment]
258526
Herb. -- H. Russell Bassler

Luc

**Comment by brouille** [comment]
258759
Herb. E.S. Burgess

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
