### ISSUE TITLE
Mexico: Municipio

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2928]
253942
Mpio. Galeana [Nuevo León]
https://es.wikipedia.org/wiki/Galeana_(Nuevo_Le%C3%B3n)

Luc

**Comment by geoffreyhall** [comment]
Nom ajouté à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
