### ISSUE TITLE
Provinces du Chili

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2936]
Il serait bon d'ajouter les régions ou provinces du Chili (cell equi serait d'ordre 1 entre les deux concepts)
Il semble que la hiérarchie soit: région, province
254608
niveau 1: Santiago Metropolitan Region
https://en.wikipedia.org/wiki/Santiago_Metropolitan_Region
Niveau 2: Maipo Provincia
https://en.wikipedia.org/wiki/Maipo_Province

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
