### ISSUE TITLE
New TaxonFamille des myristicaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2942]
Drymis brasiliensis Miers.....Amérique du sud

Coelocaryon klainei Pierre.......Afrique

Horsfieldia irya Warb....océanie

Gymnacranthera.....océanie

 Svenhedinia minor Urb.......amérique centrale

**Comment by brouille** [comment]
Drymis brasiliensis est Winteraceae, pas Myristicaceae
Drymis brasiliensis [Drymis orth. var. inval. = Drimys] = Drimys brasiliensis fiche 23199

Myristicaceae
Coelocaryon klainei = Coelocaryon preussii
Horsfieldia irya acc
Gymnacranthera acc

Magnoliaceae
Svenhedinia minor = Magnolila minor
