### ISSUE TITLE
specimens Pierre Dansereau

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2943]
Les spécimens viennent tous de Nouvelle-Zélande, la localisation et l'habitat sont précisés mais pas les autorités:
199931: Melicytus macrophyllus
199933: Metrosideros albiflora
199934: Weinmannia sylvicola
199935: Corynocarpus laevigata
199936: Dacrydium cupressinum
199937: Gymnolea montana
199938: Alseuosmia sp
199939: Ixerba brexioides
199940: Quintinia serrata
199945: Litsaea calicaris
Il manque le déterminateur (ce n'est pas l'écriture de P.D. sur l'étiquette- Une écriture fine et soignée)

**Comment by brouille** [comment]
Melicytus macrophyllus acc
Metrosideros albiflora acc
Weinmannia sylvicola acc
Corynocarpus laevigatUS acc [corriger nom au besoin]
Dacrydium cupressinum acc
Alseuosmia déjà ds bd 31704
Ixerba brexioides déjà bd 31708
Quintinia serrata acc
Litsaea calicaris [mal écrit] = Litsea calicaris
Vérifier orthographie de ce nom, ds aucune bd (même genre) : Gymnolea montana

**Comment by herbier** [comment]
trouvé!
199937: Gymnelaea montana et non pas Gymnolea montana

**Comment by brouille** [comment]
Gymnelaea montana = Nestegis montana
