### ISSUE TITLE
 Famille des piperaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2948]
Tous ces noms sont en Amérique du sud

Piper aequale var. lasiocarpum C. DC. 

Piper aequale Vahl. 

Piper amalago L. var. medium (Jacq.) Yuncker 

Piper atrorameum C. DC 

Piper cascajalanum C. DC. 

Piper darienense C. DC. 

Piper ecuadorense Sodiro.. 

Piper gaudichaudianum Kunth

Piper glabrirameum C. DC.

Piper hispidum Sw. Var. magnifolium C. DC.

Piper lanceifolium Kunth 

Piper lineatum R. et P.

Piper miersinum C. DC.

Piper nubigenum Kunth.

Sarcorhachis obtusa var. cordata Yuncker

Piper peltobryon C. DC

Piper rufescens C. DC.

Piper smilacifolium H. B. K.

Piper sodiroi C. DC.

Piper subtropicum C. DC.

Piper trichogynum C. DC.

Piper tuberculatum Jacq.

Peperomia crassilimbus C. DC.

Peperomia aphylla C. DC.

Peperomia dolabriformis H.B.K., var.

Peperomia eburnea Sodiro

Peperomia pilinervia  C. DC.

Peperomia hispidula A. DC.

Peperomia lanceolata-peltata var.carlosiana (C. DC.) Yuncker

Peperomia langsdorffii Miq.

Peperomia longicaulis C. DC.

Peperomia loxensis Kunth.

Peperomia aff. macrothyrsa Miq.

Peperomia magnoliifolia (Jacq.) C. DC.

Peperomia millei Sodiro

Peperomia rotundata Kunth.

Peperomia rupicola C. DC.

Peperomia subalata C. DC.

Peperomia tumida Sodiro

 

..........................................................................................................................................................................

Piper capense...Afrique

Peperomia dindygulensis Miq..........Asie

Peperomia reflexa (L. fil.) A. Dietr......Afrique

Peperomia calvifolia C.DC.....cultivée

Peperomia caperata....cultivée

Peperomia caulibarbis....cultivée

Peperomia eburnea Sodiro.........cultivée

Peperomia maculata ....cultivée

Peperomia magnoliaefolia ....cultivée

Peperomia obtusifolia A. Dietr. = Piper obtusifolium L.......cultivée

Peperomia peltifolia ....cultivée

Peperomia prostrata Hort.......cultivée

Peperomia sandersii....cultivée

Peperomia urocarpa....cultivée

Diane Fournier

**Comment by brouille** [comment]
Piper aequale var. lasiocarpum = Piper aequale
Piper aequale acc
Piper amalago var. medium = Piper amalago
Piper atrorameum = Piper barbatum
Piper cascajalanum = Piper glanduligerum
Piper darienense acc
Piper ecuadorense acc
Piper gaudichaudianum acc
Piper glabrirameum = Piper carpunya
Piper hispidum var. magnifolium = Piper hispidum
Piper lanceifolium acc
Piper lineatum acc
Piper miersinum acc
Piper nubigenum acc
Piper peltobryon = Piper phytolaccifolium
Piper rufescens = Piper crassinervium
Piper smilacifolium = Piper reticulatum
Piper sodiroi acc
Piper subtropicum = Piper obliquum
Piper trichogynum acc
Piper tuberculatum acc
Piper capense acc
Sarcorhachis obtusa var. cordata = Manekia obtusa

**Comment by brouille** [comment]
Peperomia crassilimbus =  crassilimba = Peperomia miqueliana
Peperomia aphylla = Peperomia microphylla
Peperomia dolabriformis acc
Peperomia eburnea Sodiro = Peperomia eburnea Linden
Peperomia pilinervia = Peperomia hispidula
Peperomia hispidula acc
Peperomia lanceolata-peltata var.carlosiana = Peperomia lanceolatopeltata var. carlosiana = Peperomia lignescens
Peperomia langsdorffii = Peperomia blanda
Peperomia longicaulis = Peperomia parasitica
Peperomia loxensis acc
Peperomia macrothyrsa acc
Peperomia magnoliifolia = Peperomia magnoliaefolia [mal épelé] = Peperomia magnoliifolia acc
Peperomia millei acc
Peperomia rotundata acc
Peperomia rupicola acc
Peperomia subalata acc
Peperomia tumida acc
Peperomia dindygulensis acc
Peperomia reflexa = Peperomia tetraphylla
[cult]
Peperomia calvifolia acc
Peperomia caperata acc
Peperomia caulibarbis = Peperomia glabella
Peperomia obtusifolia acc
Peperomia peltifolia acc
Peperomia prostrata acc
Peperomia sandersii = Peperomia argyreia
Peperomia urocarpa acc
Peperomia maculata  : semblerait être un cv ms pas une sp - de quelle sp cv?
assigné à Peperomia caperata 'Maculata' (Variegata) - unknown
