### ISSUE TITLE
Rhus copallina ou copallinum ?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2957]
Vascan <http://data.canadensys.net/vascan/taxon/23680>
Rhus copallinum var. copallinum

Base de données MT
ID de taxon 11128 (Rhus copallina = Rhus copallina)
ID de taxon 22240 (Rhus copallina var. copallina = Rhus copallinum var. copallinum [?])
ID de taxon 26145 (Rhus leucantha = Rhus copallina var. copallina)

Geoff

**Comment by brouille** [comment]
copallinum
voir https://www.ipni.org/n/219750-2
Luc
