### ISSUE TITLE
Rubus nutkanus ou Rubus parviflorus ?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#2958]
Vascan <http://data.canadensys.net/vascan/taxon/8942>
nom accepté = Rubus parviflorus Nuttall [Rubus nutkanus Mociño ex Seringe serait un synonyme]

FNA eFlora [01-2020]<http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250100441>
nom accepté = Rubus nutkanus Mociño ex Seringe [Rubus parviflorus Nuttall serait un synonyme]

Base de données MT
ID de taxon 11475 (Rubus parviflorus Nuttall)

SVP voir message collé plus bas,

Geoff

---
From: Étienne Lacroix-Carignan <etienne.lacroix-carignan@hotmail.com>
Date: Mon, Jan 6, 2020 at 2:02 PM
Subject: Modification dans FNA pour Rubus parviflorus
To:  <geoffrey.hall@umontreal.ca>

Bonjour Geoffrey,

En me penchant sur le cas de Rubus repens/Dalibarda repens, j’ai pu remarquer un changement dans FNA pour Rubus parviflorus. Pas plus tard qu’à l’automne dernier, le nom Rubus parviflorus y figurait encore, mais maintenant, ce nom a été remplacé par Rubus nutkanus Mociño ex Seringe. Jetez un coup d’oeil à cette discussion pour comprendre l’origine du changement: <https://botanyphoto.botanicalgarden.ubc.ca/2018/07/rubus-nutkanus/>

Pour résumer, on a redécouvert dans une publication de Weston en 1770 l’utilisation du nom Rubus parviflorus pour décrire une entité maintenant reconnue comme Rubus creticus. Or, lorsque Nuttall a décrit son Rubus parviflorus en 1818, le nom parviflorus était déjà utilisé et donc le nom proposé par Nuttall était illégitime lors de sa parution.  Même si l’utilisation par Weston de Rubus parviflorus est depuis longtemps relégué comme un synonyme, son existence antérieure à l’attribution du nom par Nuttall signifie que Nuttall n’a pas légitimement utilisé le nom. 

Pour en revenir au Code et à ses exigences, le premier nom publié de façon effective et légitime pour cette espèce est le Rubus nutkanus Moc. ex Ser. publié en 1825. Telle était la conclusion de l'article de Van De Beek de 2016, ci joint. C’est le nom qui est présent dans Plants of the World Online et maintenant dans FNA.

Au plaisir, Étienne L-C
[Abraham van de Beek_2016_Validations of the Rubus taxa in Tournefort’s Institutiones and their Corollarium in later literature_Adansonia(sér.3)38(1)35-53.pdf](https://github.com/irbv-collections/MT-controlled-vocabulary/files/4027762/Abraham.van.de.Beek_2016_Validations.of.the.Rubus.taxa.in.Tournefort.s.Institutiones.and.their.Corollarium.in.later.literature_Adansonia.ser.3.38.1.35-53.pdf)

**Comment by brouille** [comment]
correction faite à VASCAN : nutkanus acc
