### ISSUE TITLE
coll Dansereau

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2962]
08-01-2020
Coll. P.Dansereau
200729 et 200730 Cladium huttonii
200735 Sparganium antipodium    Graebner
200739 Lepidosperma laterale R Br.
200740 Isolepsis inundatus R.Br.
              = Scirpus inundatus
200741 Potamogeton cheesemanii A. Bennett

Toutes collectées en Nouvelle-Zélande et identifiées par N.T. Moar

Merci, Colette Butet

**Comment by brouille** [comment]
Cladium huttonii = Machaerina arthrophylla
Sparganium antipodum = Sparganium subglobosum
Lepidosperma laterale acc
Isolepsis inundatus [mal épelé] = Isolepis inundata
Potamogeton cheesemanii acc
