### ISSUE TITLE
New Taxon Famille des aristolochiaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2973]
Piper cascajalanum fiche 31754 devient Piper glanduligerum mais cette fiche n'existe pas

Piper grande Vahl.....A du Sud

Peperomia kunthiana Miq.....A du sud

Asarum acuminatum (Ashe) Bicknell....ontario

Asarum canadense L. var.canadense......ontario

Asarum canadense L. var. acuminatum Ashe..........manitoba

Asarum caudatum Lindl......British Colombia

Asarum canadense L. var. reflexum...usa

Asarum canadense L. var. acuminatum...usa

Asarum reflexum Bickn.....usa

Asarum virginicum L....usa

Asarum lemmonii S. Watson.....usa

Hexastylis arifolia (Michx.) Small var. ruthii (Ashe) Blomquist....usa

Asarum europaeum L.....europe

Asarum caulescens Maximowicz..... asie

Asarum europaeum L. subsp. Caucasicum (Duch.) Soo....europe

Asarum europaeum L. var. caucasicum ......asie

Asarum europaeum L. var. caucasicum Duch....Asie

Asarum europaeum L. subsp. Caucasicum (Duch.) Soo   ...europe

Ideterotropa hexalpba F. Maekawa ...asie

Asarum hexalobum (F. Maekawa) F. Maekawa....Asie

Asarum magacalyx F. Maekawa......Asie

Asarum satsumense F. Maekawa...Asie

Asarum sieboldii Miquel......Asie

Asarum grandiflorum....cultivée

Diane Fournier

**Comment by brouille** [comment]
Piper glanduligerum ajouté 31754
Piper grande acc
Peperomia kunthiana = Peperomia hartwegiana

Aristolochiaceae
Asarum acuminatum = Asarum canadense
Asarum canadense var.canadense = Asarum canadense
Asarum canadense var. acuminatum = Asarum canadense
Asarum canadense var. reflexum = Asarum canadense
Asarum reflexum = Asarum canadense
Asarum caudatum acc
Asarum virginicum acc
Asarum lemmonii acc
Hexastylis arifolia var. ruthii = Asarum arifolium var. ruthii
Asarum europaeum acc
Asarum europaeum subsp. caucasicum acc
Asarum europaeum var. caucasicum = Asarum europaeum subsp. caucasicum
Ideterotropa hexalpba [mal épelé] = Heterotropa hexaloba = Asarum hexalobum
Asarum hexalobum acc
Asarum megacalyx acc
Asarum caulescens acc
Asarum satsumense acc
Asarum sieboldii acc
cult
Asarum grandiflorum Klotzsch = Asarum virginicum
