### ISSUE TITLE
Histoire: herbier privé

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2976]
256377
Herbier Benoît Lavigne, Faculté d'Agriculture de Sainte-Anne-de-la-Pocatière

Luc

**Comment by brouille** [comment]
248912
Herbartium of Walter M. Benner
Luc

**Comment by brouille** [comment]
257451
Herbier du Frère Marie-Alexis
cf people 15229
Luc

**Comment by brouille** [comment]
70835
Herbier de Soeur M[arie] Joseph Omer
Luc

**Comment by brouille** [comment]
257907
Thomas P. Hart Herbarium
Luc

**Comment by brouille** [comment]
258475 etc.
Herbier Laplante
SFS
Luc

**Comment by brouille** [comment]
Herb. E.S. Burgess
NY : North American Asters bequeathed by Professor Edward Sanford Burgess, 1927

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
