### ISSUE TITLE
Parc Québec

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#2978]
256430
Ile aux Lièvres
Société Duvetnor
https://duvetnor.com/sejours/ile-aux-lievres/
https://fr.wikipedia.org/wiki/%Ïle_aux_Lièvres
http://www.environnement.gouv.qc.ca/Infuseur/communique.asp?no=2587

Luc

**Comment by brouille** [comment]
130672-3
New Brunswick
Fort Beauséjour-Fort Cumberland National Historic Site
https://www.pc.gc.ca/en/lhn-nhs/nb/beausejour
https://en.wikipedia.org/wiki/Fort_Beaus%C3%A9jour
Luc

**Comment by brouille** [comment]
130460
Réserve faunique Duchénier
Rimouski-Neigette
https://www.reserveduchenier.com/
https://fr.wikipedia.org/wiki/R%C3%A9serve_faunique_Duch%C3%A9nier

Luc

**Comment by brouille** [comment]
257850
Ont. NIagara
Lathrop Nature Preserve
http://brocku.niagaragreenbelt.com/listings/76-parks-gardens-a-conservation-areas/698-lathrop-nature-preserve-tulip-trees.html

Luc

**Comment by brouille** [comment]
257857
High Park, Toronto
https://en.wikipedia.org/wiki/High_Park
https://www.toronto.ca/explore-enjoy/parks-gardens-beaches/high-park/

Luc

**Comment by brouille** [comment]
257922
St. Williams Conservation Reserve
Ont
https://swcr.ca/about-the-cr/

aussi inscrire HAldimand-Norfolk Regional Munic. ds comté original Ont

Luc

**Comment by brouille** [comment]
257925
Kenogami Wetlands Area of Natural and Scientific Interst (ANSI)
Ontario

Luc

**Comment by brouille** [comment]
130402
réserve de biodiversité projetée de l’Île-aux-Lièvres
http://www.environnement.gouv.qc.ca/Infuseur/communique.asp?no=2587

Luc

**Comment by brouille** [comment]
258594
Alberta
Kananaskis Provincial Park
https://www.albertaparks.ca/parks/kananaskis/kananaskis-country/
https://en.wikipedia.org/wiki/Kananaskis_Country

Luc

**Comment by brouille** [comment]
132429
Ghost River Wilderness Area
https://en.wikipedia.org/wiki/Ghost_River_Wilderness_Area

Luc

**Comment by brouille** [comment]
258887
Nunavut
Kugluk/Bloody Falls Territorial Park
https://en.wikipedia.org/wiki/Kugluk/Bloody_Falls_Territorial_Park
https://en.wikipedia.org/wiki/List_of_protected_areas_of_Nunavut

**Comment by brouille** [comment]
258888
Twin Falls Gorge Territorial Park
https://en.wikipedia.org/wiki/Twin_Falls_Gorge_Territorial_Park
https://en.wikipedia.org/wiki/List_of_protected_areas_of_the_Northwest_Territories

Luc

**Comment by brouille** [comment]
258941
Marcy's Woods, Ont.
https://www.marcyswoods.ca/

Luc

**Comment by brouille** [comment]
132012
Parc régional des Grandes-Rivières du lac Saint-Jean
https://www.quebecoriginal.com/en/listing/things-to-do/sports-and-nature/regional-parks/parc-regional-des-grandes-rivieres-du-lac-saint-jean-228798524
https://baliseqc.ca/3S/explorer/saguenay-lac-saint-jean/parc-regional-des-grandes-rivieres-du-lac-saint-jean-LR0945

Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen.
Geoff
