### ISSUE TITLE
New Taxon  Famille des magnoliaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2986]
Hexastylis virginica (L.) Small.......usa

Magnolia acuminata L.....ontario...usa

Magnolia cordata Michx....usa

Magnolia fraseri Walt....usa

Magnolia grandiflora L......usa

Magnolia pyramidata Bartr....usa

Magnolia virginiana L.........usa

Magnolia macrophylla Michaux...usa

Magnolia denudata Desr......asie

Magnolia fordiana Oliv. vel. aff....asie

Magnolia kobus De Candolle .....asie

Magnolia salicifolia Maximowicz...Asie

Magnolia sieboldii K. Koch........Asie

Magnolia kobus Thunb.......cultivé

Magnolia liliflora Desrouss. Cult. 'nigra'......cultivé

Magnolia soulangeana....cultivé

Talauma...océanie

Talauma gitingensis Elmer...océanie

Talauma mexicana (Dc.) Don.....mexique

Diane Fournier

**Comment by brouille** [comment]
Hexastylis virginica = Asarum virginicum

Magnolia acuminata acc
Magnolia cordata = Magnolia acuminata
Magnolia fraseri acc
Magnolia grandiflora acc
Magnolia pyramidata acc
Magnolia virginiana acc
Magnolia macrophylla acc

Talauma mexicana = Magnolia mexicana

Magnolia denudata acc
Magnolia fordiana acc
[vel aff. = ou proche]
Magnolia kobus acc
Magnolia kobus Thunb = DC. [n'existe pas] Magnolia kobus
Magnolia salicifolia acc [ms voir auteurs]
Magnolia sieboldii acc
Talauma gitingensis [ce taxon est en Asie et non Océanie : Philippines] = Magnolia liliifera

Magnolia liliflora 'Nigra' = Magnolia liliiflora 'Nigra' [2 i] acc
Magnolia soulangeana = Magnolia ×soulangeana acc

Talauma = Magnolia
