### ISSUE TITLE
New Taxon (Goniopteris pour S. Fawcett Pringle Herb.)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#2996]
248874: Dryopteris hastata sub auriculata C. Chr
248875: Dryopteris hastata leptocladia (Fée) le Chr.
256197: 2e détermination: Dryopteris tetragona (Sw?) Urban
        3e détermination: Dryopteris sub tetragona (Link.) Maxon
253443: Dryopteris asterothryx (Fée) C. Ch.
253436-253437-253438: Goniopteris scolopendrioides (L.) C. Presl
253435 3e détermination: Goniopteris hybrid (ajouter Goniopteris sp. s.v.p.)
       1 ière détermination: Dryopteris leptocladia Fée
253434: Goniopteris reptans X Goniopteris moranii
253432-253433: Goniopteris moranii C. Sánchez
253431: Goniopteris retroflexa (L.) Salino & T.E. Almeida

Claude Lucier 10 février 2020

**Comment by brouille** [comment]
Dryopteris hastata var auriculata Kuhn [in Christensen ou ex Christensen] = Goniopteris leptocladia
Dryopteris hastata var. leptocladia = Goniopteris leptocladia
Dryopteris tetragona (Swartz) Urban fiche 5099 = Goniopteris tetragona subsp. tetragona
Dryopteris subtetragona = Goniopteris tetragona subsp. tetragona
Dryopteris asterothrix [pas y] = Goniopteris biolleyi

**Comment by brouille** [comment]
Goniopteris scolopendrioides acc
Goniopteris acc
Dryopteris leptocladia = Goniopteris leptocladia
Goniopteris reptans × Goniopteris moranii = Goniopteris moranii × Goniopteris reptans
Goniopteris moranii acc
Goniopteris retroflexa acc
