### ISSUE TITLE
New Taxon - Isoetes

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3006]
257861		dét. 3
257869		dét. 3
52464		dét. 3
8802		dét. 3	
Isoetes echinospora M. Durieu × laurentiana D.F. Brunton

257904		dét. 6
257905		dét. 6
Isoetes ×echtuckerii D.F. Brunton & D.M. Britton

Geneviève Leblanc

**Comment by brouille** [comment]
Isoetes ×echtuckerii acc
Isoetes echinospora × Isoetes laurentiana acc
