### ISSUE TITLE
New Taxon Famille des magnoliaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3008]
Kadsura japonica Dunal.......Asie
 
 Illicium anisatum Linnaeus.......Asie
 
 Illicium religiosum Sieb. & Zucc........Asie
 
 Illicium religiosum Sieb. & Zucc......Asie
 
Schisandra coccinea Michx. ......USA

Schisandra chinensis (Turcz.) Baill......Asie

Schisandra repanda (Sieb. & Zucc.) Radlk.....Asie

Schizandra nigra Maximowicz.......Asie

Schisandra...Asie

Michelia compressa Sargent.....Asie

Michelia....ASIE

Michelia fuscata Blume.....cultivé

Liriodendron chinense Sarg.......Asie

Liriodendron tulipifera L. var. variegata.....cultivée

Diane Fournier

**Comment by brouille** [comment]
Att'n: plusieurs familles

Magnoliaceae
Michelia = Magnolia
Michelia compressa = Magnolia compressa
Michelia fuscata = Magnolia figo var. figo
Liriodendron chinense acc
Liriodendron tulipifera var. variegata = variegatum = Liriodendron tulipifera 'Variegata'

Schisandraceae
Kadsura japonica acc
Illicium anisatum acc
Illicium religiosum = Illicium anisatum
Schisandra acc
Schisandra coccinea = Schisandra glabra
Schisandra chinensis acc
Schisandra repanda acc
SchiSandra nigra = Schisandra repanda
