### ISSUE TITLE
familles aristolochiaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3009]
pour le nom "Aristolochia macrophylla Lam. " il y a deux fiches différentes    La fiche 29494 me donne comme nom scientifique accepté "Isotrema macrophyllum" et la fiche31916 me donne "Aristolochia macrophylla"

Quel nom dois-je retenir pour l'étiquette  "Aristolochia macrophylla " ou "Isotrema macrophyllum"

Diane Fournier

**Comment by brouille** [comment]
Isotrema macrophylla
LB
