### ISSUE TITLE
New TaxonFamille des magnoliaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3013]
Michelia cumingii Merr. & Rolfe.  ..... océanie

Illicium henryi Diels.......Asie
Diane Fournier

**Comment by brouille** [comment]
MAgnoliaceae
NB: Philippines = Asie, pas Océanie
Michelia cumingii = Magnolia philippinensis

Schisandraceae
Illicium henryi acc
