### ISSUE TITLE
MRC/CO/Distr Alberta

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3016]
258835
Calgary Region [pas City of Calgary]
https://en.wikipedia.org/wiki/Calgary_metropolitan_region
https://www.calgarymetroregion.ca/

Luc

**Comment by brouille** [comment]
258854
Aleutian West Borough
https://en.wikipedia.org/wiki/Aleutians_West_Census_Area,_Alaska
https://ballotpedia.org/Aleutians_West_Borough,_Alaska_(Judicial)

Luc

**Comment by brouille** [comment]
258878
Edmonton Metropolitan Region (ce n'est pas Edmonton!)
https://en.wikipedia.org/wiki/Edmonton_metropolitan_region

Luc

**Comment by brouille** [comment]
Nova Scotia

Il faut vérifier les MRC/Districts car certains noms ont changé et ne correspondent à rien dans le catalogue de contrôle

ex: 131930
Region of Queen's Municipality
https://en.wikipedia.org/wiki/Region_of_Queens_Municipality
est-ce l'ancien Queens County?

Luc

**Comment by geoffreyhall** [comment]
3 noms ajoutés à une base de données temporaire dans mon ordinateur; au retour au Centre, le contenu sera importé dans les tables appropriées de la base de données MT, suivi de la mise à jour des enregistrements concernés dans la table Specimen (Region of Queens Municipality, Halifax Regional Municipality, Cape Breton Regional Municipality).
Geoff

**Comment by geoffreyhall** [comment]
Les premiers ajoutés aussi (Aleutians West Borough, Edmonton Metropolitan Region, Calgary Metropolitan Region).
Geoff
