### ISSUE TITLE
PErsonal herbarium (history)

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3021]
259184 Histoire - champ 1
Herbarium of H.N. Patterson
Purchased August 1900 [par le Herbarium Field Columbian Museum, F]

Luc

**Comment by brouille** [comment]
259200 - histoire 1
Department of Botany, Hunter College of the City of New York

Luc

**Comment by brouille** [comment]
259355 - histoire 1
Herbarium of Dr. J.T. Rothrock

Luc

**Comment by brouille** [comment]
259402
Ex Coll. T.J. Hale
Histoire entrée 1
Luc

**Comment by brouille** [comment]
259406
Southern Appalachian Botanical Club - Eigth Distribution of Southeastern Plants

Tu as déjà SEcond...

Luc

**Comment by brouille** [comment]
259410
NTSC
 [= University of North Texas]
original: Herbarium of North Texas Teachers College, Denton, Texas
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126769
Luc

**Comment by brouille** [comment]
259416
Minnesota Natural Heritage Program, Plants of Pipestone County, Minnesota, U.S.A.

Luc

**Comment by brouille** [comment]
259680
Histoire item 1
Herb. Thomas P. Hart [Ont.]
Luc

**Comment by brouille** [comment]
259769
Histoire 1
SNC
Saint Norbert College 
U.S.A. Wisconsin. De Pere.
sweetgum.nybg.org/science/ih/herbarium-details/?irn=125847

Luc

**Comment by brouille** [comment]
259957
ACCDC : Atlantic Canada Conservation Data Centre

Luc

**Comment by brouille** [comment]
260634
Herbier Benoit Lavigne
Faculté d'Agriculture de Sainte-Anne-de-la-Pocatière
Luc

**Comment by brouille** [comment]
233946
Société pour l'échange des plantes vasculaires de l'Europe occidentale et du bassin méditerranéen. Edit. †P. Fauquier et J. Lambinon (LG) Fascicule 18 (1978-1979)

Luc

**Comment by brouille** [comment]
260858
Histoire: MA
Herbario del Real Jardín Botánico de Madrid (MA)

Luc

**Comment by brouille** [comment]
224878
LAU
Musée Botanique de l'Unibversité de Lausanne
Luc

**Comment by brouille** [comment]
261317
Histoire: Biltmore Herbarium
Luc

**Comment by brouille** [comment]
262270
Herb. Fred A. Barkley
Luc

**Comment by brouille** [comment]
262279
Herbarium of State Normal School, Winona, Minnesota
Luc

**Comment by brouille** [comment]
262383
BOON
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=123971
Luc

**Comment by brouille** [comment]
262694
JSNM = Jurica-Suchy Nature Museum at Benedictine University
St. Procopus College = Benedictine University
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=252214
Luc

**Comment by brouille** [comment]
267541
Herbarium of H.C. Benke

Luc

**Comment by brouille** [comment]
267751
SNC
St. Norbert College Herbarium, West De Pere, Wis.
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125847
Luc

**Comment by brouille** [comment]
267765
Umbach Herbarium
[WIS]
Luc

**Comment by brouille** [comment]
269284 
WSC [Western State College Herbarium]
devenu Western Colorado University
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=145264
Luc

**Comment by brouille** [comment]
269360
The Robert A. Norris Herbarium

Luc

**Comment by brouille** [comment]
270409
Popenoe's Herbarium
cf People 15869
Luc

**Comment by brouille** [comment]
270560
Forest Service Herbarium, USDA

Ne parviens pas à le trouver ds Index Herb.

Luc

**Comment by brouille** [comment]
270596
Dudley Herbarium, Stanford University
https://en.wikipedia.org/wiki/Dudley_Herbarium
Luc

**Comment by brouille** [comment]
270628
Herbarium Mary Fiske Spencer
[OC]
Luc

**Comment by brouille** [comment]
270645
Herbarium of H.N. Patterson
Purchased August 1900 by Filed Columbian Museum (F)
Luc

**Comment by brouille** [comment]
270695
Herbarium of Albin Backman

Luc

**Comment by brouille** [comment]
270697
Herbarium Horti Botanici Univ. Iasi, Romania [label]
IAGB = Botanical Garden "Anastasie Fatu" of Iasi
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126490
Luc

**Comment by brouille** [comment]
270700
Herb. Horti Bot. Nat. Belg.
Jardin botanique national de Belgique

acronyme non trouvé
Luc

**Comment by brouille** [comment]
270702
Herbarium C. Simon
Luc

**Comment by brouille** [comment]
270768
Herbarium of the Kondo Collection
Luc

**Comment by brouille** [comment]
270832
BAK
Azerbaijan National Academy of Sciences (ANAS)
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=123883
Luc

**Comment by brouille** [comment]
270848
HIRO
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124749
Luc

**Comment by brouille** [comment]
270899
Herbier G. & M. Tardieu
Luc

**Comment by brouille** [comment]
270918
svp, ajouter BC aux 2 rubriques: 
histoire 
holotype à

ajouter BC à holotype à pour ce spécimen

**Comment by brouille** [comment]
270921
Dr. C. Baenitz, Herbarium Europaeum

Luc

**Comment by brouille** [comment]
270924
Herbier X. Vendrely

Luc

**Comment by brouille** [comment]
270925
Herbier Jacob [Suisse] [B. Jacob]
et
NEU (Neuchatel) : http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126534
Luc

**Comment by brouille** [comment]
270937
Museum Botanicum R Horti Taurinensis - Herbarium Generale intégré à:
TO
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126455
Luc

**Comment by brouille** [comment]
270949
Herbario Natalensis 
est-ce NH ?
Il faut valider
Luc

**Comment by brouille** [comment]
271083
Botanical Collection of D.H. Krouse
now CM
Luc

**Comment by brouille** [comment]
271092
O. Leonhardt, Nossen i. Sa. Germania - Berliner Botanischer Tauschverein
Luc

**Comment by brouille** [comment]
271093
Herbarium of Leston A. Wheeler
Luc

**Comment by brouille** [comment]
271527
DISKO
Danish Arctic Station, Disko, Greenland
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124369
Luc

**Comment by brouille** [comment]
271562
Herbarium of Freed W. Hoffman
Luc

**Comment by brouille** [comment]
271739-40
Herbarium Dennis W. Woodland
Luc

**Comment by brouille** [comment]
271848
Ajouter acronyme DES à histoire
DES _+ Desert Botanic Garden, Phoenix, Ariz
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124402
Luc

**Comment by brouille** [comment]
271965
Herbarium of Freed Hoffman [UC]
Luc

**Comment by brouille** [comment]
272563
DES (Desdert Botanical Garden, ARiz.)
Luc

**Comment by brouille** [comment]
272691
KESC
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125047

Luc

**Comment by brouille** [comment]
272710
Herbarium J.A. Sanford
Luc

**Comment by brouille** [comment]
272781
WSC [Western State College = Western Colorado University]
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=145264

Luc

**Comment by brouille** [comment]
272934
CS
Colorado State University
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124321
Luc

**Comment by brouille** [comment]
164891
Herbier Benoit Lavigne
FAc. Agriculture, Ste-Anne-de-la-Pocatière

Luc

**Comment by brouille** [comment]
164521
SNC
St. Norbert College
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125847
Luc

**Comment by brouille** [comment]
274257-8
Herb. of G.W. Freiberg
cf People 16399
Luc

**Comment by brouille** [comment]
274489
Histoire 
WVU
Luc

**Comment by brouille** [comment]
164720
Herbier du Cercle Simon-Valois
Luc

**Comment by brouille** [comment]
plusieurs spécimens UQAM 
Herbier du Cercle Simon-Valois
Luc

**Comment by brouille** [comment]
275268-9
Herbarium, University of the Punjab: LAH 
Luc

**Comment by brouille** [comment]
275270
BAK
Herbarium Azerbajdzhnicum (Inst. bot., Filiationis Azerb. Acad. Sci. URSS) est probablement maintenant BAK, Azerbaijan National Academy of Sciences (ANAS), seul herbier répertorié pour Azerbaijan
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=123883
Luc

**Comment by brouille** [comment]
275307 et ailleurs
MBM
Museu Botânico Municipal, Curitiba
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125352
Luc

**Comment by brouille** [comment]
275376
Herbier Arm : Thielens. Tirlemont (Belgique)
Luc

**Comment by brouille** [comment]
275397
Herbarium Vadense - peut-être écrire ce nom pr histoire
https://edepot.wur.nl/282969
est-ce WAHO?
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=124860
fusionné avec WAG, ms histoire est WAHO, si bon herbier
Luc

**Comment by brouille** [comment]
275398
TURUN Ylioiston Kasvimueao = Turku University Herbarium = probablement TUR
Luc

**Comment by brouille** [comment]
275406
Herbier J. [Jospeh] Hommey [médecin à Seès, Orne]
Luc

**Comment by brouille** [comment]
275411
Herb. E.F. Linton
Luc

**Comment by brouille** [comment]
275428
Herb. Musei Hist. Natur. Vindob. [Vindobonensis = Vienna ?]
je ne sais quel herbier ce peut être - il faudrait entrer tel quel (comme le font les autres herbiers, apparemment)
Luc

**Comment by brouille** [comment]
275435
Herbarium Bordère
voir fiche people 16530
Luc

**Comment by brouille** [comment]
275442
TRH
Trondheim http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125570
Luc

**Comment by brouille** [comment]
275446
NEU
Neuchâtel, Suisse
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126534
Luc

**Comment by brouille** [comment]
275528
Université de Caën 
CN

Luc

**Comment by brouille** [comment]
275535, 8
Herbarium Hermann Bessel Hagen
Luc

**Comment by brouille** [comment]
275540
ex Museo botanico turicensi, Zürich (Schweiz)
Luc

**Comment by brouille** [comment]
275545
Herbier de la chaîne du Mont-Blanc
[Venance Payot]
Luc

**Comment by brouille** [comment]
275547
Herbier du Dr. Henri van Heurck à Anvers
Luc

**Comment by brouille** [comment]
275585
Herbier M. Despaty
Herbier Delessert
Luc

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour.

Geoff
