### ISSUE TITLE
Mexico Municipio

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3023]
259353
Mexico, Nuevo Leon
Municipio General Zaragoza
https://es.wikipedia.org/wiki/General_Zaragoza

Luc

**Comment by brouille** [comment]
260029
Mexico, Nuevo Leon
Municipio Santa Catarina
https://en.wikipedia.org/wiki/Santa_Catarina_Municipality,_Nuevo_Le%C3%B3n

Luc

**Comment by CaroleSinou** [comment]
Les deux Municipio étaient déjà dans la BD.
Les fiches ont été mises à jour.
