### ISSUE TITLE
Herbarium history

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3030]
261870
Herbarium of Atomic Energy of Canada Limited. WNRE Pinawa, Manitoba, Canada

Luc

**Comment by brouille** [comment]
262366
Lafayette College
PEnnsylvania
Luc

**Comment by brouille** [comment]
262703
Dr. J.V. Haberer Collection [Presented 1925]
NYS

Luc

**Comment by brouille** [comment]
262705
Biltmore Herbarium (voir fiche collecteur 14242)
collection privée
Luc

**Comment by brouille** [comment]
262809
[WAT collection]
From the Collection of Alice Winifred Anderson Purchased 1975
Luc

**Comment by brouille** [comment]
263227
From Herbarium of Dr. J.T. Rothrock [1840-1880, now apparently at F - purchased 1909]
Luc

**Comment by brouille** [comment]
263546 et suivants
ACCDC 
Atlantic Canada Conservation Data Centre
Luc

**Comment by brouille** [comment]
263638, 263661
Herbier Fr. Adrien Robert c.s.v.

**Comment by brouille** [comment]
ajouter OKL à la liste des herbiers pour histoire
Luc

**Comment by brouille** [comment]
264799
Pammel Coll.
Luc

**Comment by geoffreyhall** [comment]
(1)  263638, 263661:  Herbier Fr. Adrien Robert c.s.v.
Déjà répertorié (750 enregistrements), fiches mises à jour

(2)
262809 [WAT collection]:  From the Collection of Alice Winifred Anderson Purchased 1975
Déjà répertorié (13 enregistrements), fiche mise à jour

Geoff

**Comment by brouille** [comment]
265269 etc
Thomas P. Hart Herbarium
WAT
Luc

**Comment by brouille** [comment]
265817
BOON : Appalachian State University Herbarium
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=123971
Luc

**Comment by brouille** [comment]
266361
Herbarium of John Donnell Smith

le nom est Donnell Smith, prénom John - voir fiche
Luc

**Comment by brouille** [comment]
266381
UCR
Herbarium University of California-Riverside
Luc

**Comment by brouille** [comment]
266415
Waynesburg College Herbarium

Il semble que Waynesburg University n'ait plus d'herbier - je ne peux déterminer où il a pu passer

Luc

**Comment by brouille** [comment]
266417
Muskingum College Herbarium = MUS
http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125401
Luc

**Comment by geoffreyhall** [comment]
Tous les noms ajoutés, toutes les fiches mises à jour.
Geoff
