### ISSUE TITLE
Divison of Alberta

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3034]
262788
Edmonton Capital Region
https://en.wikipedia.org/wiki/Edmonton_Metropolitan_Region

Cette région manque - il n'y a que Edmonton même

Luc

**Comment by CaroleSinou** [comment]
Edmonton Capital Region ne semble pas exister, mais Edmonton Metropolitan Region existe et est déjà dans la base de données.
Fiche mise à jour.
