### ISSUE TITLE
Questions autour de Hieracium vulgatum Fries (accepté?)

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3037]
Base de données MT––
ID de taxon = 6811
Nom scientifique en synonymie = Hieracium vulgatum Fries
Nom scientifique accepté = Hieracium lachenalii Suter subsp. cruentifolium (Dahlsted & Lübeck) Zahn

ID de taxon = 26462
Nom scientifique = Hieracium lachenalii Suter subsp. cruentifolium (Dahlsted & Lübeck) Zahn
Nom scientifique accepté = Hieracium lachenalii Suter subsp. cruentifolium (Dahlsted & Lübeck) Zahn

ID de taxon = 6790
Nom scientifique en synonymie = Hieracium lachenalii C.C. Gmelin
Nom scientifique accepté = Hieracium vulgatum Fries

Vascan––
<https://data.canadensys.net/vascan/taxon/3241>
Nom accepté d'espèce = Hieracium vulgatum Fries
indigène au Québec

<https://data.canadensys.net/vascan/taxon/30729>
Nom accepté d'espèce = Hieracium lachenalii Suter subsp. cruentifolium (Dahlsted & Lübeck) Zahn
introduit au Québec

Geoff

**Comment by brouille** [comment]
VASCAN a été corrigé, ce qui paraîtra à la prochaine publication.
Hieracium lachenalii C.C. Gmelin est isonyme [et donc syn] sw H. lachenalii Suter - corrigé ds VASCAN
