### ISSUE TITLE
Parcs USA

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3045]
265699
Robb Prairie [Pittsburg State University]
Pittsburg, Kansas
https://biology.pittstate.edu/robb-prairie.html

Luc

**Comment by brouille** [comment]
265888
National Elk Refuge
https://en.wikipedia.org/wiki/National_Elk_Refuge
https://www.fws.gov/refuge/national_elk_refuge/
Luc

**Comment by brouille** [comment]
266204
Oregon
Steens Mountain Wilderness
https://www.blm.gov/visit/steens-mountain-wilderness
https://en.wikipedia.org/wiki/Steens_Mountain_Wilderness

Luc

**Comment by brouille** [comment]
266207
Tahoe National Forest
https://www.fs.usda.gov/tahoe
https://en.wikipedia.org/wiki/Tahoe_National_Forest
Luc

**Comment by brouille** [comment]
203586
Deschutes National Forest
https://www.fs.usda.gov/main/deschutes/home
https://en.wikipedia.org/wiki/Deschutes_National_Forest
Luc

**Comment by CaroleSinou** [comment]
Tahoe National Forest et Deschutes National Forest étaint déjà dans la base de données.
Les autres ont été ajoutés et les fiches mises à jour.
