### ISSUE TITLE
Anthoxanthum nitens subsp. nitens     OU     A. nitens ?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3046]
Base de données MT (subsp. non acceptée)
ID de taxon 16808
Anthoxanthum nitens (Weber) Y. Schouten & Veldkamp subsp. nitens
est synonyme de
Anthoxanthum nitens (Weber) Y. Schouten & Veldkamp

VASCAN (subsp. acceptée)
Anthoxanthum nitens (Weber) Y. Schouten & Veldkamp subsp. nitens
<https://data.canadensys.net/vascan/taxon/7411>

NB: autre subsp. publiée en 2020 –– Taxon 69 (2): 264 –– Anthoxanthum nitens (Weber) Y. Schouten & Veldkamp subsp. kolymense (Prob.) Röser & Tkach

Geoff

**Comment by brouille** [comment]
Anthoxanthum nitens (Weber) Y. Schouten & Veldkamp subsp. nitens acc
