### ISSUE TITLE
Change Taxon Status

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3048]
John Semple (2021-04-08): "I submitted the manuscript on S. sect. Argutae to Phytoneuron yesterday."

Le manuscrit soumis à Phytoneuron a un impact sur la table Taxon:

Solidago vaseyi devient nom acc.

Solidago arguta var. caroliniana devient synonyme
Solidago arguta subsp. caroliniana devient synonyme
Solidago arguta subsp. caroliniana var. caroliniana devient synonyme
Solidago boottii var. caroliniana devient synonyme
Solidago yadkinensis devient synonyme (?)
Solidago arguta subsp. australis devient synonyme (?)
etc.

Dans la base de données MT, j'ai déjà mis à jour tous les enregistrements de Solidago arguta var. caroliniana (nouv. dét. = Solidago vaseyi)

Geoff

**Comment by brouille** [comment]
Solidago vaseyi acc

tous les autres noms associés à arguta var. caroliniana sont syn

Luc
