### ISSUE TITLE
Famille des brassicacea et des cabombaceae

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3080]
Draba pilosa ex de Candolle......Nouveau-Quebec......

Brasenia peltata .......fiche numero 2072   Le nom scientifique pour l'étiquette ne correspond pas au nom scientifique accepté

Cabomba piauhiensis Gardn......Cuba ....

Diane Fournier

**Comment by brouille** [comment]
Draba pilosa taxon 33153

Brasenia peltata : c'est normal, comme j'ai expliqué à Diane

Cabomba piauhiensis = Cabomba furcata
