### ISSUE TITLE
Dryopteris disjuncta

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3081]
<https://data.canadensys.net/vascan/taxon/5414>
nom accepté (MT & Vascan):  Gymnocarpium dryopteris (Linnaeus) Newman
synonyme selon MT (pas selon Vascan):  Dryopteris disjuncta auct. non (Ruprecht) C.V. Morton (nom saisi dans 95 fiches, mais absent de la table Taxon) – à vérifier

<https://data.canadensys.net/vascan/taxon/5413>
nom accepté (MT & Vascan):  Gymnocarpium disjunctum (Ruprecht) Ching
synonyme (MT & Vascan):  Dryopteris disjuncta (Ruprecht) C.V. Morton

Geoff

**Comment by brouille** [comment]
Geoff

Ces entrées de VASCAN sont correctes. L'entrée pour D. disjuncta (5043) est aussi correcte.

3081 est Carex picta. 

Je ne suis pas certain du problème à régler.
Luc

**Comment by geoffreyhall** [comment]
Je ne vois pas de problème dans VASCAN, il a été cité pour montrer que MT est différent.

Je crois qu'il faut créer une fiche dans la table Taxon de la base de données MT pour le taxon suivant (inscrit comme tel dans 90 enregistrements; par ex. MT-124914) –

Dryopteris disjuncta auct. non (Ruprecht) C.V. Morton

Si la fiche ne devrait pas exister, il faudrait modifier le nom dans les 90 enregistrements (inséré en bloc le 17 janvier 2014).

Geoff

**Comment by brouille** [comment]
C'est plus clair. J'ai ajouté ce taxon à MT/taxon et à VASCAN car c'est un problème général de nom mal appliqué.
Luc
