### ISSUE TITLE
récolteur d'Abitibi W.J.W.?

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3084]
à trouver 
récolteur anglophone d'Abitibi, en 1901, aux initiales W.J.W. 
[probablement pour la dernière initiale]

Luc

**Comment by geoffreyhall** [comment]
William James Wilson (1851-1920), géologue
infos grâce à Nolia Gervais
Correction dans la table People, fiche mise à jour
Geoff
