### ISSUE TITLE
Wilson

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3087]
William James Wilson (1851-1920), géologue
https://www.bac-lac.gc.ca/fra/recherchecollection/Pages/recherchecollection.aspx?q=%22Wilson%2c+W.J.%22&start=0&num=100

voilà c'est cela
en même temps, voici les pending:
272538 Det. 1 Nardosmia (Petasites) palmata, Hook.
272675 Det. 1 Nabalus nanus D.C.
273564 Det. 1 Immortelles
273710 Det 1 Mentha veridis Michx

**Comment by CaroleSinou** [comment]
Fiches déjà mises à jour lors de ma vérification.
