### ISSUE TITLE
New Taxonfamille des nympheaceae 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3115]
Nymphaea advena Ait........Quebec

Nuphar polysepala Engelmann   .....Alaska

Nuphar luteum subsp. Macrophyllum (Small) E. O. Beal......USA

Nuphar × intermedia Ledebour.....europe

Nuphar luteum (L.) Sm.×pumilum (Timm) DC le résultat sur la fiche donne "nuphar pumila" comme nom accepté mais il n'y a pas de fiche s'y rapportant

Nymphaea alba L. orientalis....europe

Chloranthus brachystachys Bl......Philippines

Diane Fournier

**Comment by brouille** [comment]
Nymphaea advena = Nuphar advena subsp. advena
Nuphar polysepala acc

**Comment by brouille** [comment]
Nuphar luteum subsp. macrophyllum = nom. inval. = Nuphar advena subsp. advena
Nuphar ×intermedia = Nuphar ×spenneriana
Nuphar luteum × pumilum [noms  inval.] = Nuphar lutea × pumila  = Nuphar ×spenneriana

Nymphaea alba L. orientalis : Nymphaea alba var. orientalis [arbitraire] nom ined. = Nymphaea alba

Chloranthus brachystachys = Sarcandra glabra subsp. brachystachys
