### ISSUE TITLE
Correction requise : parcs fiche 1177

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#3142]
Geoff

Cette fiche était attribuée au CAnada, Northwest Territories, Wood Buffalo NP [cela le remplaçait d'ailleurs en entrée)
Or il s'agit de sites historiques qui peuvent se trouver à au moins 3 endroits au USA. À quel état faut-il l'associer

Il faut corriger la fiche
Luc

**Comment by geoffreyhall** [comment]
3 nouveaux parcs ajoutés pour remplacer l'ancien (<2019) "World War II Valor in the Pacific National Monument".

Geoff
