### ISSUE TITLE
Rubus (Claude Lucier)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3159]
281720: Rubus argutus Link
 281743-281744: Rubus flagellaris invisus Bailey

Claude Lucier 13 juin 2022

**Comment by brouille** [comment]
Rubus argutus = Rubus pensilvanicus [ms acc in PLANTS] 
Rubus flagellaris invisus = Rubus flagellaris var. invisus = Rubus flagellaris
