### ISSUE TITLE
Famille des thelypderidaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3163]
Dryopteris brunnea C.Chr. = Olypodium distans Don. .............Noté Pseudophegopteris sp. par M.Sundue
 pas dans la banque de données

Diane Fournier

**Comment by brouille** [comment]
Dryopteris brunnea = nom. nudum = Polypodium distans = Pseudophegopteris pyrrhorhachis
Pseudophegopteris acc
