### ISSUE TITLE
familles des polydiaceas

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3172]
polypodium pustulatum   devient   Dendroconche scandens (G.Forst)  ps dans la banque.......     nouvelle zeland

    polypodium papillosum Bl.........Thylacopteris papillosa (Blume) Kunze ex J.Sm.
    
  Polypodium decrescens Christ .....Themelium curtisii (Baker) Parris.......philippines
  
  polypodium bamlerianum Ros.........Microsorum rampans (Baker) Parris........ nouvelle guinnée
  
  Polypodium bolobense Brause..........   papuanae
  
  Polypodium accedens Blume.........Lemmaphyllum accedens (Blume) Donk ........

Diane Fournier

**Comment by brouille** [comment]
Polypodium pustulatum = Lecanopteris pustulata subsp. pustulata
Dendroconche scandens = Lecanopteris scandens
Polypodium papillosum = Thylacopteris papillosa

**Comment by brouille** [comment]
Polypodium decrescens = Themelium curtisii = Oreogrammitis curtisii
Polypodium bamlerianum = Microsorum rampans
Polypodium bolobense = Prosaptia bolobensis
Polypodium accedens = Lemmaphyllum accedens = Lepisorus accedens
