### ISSUE TITLE
famille des Aspleniaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3185]
Hymenasplenium obtusifolium (L.) L. Regalado & Prada.   Amerique du sud

Pecluma hygrometrica (Splitg.) M.G.Price.  .....Amerique du sud

Hymenasplenium repandulum (Kunze) L.Regalado & Prada.....Amerique du sud

Goniopteris reptans x G. moranii.....Amerique du sud 

Dryopteris spinulosa sensu lato......terre neuve

Diane Fournier

**Comment by brouille** [comment]
Hymenasplenium obtusifolium acc
Pecluma hygrometrica acc
Hymenasplenium repandulum acc
Goniopteris reptans x G. moranii fiche 32001 [MT place les noms des parents en ordre alphabétique, à moins qu'il y ait des indications spécifiques sur le parent femelle]
Dryopteris spinulosa sensu lato = Dryopteris spinulosa auct. non (O.F. Mueller) Watt - fiche 5092
