### ISSUE TITLE
New Taxon (Projet ultraM)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3189]
115467: 1 ière det.: Chaptalia stenocephala (Griseb.) Urb.
115521: 1 ère det.: Eupatorium polydon [polyodon selon tropicos] Urb. ?
113345-113347: 3e det.: Lyonia glandulosa  (Richard) Urb. var glandulosa
113355: 1ère det.: Lyonia sp.
113361: Xolisma macrophylla Britton
258037-258038: 2e det.: Lyonia nipensis Urb. var nipensis
114833: Phialanthus parviflorus Urban
113445-113443: Purdiaea nipensis Victorin & León var nipensis
258039: 3e det. Rhynchospora cernua Griseb. var crispa (Gale) Raymond
115194-115196: 1ère det.: Tabebuia sp.
115652: 1ère det.: Wedelia veronicaefolia Rich. 

claude Lucier 22 juillet 2022

**Comment by herbier** [comment]
ajouter :115526: 1 ère det.: Eupatorium polydon [polyodon selon tropicos] Urb. ?

**Comment by brouille** [comment]
Chaptalia stenocephala acc
Eupatorium polyodon = Koanophyllon polyodon
Lyonia glandulosa var. glandulosa acc
Lyonia acc
Xolisma macrophylla = Lyonia macrophylla
Lyonia nipensis var nipensis acc
Phialanthus parviflorus = Phialanthus parvifolius [mal épelé] 
Purdiaea nipensis var. nipensis acc or syn ?
Rhynchospora cernua var. crispa = non publié =? Rhynchospora crispa
Tabebuia acc
Wedelia veronicaefolia = veronicifolia = Wedelia ehrenbergii var. veronicifolia
