### ISSUE TITLE
Famille des dryopteris

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3195]
Dryopteris clintoniana  x spinulosa... Usa

Thelypteris cristatum x goldiana Benedict..Usa

Dryopteris clintoniana var. genuina Wherry .....Usa

Dryopteris ×dowellii (Farwell) Wherry = Dryopteris clintoniana xintermedia.....ontario....lequel des deux noms dois-je retenir?

Diane Fournier

**Comment by brouille** [comment]
Dryopteris clintoniana var. genuina = Dryopteris clintoniana
Dryopteris ×dowellii acc  : à utiliser - l'autre est la formule hybride des parents, une explication
Thelypteris cristatum [cristata] x goldiana - Dryopteris cristata x Dryopteris goldiana
Dryopteris clintoniana x spinulosa = Dryopteris clintoniana ×Dryopteris carthusiana [valider dét.]
