### ISSUE TITLE
Agrostis alba – taxon utilisé pour 2 espèces

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3206]
Le type d'Agrostis alba serait Poa nemoralis, mais sur nos spécimens Agrostis alba désigne soit A. stolonifera soit A. gigantea.  Les spécimens sont déterminables par les botanistes un peu expérimentés mais non par les bénévoles qui font des annotations électroniques de Poa nemoralis.

La solution idéale signalerait le problème dans la base de données et permettrait aux bénévoles de reconnaître le besoin de demander de l'aide.

Geoff

**Comment by brouille** [comment]
Ai créé des fiches auct. non Linnaeus avec les deux noms d'Agrostis, avec note indiquant que le nom est mal appliqué
