### ISSUE TITLE
New Taxon (WAG)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3207]
207154 1ère det.:  Crotalaria lachnophora A. Rich.
207414: 1ère det.: Macrotyloma axillare (E. Mey.) Verdc. var. axillare
207365: 1ère det.:  Albizia glaberrima (Schumach. & Thonn.) Benth var. glaberrima
207301: 1ère det.:   Desmodium repandum (Vahl) DC.)
207319: 1ère det.:  Atylosia scarabaeoides (L.) Benth.
207369: 2e det.:  Dalbergia afzeliana  sans autorité selon la liste d'expédition
207329: 1ère det.: Retama raetam (Forssk.) Webb & Berthel. subsp. raetam
207342: 1ère det.: Vicia grandiflora Scop. var. grandiflora

Claude lucre 2 septembre 2022

**Comment by brouille** [comment]
Crotalaria lachnophora acc
Macrotyloma axillare var. axillare acc
Albizia glaberrima var. glaberrima acc
Desmodium repandum = Hylodesmum repandum
Atylosia scarabaeoides  = Cajanus scarabaeoides var. scarabaeoides
Dalbergia afzeliana acc
Retama raetam subsp. raetam acc
Vicia grandiflora var. grandiflora = Vicia grandiflora
