### ISSUE TITLE
Spécimen pour envoie à CAN

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3225]
273064- 273065, 2e det.: Potentilla X Rubricaules
273066: Ranunculus trichophyllus Chaix a pud Vill. var. eradicutus (Laestad.) Drew

Claude Lucier , 19 septembre 2022

**Comment by brouille** [comment]
Potentilla X Rubricaules : Potentilla rubricaulis fiche 33741 - non considéré comme hybride par Errter ds FNA
Ranunculus trichophyllus var. eradicAtus = Ranunculus confervoides
