### ISSUE TITLE
Plante pour les botanistes de Can

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3261]
285498: 2e det.: Melanocalyx uniflora (L.) Morin
285499: 1ère det.: Mertensia maritima (L.) S.F. Gray var. tenella Fries
285785-285786-285787-285788: 1ère det.: Ledum palustre L. var. decumbens Ait.
285822-285823-285824-285825-285826: 1ère det.: Lychnis affinis Fries
286089-286093-286095: Empetrum nigrum L. var. hermaphroditum (Lange) Soerensen
286083: Ledum palustre L. var. decumbens Ait
286203-286204: Lychnis triflora (sans autorité)
286205: Melandrium triflorum (R. Br.) J. Vahl
286215-286217-286218: Stellaria edwardsii R.Br.
286219: Stellaria ciliatosepala Trautv.
286226: Stellaria laeta Rich. var. altocaulis (Hultén)
286383-286386-286393-286394-286399: Eriophorum angustifolium Honckn. var. elegans Bab.
286385-286387-286388-286389-286390-286391-286392-286396-286397: Eriophorum angustifolium Honckn. var. alpinum Gaudin
286400: Eriophorum angustifolium var. alpinum (sans autorité)
286447: Salix cf. fuscescens Anderss.
286449: Koeleria spicata (L.) Barbera, Quintanar, Soreng & P.M. Peterson
286453-286471: 2e det.: Puccinellia tenella (Lange) Holmb.
286453-286471: 1ère det.: Puccinellia langeana (Berl.) Sørensen ssp. typica
286472-286473-286474: Calamagrostis purpurascens R. Br. apud Richardson in Franklin var. Maltei Polun.
286475-286476-286477: Alopecurus borealis Trin.
286484-286485-286486: Huperzia arctica (Grossh. ex Tolm.) Sipliv.
286487: Elymus arenarius L. var. villosissimus

Claude Lucier    14 novembre 2022

**Comment by brouille** [comment]
Mertensia maritima var. tenella = Mertensia maritima subsp. tenella
Melandrium triflorum = Silene sorensenis
Stellaria ciliatosepala = Stellaria longipes subsp. longipes

**Comment by brouille** [comment]
Ledum palustre var. decumbens = Rhododendron tomentosum
Lychnis affinis = Silene involucrata subsp. involucrata
Empetrum nigrum var. hermaphroditum = Empetrum nigrum subsp. hermaphroditum
Lychnis triflora = Silene sorensenis
Stellaria edwardsii = Stellaria longipes subsp. longipes
Stellaria laeta var. altocaulis = Stellaria longipes subsp. longipes
Eriophorum angustifolium var. elegans = Eriophorum angustifolium subsp. angustifolium [fiche 41123]
Eriophorum angustifolium var. alpinum  = Eriophorum angustifolium subsp. angustifolium [fiche 41102]
Salix fuscescens acc
Koeleria spicata acc [fiche 39565]
Puccinellia tenella acc [fiche 40001]
Puccinellia langeana subsp. typica = Puccinellia tenella subsp. langeana
Calamagrostis purpurascens var. Maltei = Calamagrostis purpurascens
Alopecurus borealis = Alopecurus magellanicus
Huperzia arctica acc
Elymus arenarius var. villosissimus = Leymus mollis subsp. villosissimus
