### ISSUE TITLE
Plantes pour les botanistes de Chine (visiteurs lors de la CP15)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3284]
283412: Maclura pomifera (Raf.) Schneid.
283413: Agastache pallidiflora (Heller) Rydb.    
287244: Corydalis micrantha (Engelm.) Gray. ssp. australis (Chapm.) Ownbey
287547: Corydalis scouleri Hook.
288350: Corydalis caseana ssp. hastata (Rydb.) G.B. Ownbey
288389: Corydalis paucifera (Steph.) Pers.
288438: Saxifraga Mertensiana Bong.
288505: Circaea x intermedia Ehrh.
288506: 2e det.: Chamaerhodos erecta (L.) Bung ssp. nuttallii (T&G) Hult
               1ère det.: Chamaerhodos (sans autorité)
288507: 2e det.: Dryas crenulata Juz.           
288509: 2e det.: Dryas alaskensis Porsild               
288515:  Wisteria floribunda DC               
288516: Sanicula europaea L.
288517: Sanicula graveolens Poepp.
288518: Sanicula septentrionalis Greene
288519: Sanicula nemoralis Greene
288520: Rhamnus lanceolata Pursh              
288522: Nyssa sylvatica Marsh. var. biflora (Walt.) Sarg.
288523: Circaea intermedia Ehrh.           
288526: Circaea caucasica A. Skvortsov 

Claude Lucier   9 janvier 2023

**Comment by brouille** [comment]
Maclura pomifera acc
Agastache pallidiflora acc
Corydalis micrantha subsp. australis acc
Corydalis scouleri acc
Corydalis caseana subsp. hastata acc
Corydalis pauciflora acc

**Comment by brouille** [comment]
Saxifraga Mertensiana acc
Circaea x intermedia  auct = Circaea intermedia = Circaea ×sterilis
Circaea caucasica = Circaea alpina subsp. caulescens
Chamaerhodos acc
Chamaerhodos erecta subsp. nuttallii = Chamaerhodos erecta
Dryas crenulata auct. non Juz. = Dryas incisa
Dryas alaskensis acc
Wisteria floribunda acc
Sanicula europaea acc
Sanicula graveolens acc
Sanicula septentrionalis = Sanicula graveolens
Sanicula nemoralis = Sanicula graveolens
Rhamnus lanceolata acc
Nyssa sylvatica var. biflora = Nyssa biflora
