### ISSUE TITLE
plantes du nord du Québec; pour les botanistes de CAN

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3292]
289317:   Chamaenerion angustifolium (L.) Scop var intermedium Wormskji
289359:  Gentianella tenella (Rottb.) Börner
289377:   Papaver radicans Roottb.

Claude Lucier 24 janvier 2023

**Comment by brouille** [comment]
Chamaenerion angustifolium var intermedium = application incertaine fide FNA
 Gentianella tenella = Comastoma tenellum
 Papaver radicans [erreur typo] =  Papaver radicatum
