### ISSUE TITLE
2 New Taxa + 1 question sur autorité

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3330]
277994   dét. 1
Selaginella apus (var. ciliata)

278016   dét. 1
Araucarioxylon arizonicum Knowlton

Question sur l'autorité d'un nom de Carex
—bD MT, jstor:  Carex pellita Willdenow
(ID de taxon 3067)
<https://plants.jstor.org/stable/10.5555/al.ap.flora.fna023000924>

—Vascan, Kew:  Carex pellita Muhlenberg ex Willdenow
<https://data.canadensys.net/vascan/taxon/5027>
<http://www.theplantlist.org/tpl1.1/record/kew-229617>
<https://wfoplantlist.org/plant-list/taxon/wfo-0000349892-2022-12>

Geoff

**Comment by brouille** [comment]
Araucarioxylon arizonicum acc
Araucariaceae
Je me demande cependant si tu ne devrais pas vérifier le Darwin Core: il pourrait y avoir des champs spéciaux pour fossiles, comme la période géologique, etc

**Comment by brouille** [comment]
Selaginella apus = Selaginella apoda voir fiche 12162
la var. ciliata, entre (), n'existe pas - je propose de la laisser dans la note

**Comment by brouille** [comment]
Carex pellita autorité corrigée
