### ISSUE TITLE
Nom de récolteur avec variant

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#334]
[Originally posted on GoogleCode (id 55) on 2012-02-21]

Stu:

EN corrigeant des noms, je suis tombé sur deux entrées (les seules de Negundo aceroides, 72001 et 71969) récoltées l'un par Oliver, Margaret et l'autre par Oliver, Madge

La date de récolte est semblable 1906-05 et les lieux de récolte en Ontario

Je crois qu'il s'agit d'une seule personne. Il faudrait uniformiser sur Margaret et éliminer Madge - si on peut mettre une note, il serait bon de noter le diminutif

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-02-22 14:22Z by irbv]

Entièrment d'accord
Stu

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-07-13 15:22Z by amy.vandal.13]

Changement ont été faits
