### ISSUE TITLE
New taxon

### ISSUE THREAD

**Issue by CaroleSinou** [irbv-collections/MT-controlled-vocabulary#3513]
Oxytropis arctica var. arctica (workbench : 48049, 48100, 48115)
Koeleria spicata (workbench : 48103)
Pedicularis langsdorffii subsp. arctica (workbench : 48038, 48088)

Spécimens de Daphnée Sansregeret (Cambridge Bay)

Luc, je rajouterai les numéros MT dès que l'importation sera terminée

**Comment by brouille** [comment]
Oxytropis arctica var. arctica acc
Koeleria spicata acc
Pedicularis langsdorffii subsp. arctica acc
