### ISSUE TITLE
Vascan – nouvelle répartition Dryopteris expansa

### ISSUE THREAD

**Issue by CaroleSinou** [irbv-collections/MT-controlled-vocabulary#3515]
Désolé, je n'arrive plus à envoyer des messages via le site de Vascan.
Geoff

Basé sur une révision récente à MT d'Étienne Lacroix-Carignan, Dryopteris expansa serait présent au Saskatchewan; sur l'internet ÉLC a vu que l'espèce serait présente au Manitoba également, mais je n'ai pas trouvé de spécimen pouvant être cité (iNaturalist, Blue Jay Journal, La Biche River Crossing Replacement Vegetation and Rare Plant Report)
Geoff

**Comment by brouille** [comment]
J'ai déjà fait ces additions

MErci
Luc
