### ISSUE TITLE
Vérifier l'autorité d'une var. de Symphyotrichum ontarionis

### ISSUE THREAD

**Issue by CaroleSinou** [irbv-collections/MT-controlled-vocabulary#3566]
Claire m'a signalé le problème suivant :

Dans VASCAN & GBIF
Symphyotrichum ontarionis var. glabratum (Semple) Brouillet & Bouchard est un nom accepté de variété sensu FNA Ed. Comm., 2006b.

Dans MT
ID de taxon 13185
Symphyotrichum ontarionis (Wiegand) G.L. Nesom var. glabratum (Semple) Brouillet & Labrecque

On conclut que le Bouchard est Denis Bouchard dans l'article publié par Brouillet & Labrecque :
1997. New combinations in Symphyotrichum (syn. Aster, Asteraceae: Astereae) species from northeastern North America. Phytologia 82 (3): 137-141
 
Geoff

**Comment by brouille** [comment]
J'ai corrigé l'entrée de la bd - c'était une erreur d'entrée de ma part
VASCAN et GBIF sont corrects (cf FNA)
Merci
Luc
