### ISSUE TITLE
New Taxon - Attente d'ajout pour impression des étiquettes

### ISSUE THREAD

**Issue by CaroleSinou** [irbv-collections/MT-controlled-vocabulary#3604]
Nom pour les spécimens de Biodiversité Conseil récoltés à Rivière-Koksoak (Kativik)

307495, 307496 : Poa interior
307467 : Geum macrophyllum Willdenow subsp. macrophyllum

**Comment by brouille** [comment]
Poa interior acc
Geum macrophyllum subsp. macrophyllum = Geum macrophyllum var. macrophyllum
