### ISSUE TITLE
New Person or combination (Dryopteris)

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3622]
308182: récolteur et det: B. Coleman Ohio 1963
308189: Récolteur et det. #1: E.J.D. Burlington 1938
               det.: #2 J.C. Seymour 1971

Claude Lucier   7 Mai 2024

**Comment by geoffreyhall** [comment]
Un nom ajouté (B. Coleman); E.J.D. = Eleazer Johnson Dole; J.C. Seymour = F.C. Seymour = Frank Conkling Seymour; fiches mises à jour.

Geoffrey
