### ISSUE TITLE
Dryopteris WAT nom

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3640]
309424, 309425: H.F. Calvert Ontario, 1950
309426-309427-309428: L. Gad; D. Hoy; N. Purcell; K. Dudzinski; D. Marchand; L. Gregory, Ontario, 1974
309426-309427-309428: Det.: DH
309433:  récolteur et det. #1: NE?

claude Lucier  11 juin 2024

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour.
Geoffrey
