### ISSUE TITLE
Poa pour A. St-Jean (UQAR) 

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3647]
15435-26065: déterminateur: Anthony St-Jean (UQAR)
309970: récolteur:  W.I. Illman; Ontario; 1981
                déterminateur: W.I. Illman + W.G. Dore; Ontario; 1981  [W.G. dore est dans la base de donnée]

Claude Lucier    19 juin 2024

**Comment by geoffreyhall** [comment]
Noms ajoutés, fiches mises à jour.
Geoffrey
