### ISSUE TITLE
 Dryopteridaceae

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3648]
dryopteris x ambroseae      Europe
il n'y a pas de fiche à ce nom

**Comment by herbier** [comment]
Dryopteris ardechensis Fraser-Jenkins    Europe
Dryopteris corleyi Fraser-Jenkins

**Comment by brouille** [comment]
Dryopteris ×ambroseae acc
Dryopteris ardechensis acc
Dryopteris corleyi acc
