### ISSUE TITLE
Nolia

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#3655]
Fiche 117435 -
rien dans la littérature de Worldplants, pour Ortiz, par rapport au sujet concerné

BHL - peut-être que vous avez vu ce document: requête : Epidendrum smithii
https://www.biodiversitylibrary.org/page/2452643#page/220/mode/1up

lequel Ortiz il y a :
https://species.wikimedia.org/wiki/Ortiz

voilà

**Comment by CaroleSinou** [comment]
Ce que Nolia voulait dire :
Il y a plusieurs Ortiz, visibles ici : https://species.wikimedia.org/wiki/Ortiz
Quel est le bon Ortiz ?

Pour Nolia, requête = recherche Internet

**Comment by brouille** [comment]
Aucun Ortiz n'est mentionné sur le spécimen ou la source citée

Je ne comprends toujours pas la question concernant de quel Ortiz il s'agit puisqu'il n'y en a pas...
