### ISSUE TITLE
New herbarium

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-controlled-vocabulary#3674]
WELT herbarium  Wellington, New-Zealand
Other names: 
Colonial Museum (1865–1906)
Dominion Museum (1906–1973)
National Museum of New Zealand (1973–1992)
Museum of New Zealand Te Papa Tongarewa (from 1992)

add to MT 198006

**Comment by CaroleSinou** [comment]
Institution ajoutée
