### ISSUE TITLE
New Country, Province, MRC or Park : correction

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#425]
[Originally posted on GoogleCode (id 765) on 2013-11-01]

<b>Country:</b>
<b>Province/State:</b>
<b>MRC/District/County:</b>
Park:Parc national des Lacs-Guillaume-Delisle-et-à-l’Eau-Claire &gt; Réserve de parc national des Lacs-Guillaume-Delisle-et-à-l’Eau-Claire

Il me semble que ce parc n'est plus une réserve mais a été décrété - il faudrait corriger l'entrée

ID of the specimen(s):14414, etc

Your name:Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-11-15 21:40Z]

modification effectuée, fiches mises à jour
