### ISSUE TITLE
New County

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#774]
[Originally posted on GoogleCode (id 539) on 2013-04-04 by francois.lambert.3]

Country: United States
Province/State: Delaware
MRC/District/County: Sussex County

https://www.sussexcountyde.gov/

ID of the specimen(s): 184986

Your name: François Lambert

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-04-08 21:52Z]

Nom(s) ajouté(s) et fiche(s) mise(s) à jour
