### ISSUE TITLE
Add subclass to classification database

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-controlled-vocabulary#816]
[Originally posted on GoogleCode (id 45) on 2012-02-15]

Add subclass to classification table (±12 subclass names)

Add subfamilies and tribes to classification table
Subfamilial classifications are available (for temperate families) in VASCAN
Other families: research each family (ex: Fabaceae/Leguminosae, Asteraceae)

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-10-01 15:50Z by amy.vandal.13]

Le champ subclass a été ajouté à la table Family afin de faciliter la gestion et la recherche de données.

Il reste à populer le champ.
