### ISSUE TITLE
Lycopodium sabinaefolium Willd. var. sitchense (Rupr.) Fern

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#817]
[Originally posted on GoogleCode (id 3) on 2012-02-01 by cl.bouchard6]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

Scientific name:Lycopodium sabinaefolium Willd. var. sitchense (Rupr.) Fern

ID of the specimen(s): 175514

Your name: Claire Bouchard

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-02 20:15Z]

Noter que sabinaefolium est un variant orthographique de sabinifolium (correct) selon IPNI (TROPICOS ne fait pas la distinction, malheureusement)

J'entre le nom sous sabinifolium

La fiche devrait être remplie avec sabinifolium, avec remarque: sabinaefolium

Nous allons voir comment traiter les variants orthographiques

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-02 20:19Z]

Il faut corriger sabinaefolium dans la bd = sabinifolium
