### ISSUE TITLE
New Aster combination

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#866]
[Originally posted on GoogleCode (id 90) on 2012-03-07 by cl.bouchard6]

Scientific name: Aster novi-belgii L. var. johannensis (Fern.) J.C. SEMPLE (?)

Field: 4th determination.

ID of the specimen(s): 176469

Your name: Étienne Léveillé-Bourret

N.B.: Voir note de la 4e détermination... il semble que ce soit une combinaison de Semple, et pas A.G. Jones. Il faudrait corriger l'authorité dans Vascan, dans ce cas!

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-07 19:26Z]

Almut G. Jones a fait les deux combinaisons: var (1987) et subsp (1984)
la nov. comb. de Semple est sans effet et il faut la mettre en note
