### ISSUE TITLE
New taxon: Carex rugosperma Mack. var. umbellata

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#932]
[Originally posted on GoogleCode (id 215) on 2012-06-19 by portokayak]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

Scientific name:  Carex rugosperma Mack. var. umbellata

ID of the specimen(s): 179532

Your name: Diane Juteau

Détermination par Bernard Boivin. 
Inscription manuscrite à l'encre rouge: var. umbellata (C. rugosperma Mack.)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-20 13:19Z]

Diane:

le nom Carex rugosperma var. umbellata n'existe pas. Je ne crois pas que c'est ce que Boivin voulait dire: il voulait dire Carex umbellata var. umbellata, qu'il considérait peut-être syn. de rugosperma (ou vice versa), étant donné la parenthèse

C'est donc l'autonyme que je vais ajouter à la fiche 179532, pas la combinaison demandée. Ce nom était déjà dans la bd. Le nom entre () est ajouté dans les notes de détermination (et non les remarques).

Luc
