### ISSUE TITLE
New taxon: Carex umbellata Schkuhr var. tonsa Fernald

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#933]
[Originally posted on GoogleCode (id 216) on 2012-06-19 by portokayak]

Scientific name: Carex umbellata Schkuhr var. tonsa Fernald

ID of the specimen(s):179533

Your name: Diane Juteau

Récolteurs:  Merritt L. Fernald et Harold St. John

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-20 13:20Z]

Ce nom était déjà dans la bd
Je ne sais pourquoi tu ne le trouvais pas.
Luc
